// Code generated by ent, DO NOT EDIT.

package entitlementbinding

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the entitlementbinding type in the database.
	Label = "entitlement_binding"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLimitDefinitionID holds the string denoting the limit_definition_id field in the database.
	FieldLimitDefinitionID = "limit_definition_id"
	// FieldSubjectType holds the string denoting the subject_type field in the database.
	FieldSubjectType = "subject_type"
	// FieldSubjectID holds the string denoting the subject_id field in the database.
	FieldSubjectID = "subject_id"
	// FieldScopeType holds the string denoting the scope_type field in the database.
	FieldScopeType = "scope_type"
	// FieldScopeID holds the string denoting the scope_id field in the database.
	FieldScopeID = "scope_id"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeLimitDefinition holds the string denoting the limit_definition edge name in mutations.
	EdgeLimitDefinition = "limit_definition"
	// Table holds the table name of the entitlementbinding in the database.
	Table = "entitlement_bindings"
	// LimitDefinitionTable is the table that holds the limit_definition relation/edge.
	LimitDefinitionTable = "entitlement_bindings"
	// LimitDefinitionInverseTable is the table name for the LimitDefinition entity.
	// It exists in this package in order to avoid circular dependency with the "limitdefinition" package.
	LimitDefinitionInverseTable = "limit_definitions"
	// LimitDefinitionColumn is the table column denoting the limit_definition relation/edge.
	LimitDefinitionColumn = "limit_definition_id"
)

// Columns holds all SQL columns for entitlementbinding fields.
var Columns = []string{
	FieldID,
	FieldLimitDefinitionID,
	FieldSubjectType,
	FieldSubjectID,
	FieldScopeType,
	FieldScopeID,
	FieldValue,
	FieldCreatedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSubjectID holds the default value on creation for the "subject_id" field.
	DefaultSubjectID string
	// DefaultScopeID holds the default value on creation for the "scope_id" field.
	DefaultScopeID string
	// DefaultCreatedBy holds the default value on creation for the "created_by" field.
	DefaultCreatedBy string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// SubjectType defines the type for the "subject_type" enum field.
type SubjectType string

// SubjectType values.
const (
	SubjectTypeUser          SubjectType = "user"
	SubjectTypeGroup         SubjectType = "group"
	SubjectTypeSystemDefault SubjectType = "system_default"
)

func (st SubjectType) String() string {
	return string(st)
}

// SubjectTypeValidator is a validator for the "subject_type" field enum values. It is called by the builders before save.
func SubjectTypeValidator(st SubjectType) error {
	switch st {
	case SubjectTypeUser, SubjectTypeGroup, SubjectTypeSystemDefault:
		return nil
	default:
		return fmt.Errorf("entitlementbinding: invalid enum value for subject_type field: %q", st)
	}
}

// ScopeType defines the type for the "scope_type" enum field.
type ScopeType string

// ScopeType values.
const (
	ScopeTypeSystem  ScopeType = "system"
	ScopeTypeProject ScopeType = "project"
)

func (st ScopeType) String() string {
	return string(st)
}

// ScopeTypeValidator is a validator for the "scope_type" field enum values. It is called by the builders before save.
func ScopeTypeValidator(st ScopeType) error {
	switch st {
	case ScopeTypeSystem, ScopeTypeProject:
		return nil
	default:
		return fmt.Errorf("entitlementbinding: invalid enum value for scope_type field: %q", st)
	}
}

// OrderOption defines the ordering options for the EntitlementBinding queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLimitDefinitionID orders the results by the limit_definition_id field.
func ByLimitDefinitionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLimitDefinitionID, opts...).ToFunc()
}

// BySubjectType orders the results by the subject_type field.
func BySubjectType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectType, opts...).ToFunc()
}

// BySubjectID orders the results by the subject_id field.
func BySubjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectID, opts...).ToFunc()
}

// ByScopeType orders the results by the scope_type field.
func ByScopeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeType, opts...).ToFunc()
}

// ByScopeID orders the results by the scope_id field.
func ByScopeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeID, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByLimitDefinitionField orders the results by limit_definition field.
func ByLimitDefinitionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLimitDefinitionStep(), sql.OrderByField(field, opts...))
	}
}
func newLimitDefinitionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LimitDefinitionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LimitDefinitionTable, LimitDefinitionColumn),
	)
}
