// Code generated by ent, DO NOT EDIT.

package accessconstraint

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the accessconstraint type in the database.
	Label = "access_constraint"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSubjectKind holds the string denoting the subject_kind field in the database.
	FieldSubjectKind = "subject_kind"
	// FieldSubjectPrincipalType holds the string denoting the subject_principal_type field in the database.
	FieldSubjectPrincipalType = "subject_principal_type"
	// FieldSubjectPrincipalID holds the string denoting the subject_principal_id field in the database.
	FieldSubjectPrincipalID = "subject_principal_id"
	// FieldSubjectGroupID holds the string denoting the subject_group_id field in the database.
	FieldSubjectGroupID = "subject_group_id"
	// FieldScopeType holds the string denoting the scope_type field in the database.
	FieldScopeType = "scope_type"
	// FieldScopeID holds the string denoting the scope_id field in the database.
	FieldScopeID = "scope_id"
	// FieldMaximumPermissions holds the string denoting the maximum_permissions field in the database.
	FieldMaximumPermissions = "maximum_permissions"
	// FieldNotBefore holds the string denoting the not_before field in the database.
	FieldNotBefore = "not_before"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldDisabled holds the string denoting the disabled field in the database.
	FieldDisabled = "disabled"
	// FieldRevision holds the string denoting the revision field in the database.
	FieldRevision = "revision"
	// FieldPurpose holds the string denoting the purpose field in the database.
	FieldPurpose = "purpose"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldCreated holds the string denoting the created field in the database.
	FieldCreated = "created"
	// FieldUpdated holds the string denoting the updated field in the database.
	FieldUpdated = "updated"
	// Table holds the table name of the accessconstraint in the database.
	Table = "access_constraints"
)

// Columns holds all SQL columns for accessconstraint fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSubjectKind,
	FieldSubjectPrincipalType,
	FieldSubjectPrincipalID,
	FieldSubjectGroupID,
	FieldScopeType,
	FieldScopeID,
	FieldMaximumPermissions,
	FieldNotBefore,
	FieldExpiresAt,
	FieldDisabled,
	FieldRevision,
	FieldPurpose,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldCreated,
	FieldUpdated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultScopeID holds the default value on creation for the "scope_id" field.
	DefaultScopeID string
	// DefaultDisabled holds the default value on creation for the "disabled" field.
	DefaultDisabled bool
	// DefaultRevision holds the default value on creation for the "revision" field.
	DefaultRevision int64
	// DefaultPurpose holds the default value on creation for the "purpose" field.
	DefaultPurpose string
	// PurposeValidator is a validator for the "purpose" field. It is called by the builders before save.
	PurposeValidator func(string) error
	// DefaultCreated holds the default value on creation for the "created" field.
	DefaultCreated func() time.Time
	// DefaultUpdated holds the default value on creation for the "updated" field.
	DefaultUpdated func() time.Time
	// UpdateDefaultUpdated holds the default value on update for the "updated" field.
	UpdateDefaultUpdated func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// SubjectKind defines the type for the "subject_kind" enum field.
type SubjectKind string

// SubjectKind values.
const (
	SubjectKindPrincipal     SubjectKind = "principal"
	SubjectKindGroupClosure  SubjectKind = "group_closure"
	SubjectKindAllPrincipals SubjectKind = "all_principals"
)

func (sk SubjectKind) String() string {
	return string(sk)
}

// SubjectKindValidator is a validator for the "subject_kind" field enum values. It is called by the builders before save.
func SubjectKindValidator(sk SubjectKind) error {
	switch sk {
	case SubjectKindPrincipal, SubjectKindGroupClosure, SubjectKindAllPrincipals:
		return nil
	default:
		return fmt.Errorf("accessconstraint: invalid enum value for subject_kind field: %q", sk)
	}
}

// ScopeType defines the type for the "scope_type" enum field.
type ScopeType string

// ScopeType values.
const (
	ScopeTypeSystem  ScopeType = "system"
	ScopeTypeProject ScopeType = "project"
)

func (st ScopeType) String() string {
	return string(st)
}

// ScopeTypeValidator is a validator for the "scope_type" field enum values. It is called by the builders before save.
func ScopeTypeValidator(st ScopeType) error {
	switch st {
	case ScopeTypeSystem, ScopeTypeProject:
		return nil
	default:
		return fmt.Errorf("accessconstraint: invalid enum value for scope_type field: %q", st)
	}
}

// OrderOption defines the ordering options for the AccessConstraint queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySubjectKind orders the results by the subject_kind field.
func BySubjectKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectKind, opts...).ToFunc()
}

// BySubjectPrincipalType orders the results by the subject_principal_type field.
func BySubjectPrincipalType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectPrincipalType, opts...).ToFunc()
}

// BySubjectPrincipalID orders the results by the subject_principal_id field.
func BySubjectPrincipalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectPrincipalID, opts...).ToFunc()
}

// BySubjectGroupID orders the results by the subject_group_id field.
func BySubjectGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectGroupID, opts...).ToFunc()
}

// ByScopeType orders the results by the scope_type field.
func ByScopeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeType, opts...).ToFunc()
}

// ByScopeID orders the results by the scope_id field.
func ByScopeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeID, opts...).ToFunc()
}

// ByNotBefore orders the results by the not_before field.
func ByNotBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotBefore, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByDisabled orders the results by the disabled field.
func ByDisabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisabled, opts...).ToFunc()
}

// ByRevision orders the results by the revision field.
func ByRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevision, opts...).ToFunc()
}

// ByPurpose orders the results by the purpose field.
func ByPurpose(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurpose, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByCreated orders the results by the created field.
func ByCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreated, opts...).ToFunc()
}

// ByUpdated orders the results by the updated field.
func ByUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdated, opts...).ToFunc()
}
