// Code generated by ent, DO NOT EDIT.

package usagereservation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldLTE(FieldID, id))
}

// LimitDefinitionID applies equality check predicate on the "limit_definition_id" field. It's identical to LimitDefinitionIDEQ.
func LimitDefinitionID(v uuid.UUID) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEQ(FieldLimitDefinitionID, v))
}

// SubjectID applies equality check predicate on the "subject_id" field. It's identical to SubjectIDEQ.
func SubjectID(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEQ(FieldSubjectID, v))
}

// ScopeID applies equality check predicate on the "scope_id" field. It's identical to ScopeIDEQ.
func ScopeID(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEQ(FieldScopeID, v))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEQ(FieldResourceID, v))
}

// Reserved applies equality check predicate on the "reserved" field. It's identical to ReservedEQ.
func Reserved(v int64) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEQ(FieldReserved, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEQ(FieldCreatedAt, v))
}

// ReleasedAt applies equality check predicate on the "released_at" field. It's identical to ReleasedAtEQ.
func ReleasedAt(v time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEQ(FieldReleasedAt, v))
}

// LimitDefinitionIDEQ applies the EQ predicate on the "limit_definition_id" field.
func LimitDefinitionIDEQ(v uuid.UUID) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEQ(FieldLimitDefinitionID, v))
}

// LimitDefinitionIDNEQ applies the NEQ predicate on the "limit_definition_id" field.
func LimitDefinitionIDNEQ(v uuid.UUID) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNEQ(FieldLimitDefinitionID, v))
}

// LimitDefinitionIDIn applies the In predicate on the "limit_definition_id" field.
func LimitDefinitionIDIn(vs ...uuid.UUID) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldIn(FieldLimitDefinitionID, vs...))
}

// LimitDefinitionIDNotIn applies the NotIn predicate on the "limit_definition_id" field.
func LimitDefinitionIDNotIn(vs ...uuid.UUID) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNotIn(FieldLimitDefinitionID, vs...))
}

// SubjectIDEQ applies the EQ predicate on the "subject_id" field.
func SubjectIDEQ(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEQ(FieldSubjectID, v))
}

// SubjectIDNEQ applies the NEQ predicate on the "subject_id" field.
func SubjectIDNEQ(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNEQ(FieldSubjectID, v))
}

// SubjectIDIn applies the In predicate on the "subject_id" field.
func SubjectIDIn(vs ...string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldIn(FieldSubjectID, vs...))
}

// SubjectIDNotIn applies the NotIn predicate on the "subject_id" field.
func SubjectIDNotIn(vs ...string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNotIn(FieldSubjectID, vs...))
}

// SubjectIDGT applies the GT predicate on the "subject_id" field.
func SubjectIDGT(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldGT(FieldSubjectID, v))
}

// SubjectIDGTE applies the GTE predicate on the "subject_id" field.
func SubjectIDGTE(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldGTE(FieldSubjectID, v))
}

// SubjectIDLT applies the LT predicate on the "subject_id" field.
func SubjectIDLT(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldLT(FieldSubjectID, v))
}

// SubjectIDLTE applies the LTE predicate on the "subject_id" field.
func SubjectIDLTE(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldLTE(FieldSubjectID, v))
}

// SubjectIDContains applies the Contains predicate on the "subject_id" field.
func SubjectIDContains(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldContains(FieldSubjectID, v))
}

// SubjectIDHasPrefix applies the HasPrefix predicate on the "subject_id" field.
func SubjectIDHasPrefix(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldHasPrefix(FieldSubjectID, v))
}

// SubjectIDHasSuffix applies the HasSuffix predicate on the "subject_id" field.
func SubjectIDHasSuffix(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldHasSuffix(FieldSubjectID, v))
}

// SubjectIDEqualFold applies the EqualFold predicate on the "subject_id" field.
func SubjectIDEqualFold(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEqualFold(FieldSubjectID, v))
}

// SubjectIDContainsFold applies the ContainsFold predicate on the "subject_id" field.
func SubjectIDContainsFold(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldContainsFold(FieldSubjectID, v))
}

// ScopeTypeEQ applies the EQ predicate on the "scope_type" field.
func ScopeTypeEQ(v ScopeType) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEQ(FieldScopeType, v))
}

// ScopeTypeNEQ applies the NEQ predicate on the "scope_type" field.
func ScopeTypeNEQ(v ScopeType) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNEQ(FieldScopeType, v))
}

// ScopeTypeIn applies the In predicate on the "scope_type" field.
func ScopeTypeIn(vs ...ScopeType) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldIn(FieldScopeType, vs...))
}

// ScopeTypeNotIn applies the NotIn predicate on the "scope_type" field.
func ScopeTypeNotIn(vs ...ScopeType) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNotIn(FieldScopeType, vs...))
}

// ScopeIDEQ applies the EQ predicate on the "scope_id" field.
func ScopeIDEQ(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEQ(FieldScopeID, v))
}

// ScopeIDNEQ applies the NEQ predicate on the "scope_id" field.
func ScopeIDNEQ(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNEQ(FieldScopeID, v))
}

// ScopeIDIn applies the In predicate on the "scope_id" field.
func ScopeIDIn(vs ...string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldIn(FieldScopeID, vs...))
}

// ScopeIDNotIn applies the NotIn predicate on the "scope_id" field.
func ScopeIDNotIn(vs ...string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNotIn(FieldScopeID, vs...))
}

// ScopeIDGT applies the GT predicate on the "scope_id" field.
func ScopeIDGT(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldGT(FieldScopeID, v))
}

// ScopeIDGTE applies the GTE predicate on the "scope_id" field.
func ScopeIDGTE(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldGTE(FieldScopeID, v))
}

// ScopeIDLT applies the LT predicate on the "scope_id" field.
func ScopeIDLT(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldLT(FieldScopeID, v))
}

// ScopeIDLTE applies the LTE predicate on the "scope_id" field.
func ScopeIDLTE(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldLTE(FieldScopeID, v))
}

// ScopeIDContains applies the Contains predicate on the "scope_id" field.
func ScopeIDContains(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldContains(FieldScopeID, v))
}

// ScopeIDHasPrefix applies the HasPrefix predicate on the "scope_id" field.
func ScopeIDHasPrefix(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldHasPrefix(FieldScopeID, v))
}

// ScopeIDHasSuffix applies the HasSuffix predicate on the "scope_id" field.
func ScopeIDHasSuffix(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldHasSuffix(FieldScopeID, v))
}

// ScopeIDEqualFold applies the EqualFold predicate on the "scope_id" field.
func ScopeIDEqualFold(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEqualFold(FieldScopeID, v))
}

// ScopeIDContainsFold applies the ContainsFold predicate on the "scope_id" field.
func ScopeIDContainsFold(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldContainsFold(FieldScopeID, v))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNotIn(FieldResourceID, vs...))
}

// ResourceIDGT applies the GT predicate on the "resource_id" field.
func ResourceIDGT(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldGT(FieldResourceID, v))
}

// ResourceIDGTE applies the GTE predicate on the "resource_id" field.
func ResourceIDGTE(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldGTE(FieldResourceID, v))
}

// ResourceIDLT applies the LT predicate on the "resource_id" field.
func ResourceIDLT(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldLT(FieldResourceID, v))
}

// ResourceIDLTE applies the LTE predicate on the "resource_id" field.
func ResourceIDLTE(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldLTE(FieldResourceID, v))
}

// ResourceIDContains applies the Contains predicate on the "resource_id" field.
func ResourceIDContains(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldContains(FieldResourceID, v))
}

// ResourceIDHasPrefix applies the HasPrefix predicate on the "resource_id" field.
func ResourceIDHasPrefix(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldHasPrefix(FieldResourceID, v))
}

// ResourceIDHasSuffix applies the HasSuffix predicate on the "resource_id" field.
func ResourceIDHasSuffix(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldHasSuffix(FieldResourceID, v))
}

// ResourceIDEqualFold applies the EqualFold predicate on the "resource_id" field.
func ResourceIDEqualFold(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEqualFold(FieldResourceID, v))
}

// ResourceIDContainsFold applies the ContainsFold predicate on the "resource_id" field.
func ResourceIDContainsFold(v string) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldContainsFold(FieldResourceID, v))
}

// ReservedEQ applies the EQ predicate on the "reserved" field.
func ReservedEQ(v int64) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEQ(FieldReserved, v))
}

// ReservedNEQ applies the NEQ predicate on the "reserved" field.
func ReservedNEQ(v int64) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNEQ(FieldReserved, v))
}

// ReservedIn applies the In predicate on the "reserved" field.
func ReservedIn(vs ...int64) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldIn(FieldReserved, vs...))
}

// ReservedNotIn applies the NotIn predicate on the "reserved" field.
func ReservedNotIn(vs ...int64) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNotIn(FieldReserved, vs...))
}

// ReservedGT applies the GT predicate on the "reserved" field.
func ReservedGT(v int64) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldGT(FieldReserved, v))
}

// ReservedGTE applies the GTE predicate on the "reserved" field.
func ReservedGTE(v int64) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldGTE(FieldReserved, v))
}

// ReservedLT applies the LT predicate on the "reserved" field.
func ReservedLT(v int64) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldLT(FieldReserved, v))
}

// ReservedLTE applies the LTE predicate on the "reserved" field.
func ReservedLTE(v int64) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldLTE(FieldReserved, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldLTE(FieldCreatedAt, v))
}

// ReleasedAtEQ applies the EQ predicate on the "released_at" field.
func ReleasedAtEQ(v time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldEQ(FieldReleasedAt, v))
}

// ReleasedAtNEQ applies the NEQ predicate on the "released_at" field.
func ReleasedAtNEQ(v time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNEQ(FieldReleasedAt, v))
}

// ReleasedAtIn applies the In predicate on the "released_at" field.
func ReleasedAtIn(vs ...time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldIn(FieldReleasedAt, vs...))
}

// ReleasedAtNotIn applies the NotIn predicate on the "released_at" field.
func ReleasedAtNotIn(vs ...time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNotIn(FieldReleasedAt, vs...))
}

// ReleasedAtGT applies the GT predicate on the "released_at" field.
func ReleasedAtGT(v time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldGT(FieldReleasedAt, v))
}

// ReleasedAtGTE applies the GTE predicate on the "released_at" field.
func ReleasedAtGTE(v time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldGTE(FieldReleasedAt, v))
}

// ReleasedAtLT applies the LT predicate on the "released_at" field.
func ReleasedAtLT(v time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldLT(FieldReleasedAt, v))
}

// ReleasedAtLTE applies the LTE predicate on the "released_at" field.
func ReleasedAtLTE(v time.Time) predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldLTE(FieldReleasedAt, v))
}

// ReleasedAtIsNil applies the IsNil predicate on the "released_at" field.
func ReleasedAtIsNil() predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldIsNull(FieldReleasedAt))
}

// ReleasedAtNotNil applies the NotNil predicate on the "released_at" field.
func ReleasedAtNotNil() predicate.UsageReservation {
	return predicate.UsageReservation(sql.FieldNotNull(FieldReleasedAt))
}

// HasLimitDefinition applies the HasEdge predicate on the "limit_definition" edge.
func HasLimitDefinition() predicate.UsageReservation {
	return predicate.UsageReservation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LimitDefinitionTable, LimitDefinitionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLimitDefinitionWith applies the HasEdge predicate on the "limit_definition" edge with a given conditions (other predicates).
func HasLimitDefinitionWith(preds ...predicate.LimitDefinition) predicate.UsageReservation {
	return predicate.UsageReservation(func(s *sql.Selector) {
		step := newLimitDefinitionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageReservation) predicate.UsageReservation {
	return predicate.UsageReservation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageReservation) predicate.UsageReservation {
	return predicate.UsageReservation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageReservation) predicate.UsageReservation {
	return predicate.UsageReservation(sql.NotPredicates(p))
}
