// Code generated by ent, DO NOT EDIT.

package agentsessionmetrics

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLTE(FieldID, id))
}

// AgentID applies equality check predicate on the "agent_id" field. It's identical to AgentIDEQ.
func AgentID(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldAgentID, v))
}

// GroveID applies equality check predicate on the "grove_id" field. It's identical to GroveIDEQ.
func GroveID(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldGroveID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldSessionID, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldStartedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldEndedAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldStatus, v))
}

// TurnCount applies equality check predicate on the "turn_count" field. It's identical to TurnCountEQ.
func TurnCount(v int) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldTurnCount, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldModel, v))
}

// TokensInput applies equality check predicate on the "tokens_input" field. It's identical to TokensInputEQ.
func TokensInput(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldTokensInput, v))
}

// TokensOutput applies equality check predicate on the "tokens_output" field. It's identical to TokensOutputEQ.
func TokensOutput(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldTokensOutput, v))
}

// TokensCached applies equality check predicate on the "tokens_cached" field. It's identical to TokensCachedEQ.
func TokensCached(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldTokensCached, v))
}

// TokensReasoning applies equality check predicate on the "tokens_reasoning" field. It's identical to TokensReasoningEQ.
func TokensReasoning(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldTokensReasoning, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldCreatedAt, v))
}

// AgentIDEQ applies the EQ predicate on the "agent_id" field.
func AgentIDEQ(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldAgentID, v))
}

// AgentIDNEQ applies the NEQ predicate on the "agent_id" field.
func AgentIDNEQ(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNEQ(FieldAgentID, v))
}

// AgentIDIn applies the In predicate on the "agent_id" field.
func AgentIDIn(vs ...string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIn(FieldAgentID, vs...))
}

// AgentIDNotIn applies the NotIn predicate on the "agent_id" field.
func AgentIDNotIn(vs ...string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotIn(FieldAgentID, vs...))
}

// AgentIDGT applies the GT predicate on the "agent_id" field.
func AgentIDGT(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGT(FieldAgentID, v))
}

// AgentIDGTE applies the GTE predicate on the "agent_id" field.
func AgentIDGTE(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGTE(FieldAgentID, v))
}

// AgentIDLT applies the LT predicate on the "agent_id" field.
func AgentIDLT(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLT(FieldAgentID, v))
}

// AgentIDLTE applies the LTE predicate on the "agent_id" field.
func AgentIDLTE(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLTE(FieldAgentID, v))
}

// AgentIDContains applies the Contains predicate on the "agent_id" field.
func AgentIDContains(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldContains(FieldAgentID, v))
}

// AgentIDHasPrefix applies the HasPrefix predicate on the "agent_id" field.
func AgentIDHasPrefix(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldHasPrefix(FieldAgentID, v))
}

// AgentIDHasSuffix applies the HasSuffix predicate on the "agent_id" field.
func AgentIDHasSuffix(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldHasSuffix(FieldAgentID, v))
}

// AgentIDEqualFold applies the EqualFold predicate on the "agent_id" field.
func AgentIDEqualFold(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEqualFold(FieldAgentID, v))
}

// AgentIDContainsFold applies the ContainsFold predicate on the "agent_id" field.
func AgentIDContainsFold(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldContainsFold(FieldAgentID, v))
}

// GroveIDEQ applies the EQ predicate on the "grove_id" field.
func GroveIDEQ(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldGroveID, v))
}

// GroveIDNEQ applies the NEQ predicate on the "grove_id" field.
func GroveIDNEQ(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNEQ(FieldGroveID, v))
}

// GroveIDIn applies the In predicate on the "grove_id" field.
func GroveIDIn(vs ...string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIn(FieldGroveID, vs...))
}

// GroveIDNotIn applies the NotIn predicate on the "grove_id" field.
func GroveIDNotIn(vs ...string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotIn(FieldGroveID, vs...))
}

// GroveIDGT applies the GT predicate on the "grove_id" field.
func GroveIDGT(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGT(FieldGroveID, v))
}

// GroveIDGTE applies the GTE predicate on the "grove_id" field.
func GroveIDGTE(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGTE(FieldGroveID, v))
}

// GroveIDLT applies the LT predicate on the "grove_id" field.
func GroveIDLT(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLT(FieldGroveID, v))
}

// GroveIDLTE applies the LTE predicate on the "grove_id" field.
func GroveIDLTE(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLTE(FieldGroveID, v))
}

// GroveIDContains applies the Contains predicate on the "grove_id" field.
func GroveIDContains(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldContains(FieldGroveID, v))
}

// GroveIDHasPrefix applies the HasPrefix predicate on the "grove_id" field.
func GroveIDHasPrefix(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldHasPrefix(FieldGroveID, v))
}

// GroveIDHasSuffix applies the HasSuffix predicate on the "grove_id" field.
func GroveIDHasSuffix(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldHasSuffix(FieldGroveID, v))
}

// GroveIDEqualFold applies the EqualFold predicate on the "grove_id" field.
func GroveIDEqualFold(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEqualFold(FieldGroveID, v))
}

// GroveIDContainsFold applies the ContainsFold predicate on the "grove_id" field.
func GroveIDContainsFold(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldContainsFold(FieldGroveID, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldContainsFold(FieldSessionID, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLTE(FieldStartedAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotNull(FieldEndedAt))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotNull(FieldStatus))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldContainsFold(FieldStatus, v))
}

// TurnCountEQ applies the EQ predicate on the "turn_count" field.
func TurnCountEQ(v int) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldTurnCount, v))
}

// TurnCountNEQ applies the NEQ predicate on the "turn_count" field.
func TurnCountNEQ(v int) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNEQ(FieldTurnCount, v))
}

// TurnCountIn applies the In predicate on the "turn_count" field.
func TurnCountIn(vs ...int) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIn(FieldTurnCount, vs...))
}

// TurnCountNotIn applies the NotIn predicate on the "turn_count" field.
func TurnCountNotIn(vs ...int) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotIn(FieldTurnCount, vs...))
}

// TurnCountGT applies the GT predicate on the "turn_count" field.
func TurnCountGT(v int) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGT(FieldTurnCount, v))
}

// TurnCountGTE applies the GTE predicate on the "turn_count" field.
func TurnCountGTE(v int) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGTE(FieldTurnCount, v))
}

// TurnCountLT applies the LT predicate on the "turn_count" field.
func TurnCountLT(v int) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLT(FieldTurnCount, v))
}

// TurnCountLTE applies the LTE predicate on the "turn_count" field.
func TurnCountLTE(v int) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLTE(FieldTurnCount, v))
}

// TurnCountIsNil applies the IsNil predicate on the "turn_count" field.
func TurnCountIsNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIsNull(FieldTurnCount))
}

// TurnCountNotNil applies the NotNil predicate on the "turn_count" field.
func TurnCountNotNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotNull(FieldTurnCount))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldHasSuffix(FieldModel, v))
}

// ModelIsNil applies the IsNil predicate on the "model" field.
func ModelIsNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIsNull(FieldModel))
}

// ModelNotNil applies the NotNil predicate on the "model" field.
func ModelNotNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotNull(FieldModel))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldContainsFold(FieldModel, v))
}

// TokensInputEQ applies the EQ predicate on the "tokens_input" field.
func TokensInputEQ(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldTokensInput, v))
}

// TokensInputNEQ applies the NEQ predicate on the "tokens_input" field.
func TokensInputNEQ(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNEQ(FieldTokensInput, v))
}

// TokensInputIn applies the In predicate on the "tokens_input" field.
func TokensInputIn(vs ...int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIn(FieldTokensInput, vs...))
}

// TokensInputNotIn applies the NotIn predicate on the "tokens_input" field.
func TokensInputNotIn(vs ...int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotIn(FieldTokensInput, vs...))
}

// TokensInputGT applies the GT predicate on the "tokens_input" field.
func TokensInputGT(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGT(FieldTokensInput, v))
}

// TokensInputGTE applies the GTE predicate on the "tokens_input" field.
func TokensInputGTE(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGTE(FieldTokensInput, v))
}

// TokensInputLT applies the LT predicate on the "tokens_input" field.
func TokensInputLT(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLT(FieldTokensInput, v))
}

// TokensInputLTE applies the LTE predicate on the "tokens_input" field.
func TokensInputLTE(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLTE(FieldTokensInput, v))
}

// TokensInputIsNil applies the IsNil predicate on the "tokens_input" field.
func TokensInputIsNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIsNull(FieldTokensInput))
}

// TokensInputNotNil applies the NotNil predicate on the "tokens_input" field.
func TokensInputNotNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotNull(FieldTokensInput))
}

// TokensOutputEQ applies the EQ predicate on the "tokens_output" field.
func TokensOutputEQ(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldTokensOutput, v))
}

// TokensOutputNEQ applies the NEQ predicate on the "tokens_output" field.
func TokensOutputNEQ(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNEQ(FieldTokensOutput, v))
}

// TokensOutputIn applies the In predicate on the "tokens_output" field.
func TokensOutputIn(vs ...int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIn(FieldTokensOutput, vs...))
}

// TokensOutputNotIn applies the NotIn predicate on the "tokens_output" field.
func TokensOutputNotIn(vs ...int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotIn(FieldTokensOutput, vs...))
}

// TokensOutputGT applies the GT predicate on the "tokens_output" field.
func TokensOutputGT(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGT(FieldTokensOutput, v))
}

// TokensOutputGTE applies the GTE predicate on the "tokens_output" field.
func TokensOutputGTE(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGTE(FieldTokensOutput, v))
}

// TokensOutputLT applies the LT predicate on the "tokens_output" field.
func TokensOutputLT(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLT(FieldTokensOutput, v))
}

// TokensOutputLTE applies the LTE predicate on the "tokens_output" field.
func TokensOutputLTE(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLTE(FieldTokensOutput, v))
}

// TokensOutputIsNil applies the IsNil predicate on the "tokens_output" field.
func TokensOutputIsNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIsNull(FieldTokensOutput))
}

// TokensOutputNotNil applies the NotNil predicate on the "tokens_output" field.
func TokensOutputNotNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotNull(FieldTokensOutput))
}

// TokensCachedEQ applies the EQ predicate on the "tokens_cached" field.
func TokensCachedEQ(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldTokensCached, v))
}

// TokensCachedNEQ applies the NEQ predicate on the "tokens_cached" field.
func TokensCachedNEQ(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNEQ(FieldTokensCached, v))
}

// TokensCachedIn applies the In predicate on the "tokens_cached" field.
func TokensCachedIn(vs ...int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIn(FieldTokensCached, vs...))
}

// TokensCachedNotIn applies the NotIn predicate on the "tokens_cached" field.
func TokensCachedNotIn(vs ...int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotIn(FieldTokensCached, vs...))
}

// TokensCachedGT applies the GT predicate on the "tokens_cached" field.
func TokensCachedGT(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGT(FieldTokensCached, v))
}

// TokensCachedGTE applies the GTE predicate on the "tokens_cached" field.
func TokensCachedGTE(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGTE(FieldTokensCached, v))
}

// TokensCachedLT applies the LT predicate on the "tokens_cached" field.
func TokensCachedLT(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLT(FieldTokensCached, v))
}

// TokensCachedLTE applies the LTE predicate on the "tokens_cached" field.
func TokensCachedLTE(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLTE(FieldTokensCached, v))
}

// TokensCachedIsNil applies the IsNil predicate on the "tokens_cached" field.
func TokensCachedIsNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIsNull(FieldTokensCached))
}

// TokensCachedNotNil applies the NotNil predicate on the "tokens_cached" field.
func TokensCachedNotNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotNull(FieldTokensCached))
}

// TokensReasoningEQ applies the EQ predicate on the "tokens_reasoning" field.
func TokensReasoningEQ(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldTokensReasoning, v))
}

// TokensReasoningNEQ applies the NEQ predicate on the "tokens_reasoning" field.
func TokensReasoningNEQ(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNEQ(FieldTokensReasoning, v))
}

// TokensReasoningIn applies the In predicate on the "tokens_reasoning" field.
func TokensReasoningIn(vs ...int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIn(FieldTokensReasoning, vs...))
}

// TokensReasoningNotIn applies the NotIn predicate on the "tokens_reasoning" field.
func TokensReasoningNotIn(vs ...int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotIn(FieldTokensReasoning, vs...))
}

// TokensReasoningGT applies the GT predicate on the "tokens_reasoning" field.
func TokensReasoningGT(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGT(FieldTokensReasoning, v))
}

// TokensReasoningGTE applies the GTE predicate on the "tokens_reasoning" field.
func TokensReasoningGTE(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGTE(FieldTokensReasoning, v))
}

// TokensReasoningLT applies the LT predicate on the "tokens_reasoning" field.
func TokensReasoningLT(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLT(FieldTokensReasoning, v))
}

// TokensReasoningLTE applies the LTE predicate on the "tokens_reasoning" field.
func TokensReasoningLTE(v int64) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLTE(FieldTokensReasoning, v))
}

// TokensReasoningIsNil applies the IsNil predicate on the "tokens_reasoning" field.
func TokensReasoningIsNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIsNull(FieldTokensReasoning))
}

// TokensReasoningNotNil applies the NotNil predicate on the "tokens_reasoning" field.
func TokensReasoningNotNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotNull(FieldTokensReasoning))
}

// ToolCallsIsNil applies the IsNil predicate on the "tool_calls" field.
func ToolCallsIsNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIsNull(FieldToolCalls))
}

// ToolCallsNotNil applies the NotNil predicate on the "tool_calls" field.
func ToolCallsNotNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotNull(FieldToolCalls))
}

// LanguagesIsNil applies the IsNil predicate on the "languages" field.
func LanguagesIsNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIsNull(FieldLanguages))
}

// LanguagesNotNil applies the NotNil predicate on the "languages" field.
func LanguagesNotNil() predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotNull(FieldLanguages))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentSessionMetrics) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentSessionMetrics) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentSessionMetrics) predicate.AgentSessionMetrics {
	return predicate.AgentSessionMetrics(sql.NotPredicates(p))
}
