// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/accessconstraint"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// AccessConstraintUpdate is the builder for updating AccessConstraint entities.
type AccessConstraintUpdate struct {
	config
	hooks    []Hook
	mutation *AccessConstraintMutation
}

// Where appends a list predicates to the AccessConstraintUpdate builder.
func (_u *AccessConstraintUpdate) Where(ps ...predicate.AccessConstraint) *AccessConstraintUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *AccessConstraintUpdate) SetName(v string) *AccessConstraintUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccessConstraintUpdate) SetNillableName(v *string) *AccessConstraintUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSubjectKind sets the "subject_kind" field.
func (_u *AccessConstraintUpdate) SetSubjectKind(v accessconstraint.SubjectKind) *AccessConstraintUpdate {
	_u.mutation.SetSubjectKind(v)
	return _u
}

// SetNillableSubjectKind sets the "subject_kind" field if the given value is not nil.
func (_u *AccessConstraintUpdate) SetNillableSubjectKind(v *accessconstraint.SubjectKind) *AccessConstraintUpdate {
	if v != nil {
		_u.SetSubjectKind(*v)
	}
	return _u
}

// SetSubjectPrincipalType sets the "subject_principal_type" field.
func (_u *AccessConstraintUpdate) SetSubjectPrincipalType(v string) *AccessConstraintUpdate {
	_u.mutation.SetSubjectPrincipalType(v)
	return _u
}

// SetNillableSubjectPrincipalType sets the "subject_principal_type" field if the given value is not nil.
func (_u *AccessConstraintUpdate) SetNillableSubjectPrincipalType(v *string) *AccessConstraintUpdate {
	if v != nil {
		_u.SetSubjectPrincipalType(*v)
	}
	return _u
}

// ClearSubjectPrincipalType clears the value of the "subject_principal_type" field.
func (_u *AccessConstraintUpdate) ClearSubjectPrincipalType() *AccessConstraintUpdate {
	_u.mutation.ClearSubjectPrincipalType()
	return _u
}

// SetSubjectPrincipalID sets the "subject_principal_id" field.
func (_u *AccessConstraintUpdate) SetSubjectPrincipalID(v string) *AccessConstraintUpdate {
	_u.mutation.SetSubjectPrincipalID(v)
	return _u
}

// SetNillableSubjectPrincipalID sets the "subject_principal_id" field if the given value is not nil.
func (_u *AccessConstraintUpdate) SetNillableSubjectPrincipalID(v *string) *AccessConstraintUpdate {
	if v != nil {
		_u.SetSubjectPrincipalID(*v)
	}
	return _u
}

// ClearSubjectPrincipalID clears the value of the "subject_principal_id" field.
func (_u *AccessConstraintUpdate) ClearSubjectPrincipalID() *AccessConstraintUpdate {
	_u.mutation.ClearSubjectPrincipalID()
	return _u
}

// SetSubjectGroupID sets the "subject_group_id" field.
func (_u *AccessConstraintUpdate) SetSubjectGroupID(v string) *AccessConstraintUpdate {
	_u.mutation.SetSubjectGroupID(v)
	return _u
}

// SetNillableSubjectGroupID sets the "subject_group_id" field if the given value is not nil.
func (_u *AccessConstraintUpdate) SetNillableSubjectGroupID(v *string) *AccessConstraintUpdate {
	if v != nil {
		_u.SetSubjectGroupID(*v)
	}
	return _u
}

// ClearSubjectGroupID clears the value of the "subject_group_id" field.
func (_u *AccessConstraintUpdate) ClearSubjectGroupID() *AccessConstraintUpdate {
	_u.mutation.ClearSubjectGroupID()
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *AccessConstraintUpdate) SetScopeType(v accessconstraint.ScopeType) *AccessConstraintUpdate {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *AccessConstraintUpdate) SetNillableScopeType(v *accessconstraint.ScopeType) *AccessConstraintUpdate {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *AccessConstraintUpdate) SetScopeID(v string) *AccessConstraintUpdate {
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *AccessConstraintUpdate) SetNillableScopeID(v *string) *AccessConstraintUpdate {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// SetMaximumPermissions sets the "maximum_permissions" field.
func (_u *AccessConstraintUpdate) SetMaximumPermissions(v []string) *AccessConstraintUpdate {
	_u.mutation.SetMaximumPermissions(v)
	return _u
}

// AppendMaximumPermissions appends value to the "maximum_permissions" field.
func (_u *AccessConstraintUpdate) AppendMaximumPermissions(v []string) *AccessConstraintUpdate {
	_u.mutation.AppendMaximumPermissions(v)
	return _u
}

// SetNotBefore sets the "not_before" field.
func (_u *AccessConstraintUpdate) SetNotBefore(v time.Time) *AccessConstraintUpdate {
	_u.mutation.SetNotBefore(v)
	return _u
}

// SetNillableNotBefore sets the "not_before" field if the given value is not nil.
func (_u *AccessConstraintUpdate) SetNillableNotBefore(v *time.Time) *AccessConstraintUpdate {
	if v != nil {
		_u.SetNotBefore(*v)
	}
	return _u
}

// ClearNotBefore clears the value of the "not_before" field.
func (_u *AccessConstraintUpdate) ClearNotBefore() *AccessConstraintUpdate {
	_u.mutation.ClearNotBefore()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AccessConstraintUpdate) SetExpiresAt(v time.Time) *AccessConstraintUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AccessConstraintUpdate) SetNillableExpiresAt(v *time.Time) *AccessConstraintUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *AccessConstraintUpdate) ClearExpiresAt() *AccessConstraintUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *AccessConstraintUpdate) SetDisabled(v bool) *AccessConstraintUpdate {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *AccessConstraintUpdate) SetNillableDisabled(v *bool) *AccessConstraintUpdate {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetRevision sets the "revision" field.
func (_u *AccessConstraintUpdate) SetRevision(v int64) *AccessConstraintUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *AccessConstraintUpdate) SetNillableRevision(v *int64) *AccessConstraintUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *AccessConstraintUpdate) AddRevision(v int64) *AccessConstraintUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetPurpose sets the "purpose" field.
func (_u *AccessConstraintUpdate) SetPurpose(v string) *AccessConstraintUpdate {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *AccessConstraintUpdate) SetNillablePurpose(v *string) *AccessConstraintUpdate {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AccessConstraintUpdate) SetCreatedBy(v string) *AccessConstraintUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AccessConstraintUpdate) SetNillableCreatedBy(v *string) *AccessConstraintUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *AccessConstraintUpdate) ClearCreatedBy() *AccessConstraintUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *AccessConstraintUpdate) SetUpdatedBy(v string) *AccessConstraintUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *AccessConstraintUpdate) SetNillableUpdatedBy(v *string) *AccessConstraintUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *AccessConstraintUpdate) ClearUpdatedBy() *AccessConstraintUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *AccessConstraintUpdate) SetUpdated(v time.Time) *AccessConstraintUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// Mutation returns the AccessConstraintMutation object of the builder.
func (_u *AccessConstraintUpdate) Mutation() *AccessConstraintMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccessConstraintUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessConstraintUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccessConstraintUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessConstraintUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccessConstraintUpdate) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := accessconstraint.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessConstraintUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accessconstraint.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccessConstraint.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubjectKind(); ok {
		if err := accessconstraint.SubjectKindValidator(v); err != nil {
			return &ValidationError{Name: "subject_kind", err: fmt.Errorf(`ent: validator failed for field "AccessConstraint.subject_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := accessconstraint.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "AccessConstraint.scope_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Purpose(); ok {
		if err := accessconstraint.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "AccessConstraint.purpose": %w`, err)}
		}
	}
	return nil
}

func (_u *AccessConstraintUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accessconstraint.Table, accessconstraint.Columns, sqlgraph.NewFieldSpec(accessconstraint.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accessconstraint.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubjectKind(); ok {
		_spec.SetField(accessconstraint.FieldSubjectKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SubjectPrincipalType(); ok {
		_spec.SetField(accessconstraint.FieldSubjectPrincipalType, field.TypeString, value)
	}
	if _u.mutation.SubjectPrincipalTypeCleared() {
		_spec.ClearField(accessconstraint.FieldSubjectPrincipalType, field.TypeString)
	}
	if value, ok := _u.mutation.SubjectPrincipalID(); ok {
		_spec.SetField(accessconstraint.FieldSubjectPrincipalID, field.TypeString, value)
	}
	if _u.mutation.SubjectPrincipalIDCleared() {
		_spec.ClearField(accessconstraint.FieldSubjectPrincipalID, field.TypeString)
	}
	if value, ok := _u.mutation.SubjectGroupID(); ok {
		_spec.SetField(accessconstraint.FieldSubjectGroupID, field.TypeString, value)
	}
	if _u.mutation.SubjectGroupIDCleared() {
		_spec.ClearField(accessconstraint.FieldSubjectGroupID, field.TypeString)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(accessconstraint.FieldScopeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(accessconstraint.FieldScopeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaximumPermissions(); ok {
		_spec.SetField(accessconstraint.FieldMaximumPermissions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMaximumPermissions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, accessconstraint.FieldMaximumPermissions, value)
		})
	}
	if value, ok := _u.mutation.NotBefore(); ok {
		_spec.SetField(accessconstraint.FieldNotBefore, field.TypeTime, value)
	}
	if _u.mutation.NotBeforeCleared() {
		_spec.ClearField(accessconstraint.FieldNotBefore, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(accessconstraint.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(accessconstraint.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(accessconstraint.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(accessconstraint.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(accessconstraint.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(accessconstraint.FieldPurpose, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(accessconstraint.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(accessconstraint.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(accessconstraint.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(accessconstraint.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(accessconstraint.FieldUpdated, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accessconstraint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccessConstraintUpdateOne is the builder for updating a single AccessConstraint entity.
type AccessConstraintUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccessConstraintMutation
}

// SetName sets the "name" field.
func (_u *AccessConstraintUpdateOne) SetName(v string) *AccessConstraintUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccessConstraintUpdateOne) SetNillableName(v *string) *AccessConstraintUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSubjectKind sets the "subject_kind" field.
func (_u *AccessConstraintUpdateOne) SetSubjectKind(v accessconstraint.SubjectKind) *AccessConstraintUpdateOne {
	_u.mutation.SetSubjectKind(v)
	return _u
}

// SetNillableSubjectKind sets the "subject_kind" field if the given value is not nil.
func (_u *AccessConstraintUpdateOne) SetNillableSubjectKind(v *accessconstraint.SubjectKind) *AccessConstraintUpdateOne {
	if v != nil {
		_u.SetSubjectKind(*v)
	}
	return _u
}

// SetSubjectPrincipalType sets the "subject_principal_type" field.
func (_u *AccessConstraintUpdateOne) SetSubjectPrincipalType(v string) *AccessConstraintUpdateOne {
	_u.mutation.SetSubjectPrincipalType(v)
	return _u
}

// SetNillableSubjectPrincipalType sets the "subject_principal_type" field if the given value is not nil.
func (_u *AccessConstraintUpdateOne) SetNillableSubjectPrincipalType(v *string) *AccessConstraintUpdateOne {
	if v != nil {
		_u.SetSubjectPrincipalType(*v)
	}
	return _u
}

// ClearSubjectPrincipalType clears the value of the "subject_principal_type" field.
func (_u *AccessConstraintUpdateOne) ClearSubjectPrincipalType() *AccessConstraintUpdateOne {
	_u.mutation.ClearSubjectPrincipalType()
	return _u
}

// SetSubjectPrincipalID sets the "subject_principal_id" field.
func (_u *AccessConstraintUpdateOne) SetSubjectPrincipalID(v string) *AccessConstraintUpdateOne {
	_u.mutation.SetSubjectPrincipalID(v)
	return _u
}

// SetNillableSubjectPrincipalID sets the "subject_principal_id" field if the given value is not nil.
func (_u *AccessConstraintUpdateOne) SetNillableSubjectPrincipalID(v *string) *AccessConstraintUpdateOne {
	if v != nil {
		_u.SetSubjectPrincipalID(*v)
	}
	return _u
}

// ClearSubjectPrincipalID clears the value of the "subject_principal_id" field.
func (_u *AccessConstraintUpdateOne) ClearSubjectPrincipalID() *AccessConstraintUpdateOne {
	_u.mutation.ClearSubjectPrincipalID()
	return _u
}

// SetSubjectGroupID sets the "subject_group_id" field.
func (_u *AccessConstraintUpdateOne) SetSubjectGroupID(v string) *AccessConstraintUpdateOne {
	_u.mutation.SetSubjectGroupID(v)
	return _u
}

// SetNillableSubjectGroupID sets the "subject_group_id" field if the given value is not nil.
func (_u *AccessConstraintUpdateOne) SetNillableSubjectGroupID(v *string) *AccessConstraintUpdateOne {
	if v != nil {
		_u.SetSubjectGroupID(*v)
	}
	return _u
}

// ClearSubjectGroupID clears the value of the "subject_group_id" field.
func (_u *AccessConstraintUpdateOne) ClearSubjectGroupID() *AccessConstraintUpdateOne {
	_u.mutation.ClearSubjectGroupID()
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *AccessConstraintUpdateOne) SetScopeType(v accessconstraint.ScopeType) *AccessConstraintUpdateOne {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *AccessConstraintUpdateOne) SetNillableScopeType(v *accessconstraint.ScopeType) *AccessConstraintUpdateOne {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *AccessConstraintUpdateOne) SetScopeID(v string) *AccessConstraintUpdateOne {
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *AccessConstraintUpdateOne) SetNillableScopeID(v *string) *AccessConstraintUpdateOne {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// SetMaximumPermissions sets the "maximum_permissions" field.
func (_u *AccessConstraintUpdateOne) SetMaximumPermissions(v []string) *AccessConstraintUpdateOne {
	_u.mutation.SetMaximumPermissions(v)
	return _u
}

// AppendMaximumPermissions appends value to the "maximum_permissions" field.
func (_u *AccessConstraintUpdateOne) AppendMaximumPermissions(v []string) *AccessConstraintUpdateOne {
	_u.mutation.AppendMaximumPermissions(v)
	return _u
}

// SetNotBefore sets the "not_before" field.
func (_u *AccessConstraintUpdateOne) SetNotBefore(v time.Time) *AccessConstraintUpdateOne {
	_u.mutation.SetNotBefore(v)
	return _u
}

// SetNillableNotBefore sets the "not_before" field if the given value is not nil.
func (_u *AccessConstraintUpdateOne) SetNillableNotBefore(v *time.Time) *AccessConstraintUpdateOne {
	if v != nil {
		_u.SetNotBefore(*v)
	}
	return _u
}

// ClearNotBefore clears the value of the "not_before" field.
func (_u *AccessConstraintUpdateOne) ClearNotBefore() *AccessConstraintUpdateOne {
	_u.mutation.ClearNotBefore()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AccessConstraintUpdateOne) SetExpiresAt(v time.Time) *AccessConstraintUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AccessConstraintUpdateOne) SetNillableExpiresAt(v *time.Time) *AccessConstraintUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *AccessConstraintUpdateOne) ClearExpiresAt() *AccessConstraintUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *AccessConstraintUpdateOne) SetDisabled(v bool) *AccessConstraintUpdateOne {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *AccessConstraintUpdateOne) SetNillableDisabled(v *bool) *AccessConstraintUpdateOne {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetRevision sets the "revision" field.
func (_u *AccessConstraintUpdateOne) SetRevision(v int64) *AccessConstraintUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *AccessConstraintUpdateOne) SetNillableRevision(v *int64) *AccessConstraintUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *AccessConstraintUpdateOne) AddRevision(v int64) *AccessConstraintUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetPurpose sets the "purpose" field.
func (_u *AccessConstraintUpdateOne) SetPurpose(v string) *AccessConstraintUpdateOne {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *AccessConstraintUpdateOne) SetNillablePurpose(v *string) *AccessConstraintUpdateOne {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AccessConstraintUpdateOne) SetCreatedBy(v string) *AccessConstraintUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AccessConstraintUpdateOne) SetNillableCreatedBy(v *string) *AccessConstraintUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *AccessConstraintUpdateOne) ClearCreatedBy() *AccessConstraintUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *AccessConstraintUpdateOne) SetUpdatedBy(v string) *AccessConstraintUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *AccessConstraintUpdateOne) SetNillableUpdatedBy(v *string) *AccessConstraintUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *AccessConstraintUpdateOne) ClearUpdatedBy() *AccessConstraintUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *AccessConstraintUpdateOne) SetUpdated(v time.Time) *AccessConstraintUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// Mutation returns the AccessConstraintMutation object of the builder.
func (_u *AccessConstraintUpdateOne) Mutation() *AccessConstraintMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccessConstraintUpdate builder.
func (_u *AccessConstraintUpdateOne) Where(ps ...predicate.AccessConstraint) *AccessConstraintUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccessConstraintUpdateOne) Select(field string, fields ...string) *AccessConstraintUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccessConstraint entity.
func (_u *AccessConstraintUpdateOne) Save(ctx context.Context) (*AccessConstraint, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessConstraintUpdateOne) SaveX(ctx context.Context) *AccessConstraint {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccessConstraintUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessConstraintUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccessConstraintUpdateOne) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := accessconstraint.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessConstraintUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accessconstraint.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccessConstraint.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubjectKind(); ok {
		if err := accessconstraint.SubjectKindValidator(v); err != nil {
			return &ValidationError{Name: "subject_kind", err: fmt.Errorf(`ent: validator failed for field "AccessConstraint.subject_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := accessconstraint.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "AccessConstraint.scope_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Purpose(); ok {
		if err := accessconstraint.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "AccessConstraint.purpose": %w`, err)}
		}
	}
	return nil
}

func (_u *AccessConstraintUpdateOne) sqlSave(ctx context.Context) (_node *AccessConstraint, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accessconstraint.Table, accessconstraint.Columns, sqlgraph.NewFieldSpec(accessconstraint.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccessConstraint.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accessconstraint.FieldID)
		for _, f := range fields {
			if !accessconstraint.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accessconstraint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accessconstraint.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubjectKind(); ok {
		_spec.SetField(accessconstraint.FieldSubjectKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SubjectPrincipalType(); ok {
		_spec.SetField(accessconstraint.FieldSubjectPrincipalType, field.TypeString, value)
	}
	if _u.mutation.SubjectPrincipalTypeCleared() {
		_spec.ClearField(accessconstraint.FieldSubjectPrincipalType, field.TypeString)
	}
	if value, ok := _u.mutation.SubjectPrincipalID(); ok {
		_spec.SetField(accessconstraint.FieldSubjectPrincipalID, field.TypeString, value)
	}
	if _u.mutation.SubjectPrincipalIDCleared() {
		_spec.ClearField(accessconstraint.FieldSubjectPrincipalID, field.TypeString)
	}
	if value, ok := _u.mutation.SubjectGroupID(); ok {
		_spec.SetField(accessconstraint.FieldSubjectGroupID, field.TypeString, value)
	}
	if _u.mutation.SubjectGroupIDCleared() {
		_spec.ClearField(accessconstraint.FieldSubjectGroupID, field.TypeString)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(accessconstraint.FieldScopeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(accessconstraint.FieldScopeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaximumPermissions(); ok {
		_spec.SetField(accessconstraint.FieldMaximumPermissions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMaximumPermissions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, accessconstraint.FieldMaximumPermissions, value)
		})
	}
	if value, ok := _u.mutation.NotBefore(); ok {
		_spec.SetField(accessconstraint.FieldNotBefore, field.TypeTime, value)
	}
	if _u.mutation.NotBeforeCleared() {
		_spec.ClearField(accessconstraint.FieldNotBefore, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(accessconstraint.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(accessconstraint.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(accessconstraint.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(accessconstraint.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(accessconstraint.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(accessconstraint.FieldPurpose, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(accessconstraint.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(accessconstraint.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(accessconstraint.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(accessconstraint.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(accessconstraint.FieldUpdated, field.TypeTime, value)
	}
	_node = &AccessConstraint{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accessconstraint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
