// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agentsessionmetrics"
	"github.com/google/uuid"
)

// AgentSessionMetrics is the model entity for the AgentSessionMetrics schema.
type AgentSessionMetrics struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// AgentID holds the value of the "agent_id" field.
	AgentID string `json:"agent_id,omitempty"`
	// GroveID holds the value of the "grove_id" field.
	GroveID string `json:"grove_id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// EndedAt holds the value of the "ended_at" field.
	EndedAt *time.Time `json:"ended_at,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// TurnCount holds the value of the "turn_count" field.
	TurnCount int `json:"turn_count,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// TokensInput holds the value of the "tokens_input" field.
	TokensInput int64 `json:"tokens_input,omitempty"`
	// TokensOutput holds the value of the "tokens_output" field.
	TokensOutput int64 `json:"tokens_output,omitempty"`
	// TokensCached holds the value of the "tokens_cached" field.
	TokensCached int64 `json:"tokens_cached,omitempty"`
	// TokensReasoning holds the value of the "tokens_reasoning" field.
	TokensReasoning int64 `json:"tokens_reasoning,omitempty"`
	// ToolCalls holds the value of the "tool_calls" field.
	ToolCalls map[string]interface{} `json:"tool_calls,omitempty"`
	// Languages holds the value of the "languages" field.
	Languages []string `json:"languages,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentSessionMetrics) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agentsessionmetrics.FieldToolCalls, agentsessionmetrics.FieldLanguages:
			values[i] = new([]byte)
		case agentsessionmetrics.FieldTurnCount, agentsessionmetrics.FieldTokensInput, agentsessionmetrics.FieldTokensOutput, agentsessionmetrics.FieldTokensCached, agentsessionmetrics.FieldTokensReasoning:
			values[i] = new(sql.NullInt64)
		case agentsessionmetrics.FieldAgentID, agentsessionmetrics.FieldGroveID, agentsessionmetrics.FieldSessionID, agentsessionmetrics.FieldStatus, agentsessionmetrics.FieldModel:
			values[i] = new(sql.NullString)
		case agentsessionmetrics.FieldStartedAt, agentsessionmetrics.FieldEndedAt, agentsessionmetrics.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case agentsessionmetrics.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentSessionMetrics fields.
func (_m *AgentSessionMetrics) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agentsessionmetrics.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case agentsessionmetrics.FieldAgentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_id", values[i])
			} else if value.Valid {
				_m.AgentID = value.String
			}
		case agentsessionmetrics.FieldGroveID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field grove_id", values[i])
			} else if value.Valid {
				_m.GroveID = value.String
			}
		case agentsessionmetrics.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case agentsessionmetrics.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case agentsessionmetrics.FieldEndedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ended_at", values[i])
			} else if value.Valid {
				_m.EndedAt = new(time.Time)
				*_m.EndedAt = value.Time
			}
		case agentsessionmetrics.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case agentsessionmetrics.FieldTurnCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field turn_count", values[i])
			} else if value.Valid {
				_m.TurnCount = int(value.Int64)
			}
		case agentsessionmetrics.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case agentsessionmetrics.FieldTokensInput:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tokens_input", values[i])
			} else if value.Valid {
				_m.TokensInput = value.Int64
			}
		case agentsessionmetrics.FieldTokensOutput:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tokens_output", values[i])
			} else if value.Valid {
				_m.TokensOutput = value.Int64
			}
		case agentsessionmetrics.FieldTokensCached:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tokens_cached", values[i])
			} else if value.Valid {
				_m.TokensCached = value.Int64
			}
		case agentsessionmetrics.FieldTokensReasoning:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tokens_reasoning", values[i])
			} else if value.Valid {
				_m.TokensReasoning = value.Int64
			}
		case agentsessionmetrics.FieldToolCalls:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tool_calls", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ToolCalls); err != nil {
					return fmt.Errorf("unmarshal field tool_calls: %w", err)
				}
			}
		case agentsessionmetrics.FieldLanguages:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field languages", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Languages); err != nil {
					return fmt.Errorf("unmarshal field languages: %w", err)
				}
			}
		case agentsessionmetrics.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentSessionMetrics.
// This includes values selected through modifiers, order, etc.
func (_m *AgentSessionMetrics) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AgentSessionMetrics.
// Note that you need to call AgentSessionMetrics.Unwrap() before calling this method if this AgentSessionMetrics
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentSessionMetrics) Update() *AgentSessionMetricsUpdateOne {
	return NewAgentSessionMetricsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentSessionMetrics entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentSessionMetrics) Unwrap() *AgentSessionMetrics {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentSessionMetrics is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentSessionMetrics) String() string {
	var builder strings.Builder
	builder.WriteString("AgentSessionMetrics(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("agent_id=")
	builder.WriteString(_m.AgentID)
	builder.WriteString(", ")
	builder.WriteString("grove_id=")
	builder.WriteString(_m.GroveID)
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EndedAt; v != nil {
		builder.WriteString("ended_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("turn_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TurnCount))
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("tokens_input=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokensInput))
	builder.WriteString(", ")
	builder.WriteString("tokens_output=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokensOutput))
	builder.WriteString(", ")
	builder.WriteString("tokens_cached=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokensCached))
	builder.WriteString(", ")
	builder.WriteString("tokens_reasoning=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokensReasoning))
	builder.WriteString(", ")
	builder.WriteString("tool_calls=")
	builder.WriteString(fmt.Sprintf("%v", _m.ToolCalls))
	builder.WriteString(", ")
	builder.WriteString("languages=")
	builder.WriteString(fmt.Sprintf("%v", _m.Languages))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AgentSessionMetricsSlice is a parsable slice of AgentSessionMetrics.
type AgentSessionMetricsSlice []*AgentSessionMetrics
