// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agentsessionmetrics"
	"github.com/google/uuid"
)

// AgentSessionMetricsCreate is the builder for creating a AgentSessionMetrics entity.
type AgentSessionMetricsCreate struct {
	config
	mutation *AgentSessionMetricsMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAgentID sets the "agent_id" field.
func (_c *AgentSessionMetricsCreate) SetAgentID(v string) *AgentSessionMetricsCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetGroveID sets the "grove_id" field.
func (_c *AgentSessionMetricsCreate) SetGroveID(v string) *AgentSessionMetricsCreate {
	_c.mutation.SetGroveID(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *AgentSessionMetricsCreate) SetSessionID(v string) *AgentSessionMetricsCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *AgentSessionMetricsCreate) SetStartedAt(v time.Time) *AgentSessionMetricsCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetEndedAt sets the "ended_at" field.
func (_c *AgentSessionMetricsCreate) SetEndedAt(v time.Time) *AgentSessionMetricsCreate {
	_c.mutation.SetEndedAt(v)
	return _c
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_c *AgentSessionMetricsCreate) SetNillableEndedAt(v *time.Time) *AgentSessionMetricsCreate {
	if v != nil {
		_c.SetEndedAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AgentSessionMetricsCreate) SetStatus(v string) *AgentSessionMetricsCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AgentSessionMetricsCreate) SetNillableStatus(v *string) *AgentSessionMetricsCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTurnCount sets the "turn_count" field.
func (_c *AgentSessionMetricsCreate) SetTurnCount(v int) *AgentSessionMetricsCreate {
	_c.mutation.SetTurnCount(v)
	return _c
}

// SetNillableTurnCount sets the "turn_count" field if the given value is not nil.
func (_c *AgentSessionMetricsCreate) SetNillableTurnCount(v *int) *AgentSessionMetricsCreate {
	if v != nil {
		_c.SetTurnCount(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *AgentSessionMetricsCreate) SetModel(v string) *AgentSessionMetricsCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *AgentSessionMetricsCreate) SetNillableModel(v *string) *AgentSessionMetricsCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetTokensInput sets the "tokens_input" field.
func (_c *AgentSessionMetricsCreate) SetTokensInput(v int64) *AgentSessionMetricsCreate {
	_c.mutation.SetTokensInput(v)
	return _c
}

// SetNillableTokensInput sets the "tokens_input" field if the given value is not nil.
func (_c *AgentSessionMetricsCreate) SetNillableTokensInput(v *int64) *AgentSessionMetricsCreate {
	if v != nil {
		_c.SetTokensInput(*v)
	}
	return _c
}

// SetTokensOutput sets the "tokens_output" field.
func (_c *AgentSessionMetricsCreate) SetTokensOutput(v int64) *AgentSessionMetricsCreate {
	_c.mutation.SetTokensOutput(v)
	return _c
}

// SetNillableTokensOutput sets the "tokens_output" field if the given value is not nil.
func (_c *AgentSessionMetricsCreate) SetNillableTokensOutput(v *int64) *AgentSessionMetricsCreate {
	if v != nil {
		_c.SetTokensOutput(*v)
	}
	return _c
}

// SetTokensCached sets the "tokens_cached" field.
func (_c *AgentSessionMetricsCreate) SetTokensCached(v int64) *AgentSessionMetricsCreate {
	_c.mutation.SetTokensCached(v)
	return _c
}

// SetNillableTokensCached sets the "tokens_cached" field if the given value is not nil.
func (_c *AgentSessionMetricsCreate) SetNillableTokensCached(v *int64) *AgentSessionMetricsCreate {
	if v != nil {
		_c.SetTokensCached(*v)
	}
	return _c
}

// SetTokensReasoning sets the "tokens_reasoning" field.
func (_c *AgentSessionMetricsCreate) SetTokensReasoning(v int64) *AgentSessionMetricsCreate {
	_c.mutation.SetTokensReasoning(v)
	return _c
}

// SetNillableTokensReasoning sets the "tokens_reasoning" field if the given value is not nil.
func (_c *AgentSessionMetricsCreate) SetNillableTokensReasoning(v *int64) *AgentSessionMetricsCreate {
	if v != nil {
		_c.SetTokensReasoning(*v)
	}
	return _c
}

// SetToolCalls sets the "tool_calls" field.
func (_c *AgentSessionMetricsCreate) SetToolCalls(v map[string]interface{}) *AgentSessionMetricsCreate {
	_c.mutation.SetToolCalls(v)
	return _c
}

// SetLanguages sets the "languages" field.
func (_c *AgentSessionMetricsCreate) SetLanguages(v []string) *AgentSessionMetricsCreate {
	_c.mutation.SetLanguages(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentSessionMetricsCreate) SetCreatedAt(v time.Time) *AgentSessionMetricsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentSessionMetricsCreate) SetNillableCreatedAt(v *time.Time) *AgentSessionMetricsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AgentSessionMetricsCreate) SetID(v uuid.UUID) *AgentSessionMetricsCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AgentSessionMetricsCreate) SetNillableID(v *uuid.UUID) *AgentSessionMetricsCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AgentSessionMetricsMutation object of the builder.
func (_c *AgentSessionMetricsCreate) Mutation() *AgentSessionMetricsMutation {
	return _c.mutation
}

// Save creates the AgentSessionMetrics in the database.
func (_c *AgentSessionMetricsCreate) Save(ctx context.Context) (*AgentSessionMetrics, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentSessionMetricsCreate) SaveX(ctx context.Context) *AgentSessionMetrics {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentSessionMetricsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentSessionMetricsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentSessionMetricsCreate) defaults() {
	if _, ok := _c.mutation.TurnCount(); !ok {
		v := agentsessionmetrics.DefaultTurnCount
		_c.mutation.SetTurnCount(v)
	}
	if _, ok := _c.mutation.TokensInput(); !ok {
		v := agentsessionmetrics.DefaultTokensInput
		_c.mutation.SetTokensInput(v)
	}
	if _, ok := _c.mutation.TokensOutput(); !ok {
		v := agentsessionmetrics.DefaultTokensOutput
		_c.mutation.SetTokensOutput(v)
	}
	if _, ok := _c.mutation.TokensCached(); !ok {
		v := agentsessionmetrics.DefaultTokensCached
		_c.mutation.SetTokensCached(v)
	}
	if _, ok := _c.mutation.TokensReasoning(); !ok {
		v := agentsessionmetrics.DefaultTokensReasoning
		_c.mutation.SetTokensReasoning(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agentsessionmetrics.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := agentsessionmetrics.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentSessionMetricsCreate) check() error {
	if _, ok := _c.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "AgentSessionMetrics.agent_id"`)}
	}
	if v, ok := _c.mutation.AgentID(); ok {
		if err := agentsessionmetrics.AgentIDValidator(v); err != nil {
			return &ValidationError{Name: "agent_id", err: fmt.Errorf(`ent: validator failed for field "AgentSessionMetrics.agent_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GroveID(); !ok {
		return &ValidationError{Name: "grove_id", err: errors.New(`ent: missing required field "AgentSessionMetrics.grove_id"`)}
	}
	if v, ok := _c.mutation.GroveID(); ok {
		if err := agentsessionmetrics.GroveIDValidator(v); err != nil {
			return &ValidationError{Name: "grove_id", err: fmt.Errorf(`ent: validator failed for field "AgentSessionMetrics.grove_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "AgentSessionMetrics.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := agentsessionmetrics.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "AgentSessionMetrics.session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "AgentSessionMetrics.started_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentSessionMetrics.created_at"`)}
	}
	return nil
}

func (_c *AgentSessionMetricsCreate) sqlSave(ctx context.Context) (*AgentSessionMetrics, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentSessionMetricsCreate) createSpec() (*AgentSessionMetrics, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentSessionMetrics{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentsessionmetrics.Table, sqlgraph.NewFieldSpec(agentsessionmetrics.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.AgentID(); ok {
		_spec.SetField(agentsessionmetrics.FieldAgentID, field.TypeString, value)
		_node.AgentID = value
	}
	if value, ok := _c.mutation.GroveID(); ok {
		_spec.SetField(agentsessionmetrics.FieldGroveID, field.TypeString, value)
		_node.GroveID = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(agentsessionmetrics.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(agentsessionmetrics.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.EndedAt(); ok {
		_spec.SetField(agentsessionmetrics.FieldEndedAt, field.TypeTime, value)
		_node.EndedAt = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(agentsessionmetrics.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TurnCount(); ok {
		_spec.SetField(agentsessionmetrics.FieldTurnCount, field.TypeInt, value)
		_node.TurnCount = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(agentsessionmetrics.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.TokensInput(); ok {
		_spec.SetField(agentsessionmetrics.FieldTokensInput, field.TypeInt64, value)
		_node.TokensInput = value
	}
	if value, ok := _c.mutation.TokensOutput(); ok {
		_spec.SetField(agentsessionmetrics.FieldTokensOutput, field.TypeInt64, value)
		_node.TokensOutput = value
	}
	if value, ok := _c.mutation.TokensCached(); ok {
		_spec.SetField(agentsessionmetrics.FieldTokensCached, field.TypeInt64, value)
		_node.TokensCached = value
	}
	if value, ok := _c.mutation.TokensReasoning(); ok {
		_spec.SetField(agentsessionmetrics.FieldTokensReasoning, field.TypeInt64, value)
		_node.TokensReasoning = value
	}
	if value, ok := _c.mutation.ToolCalls(); ok {
		_spec.SetField(agentsessionmetrics.FieldToolCalls, field.TypeJSON, value)
		_node.ToolCalls = value
	}
	if value, ok := _c.mutation.Languages(); ok {
		_spec.SetField(agentsessionmetrics.FieldLanguages, field.TypeJSON, value)
		_node.Languages = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agentsessionmetrics.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AgentSessionMetrics.Create().
//		SetAgentID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AgentSessionMetricsUpsert) {
//			SetAgentID(v+v).
//		}).
//		Exec(ctx)
func (_c *AgentSessionMetricsCreate) OnConflict(opts ...sql.ConflictOption) *AgentSessionMetricsUpsertOne {
	_c.conflict = opts
	return &AgentSessionMetricsUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AgentSessionMetrics.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AgentSessionMetricsCreate) OnConflictColumns(columns ...string) *AgentSessionMetricsUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AgentSessionMetricsUpsertOne{
		create: _c,
	}
}

type (
	// AgentSessionMetricsUpsertOne is the builder for "upsert"-ing
	//  one AgentSessionMetrics node.
	AgentSessionMetricsUpsertOne struct {
		create *AgentSessionMetricsCreate
	}

	// AgentSessionMetricsUpsert is the "OnConflict" setter.
	AgentSessionMetricsUpsert struct {
		*sql.UpdateSet
	}
)

// SetAgentID sets the "agent_id" field.
func (u *AgentSessionMetricsUpsert) SetAgentID(v string) *AgentSessionMetricsUpsert {
	u.Set(agentsessionmetrics.FieldAgentID, v)
	return u
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsert) UpdateAgentID() *AgentSessionMetricsUpsert {
	u.SetExcluded(agentsessionmetrics.FieldAgentID)
	return u
}

// SetGroveID sets the "grove_id" field.
func (u *AgentSessionMetricsUpsert) SetGroveID(v string) *AgentSessionMetricsUpsert {
	u.Set(agentsessionmetrics.FieldGroveID, v)
	return u
}

// UpdateGroveID sets the "grove_id" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsert) UpdateGroveID() *AgentSessionMetricsUpsert {
	u.SetExcluded(agentsessionmetrics.FieldGroveID)
	return u
}

// SetSessionID sets the "session_id" field.
func (u *AgentSessionMetricsUpsert) SetSessionID(v string) *AgentSessionMetricsUpsert {
	u.Set(agentsessionmetrics.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsert) UpdateSessionID() *AgentSessionMetricsUpsert {
	u.SetExcluded(agentsessionmetrics.FieldSessionID)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *AgentSessionMetricsUpsert) SetStartedAt(v time.Time) *AgentSessionMetricsUpsert {
	u.Set(agentsessionmetrics.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsert) UpdateStartedAt() *AgentSessionMetricsUpsert {
	u.SetExcluded(agentsessionmetrics.FieldStartedAt)
	return u
}

// SetEndedAt sets the "ended_at" field.
func (u *AgentSessionMetricsUpsert) SetEndedAt(v time.Time) *AgentSessionMetricsUpsert {
	u.Set(agentsessionmetrics.FieldEndedAt, v)
	return u
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsert) UpdateEndedAt() *AgentSessionMetricsUpsert {
	u.SetExcluded(agentsessionmetrics.FieldEndedAt)
	return u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *AgentSessionMetricsUpsert) ClearEndedAt() *AgentSessionMetricsUpsert {
	u.SetNull(agentsessionmetrics.FieldEndedAt)
	return u
}

// SetStatus sets the "status" field.
func (u *AgentSessionMetricsUpsert) SetStatus(v string) *AgentSessionMetricsUpsert {
	u.Set(agentsessionmetrics.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsert) UpdateStatus() *AgentSessionMetricsUpsert {
	u.SetExcluded(agentsessionmetrics.FieldStatus)
	return u
}

// ClearStatus clears the value of the "status" field.
func (u *AgentSessionMetricsUpsert) ClearStatus() *AgentSessionMetricsUpsert {
	u.SetNull(agentsessionmetrics.FieldStatus)
	return u
}

// SetTurnCount sets the "turn_count" field.
func (u *AgentSessionMetricsUpsert) SetTurnCount(v int) *AgentSessionMetricsUpsert {
	u.Set(agentsessionmetrics.FieldTurnCount, v)
	return u
}

// UpdateTurnCount sets the "turn_count" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsert) UpdateTurnCount() *AgentSessionMetricsUpsert {
	u.SetExcluded(agentsessionmetrics.FieldTurnCount)
	return u
}

// AddTurnCount adds v to the "turn_count" field.
func (u *AgentSessionMetricsUpsert) AddTurnCount(v int) *AgentSessionMetricsUpsert {
	u.Add(agentsessionmetrics.FieldTurnCount, v)
	return u
}

// ClearTurnCount clears the value of the "turn_count" field.
func (u *AgentSessionMetricsUpsert) ClearTurnCount() *AgentSessionMetricsUpsert {
	u.SetNull(agentsessionmetrics.FieldTurnCount)
	return u
}

// SetModel sets the "model" field.
func (u *AgentSessionMetricsUpsert) SetModel(v string) *AgentSessionMetricsUpsert {
	u.Set(agentsessionmetrics.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsert) UpdateModel() *AgentSessionMetricsUpsert {
	u.SetExcluded(agentsessionmetrics.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *AgentSessionMetricsUpsert) ClearModel() *AgentSessionMetricsUpsert {
	u.SetNull(agentsessionmetrics.FieldModel)
	return u
}

// SetTokensInput sets the "tokens_input" field.
func (u *AgentSessionMetricsUpsert) SetTokensInput(v int64) *AgentSessionMetricsUpsert {
	u.Set(agentsessionmetrics.FieldTokensInput, v)
	return u
}

// UpdateTokensInput sets the "tokens_input" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsert) UpdateTokensInput() *AgentSessionMetricsUpsert {
	u.SetExcluded(agentsessionmetrics.FieldTokensInput)
	return u
}

// AddTokensInput adds v to the "tokens_input" field.
func (u *AgentSessionMetricsUpsert) AddTokensInput(v int64) *AgentSessionMetricsUpsert {
	u.Add(agentsessionmetrics.FieldTokensInput, v)
	return u
}

// ClearTokensInput clears the value of the "tokens_input" field.
func (u *AgentSessionMetricsUpsert) ClearTokensInput() *AgentSessionMetricsUpsert {
	u.SetNull(agentsessionmetrics.FieldTokensInput)
	return u
}

// SetTokensOutput sets the "tokens_output" field.
func (u *AgentSessionMetricsUpsert) SetTokensOutput(v int64) *AgentSessionMetricsUpsert {
	u.Set(agentsessionmetrics.FieldTokensOutput, v)
	return u
}

// UpdateTokensOutput sets the "tokens_output" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsert) UpdateTokensOutput() *AgentSessionMetricsUpsert {
	u.SetExcluded(agentsessionmetrics.FieldTokensOutput)
	return u
}

// AddTokensOutput adds v to the "tokens_output" field.
func (u *AgentSessionMetricsUpsert) AddTokensOutput(v int64) *AgentSessionMetricsUpsert {
	u.Add(agentsessionmetrics.FieldTokensOutput, v)
	return u
}

// ClearTokensOutput clears the value of the "tokens_output" field.
func (u *AgentSessionMetricsUpsert) ClearTokensOutput() *AgentSessionMetricsUpsert {
	u.SetNull(agentsessionmetrics.FieldTokensOutput)
	return u
}

// SetTokensCached sets the "tokens_cached" field.
func (u *AgentSessionMetricsUpsert) SetTokensCached(v int64) *AgentSessionMetricsUpsert {
	u.Set(agentsessionmetrics.FieldTokensCached, v)
	return u
}

// UpdateTokensCached sets the "tokens_cached" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsert) UpdateTokensCached() *AgentSessionMetricsUpsert {
	u.SetExcluded(agentsessionmetrics.FieldTokensCached)
	return u
}

// AddTokensCached adds v to the "tokens_cached" field.
func (u *AgentSessionMetricsUpsert) AddTokensCached(v int64) *AgentSessionMetricsUpsert {
	u.Add(agentsessionmetrics.FieldTokensCached, v)
	return u
}

// ClearTokensCached clears the value of the "tokens_cached" field.
func (u *AgentSessionMetricsUpsert) ClearTokensCached() *AgentSessionMetricsUpsert {
	u.SetNull(agentsessionmetrics.FieldTokensCached)
	return u
}

// SetTokensReasoning sets the "tokens_reasoning" field.
func (u *AgentSessionMetricsUpsert) SetTokensReasoning(v int64) *AgentSessionMetricsUpsert {
	u.Set(agentsessionmetrics.FieldTokensReasoning, v)
	return u
}

// UpdateTokensReasoning sets the "tokens_reasoning" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsert) UpdateTokensReasoning() *AgentSessionMetricsUpsert {
	u.SetExcluded(agentsessionmetrics.FieldTokensReasoning)
	return u
}

// AddTokensReasoning adds v to the "tokens_reasoning" field.
func (u *AgentSessionMetricsUpsert) AddTokensReasoning(v int64) *AgentSessionMetricsUpsert {
	u.Add(agentsessionmetrics.FieldTokensReasoning, v)
	return u
}

// ClearTokensReasoning clears the value of the "tokens_reasoning" field.
func (u *AgentSessionMetricsUpsert) ClearTokensReasoning() *AgentSessionMetricsUpsert {
	u.SetNull(agentsessionmetrics.FieldTokensReasoning)
	return u
}

// SetToolCalls sets the "tool_calls" field.
func (u *AgentSessionMetricsUpsert) SetToolCalls(v map[string]interface{}) *AgentSessionMetricsUpsert {
	u.Set(agentsessionmetrics.FieldToolCalls, v)
	return u
}

// UpdateToolCalls sets the "tool_calls" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsert) UpdateToolCalls() *AgentSessionMetricsUpsert {
	u.SetExcluded(agentsessionmetrics.FieldToolCalls)
	return u
}

// ClearToolCalls clears the value of the "tool_calls" field.
func (u *AgentSessionMetricsUpsert) ClearToolCalls() *AgentSessionMetricsUpsert {
	u.SetNull(agentsessionmetrics.FieldToolCalls)
	return u
}

// SetLanguages sets the "languages" field.
func (u *AgentSessionMetricsUpsert) SetLanguages(v []string) *AgentSessionMetricsUpsert {
	u.Set(agentsessionmetrics.FieldLanguages, v)
	return u
}

// UpdateLanguages sets the "languages" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsert) UpdateLanguages() *AgentSessionMetricsUpsert {
	u.SetExcluded(agentsessionmetrics.FieldLanguages)
	return u
}

// ClearLanguages clears the value of the "languages" field.
func (u *AgentSessionMetricsUpsert) ClearLanguages() *AgentSessionMetricsUpsert {
	u.SetNull(agentsessionmetrics.FieldLanguages)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AgentSessionMetrics.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(agentsessionmetrics.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AgentSessionMetricsUpsertOne) UpdateNewValues() *AgentSessionMetricsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(agentsessionmetrics.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(agentsessionmetrics.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AgentSessionMetrics.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AgentSessionMetricsUpsertOne) Ignore() *AgentSessionMetricsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AgentSessionMetricsUpsertOne) DoNothing() *AgentSessionMetricsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AgentSessionMetricsCreate.OnConflict
// documentation for more info.
func (u *AgentSessionMetricsUpsertOne) Update(set func(*AgentSessionMetricsUpsert)) *AgentSessionMetricsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AgentSessionMetricsUpsert{UpdateSet: update})
	}))
	return u
}

// SetAgentID sets the "agent_id" field.
func (u *AgentSessionMetricsUpsertOne) SetAgentID(v string) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertOne) UpdateAgentID() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateAgentID()
	})
}

// SetGroveID sets the "grove_id" field.
func (u *AgentSessionMetricsUpsertOne) SetGroveID(v string) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetGroveID(v)
	})
}

// UpdateGroveID sets the "grove_id" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertOne) UpdateGroveID() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateGroveID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *AgentSessionMetricsUpsertOne) SetSessionID(v string) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertOne) UpdateSessionID() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateSessionID()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *AgentSessionMetricsUpsertOne) SetStartedAt(v time.Time) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertOne) UpdateStartedAt() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateStartedAt()
	})
}

// SetEndedAt sets the "ended_at" field.
func (u *AgentSessionMetricsUpsertOne) SetEndedAt(v time.Time) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetEndedAt(v)
	})
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertOne) UpdateEndedAt() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateEndedAt()
	})
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *AgentSessionMetricsUpsertOne) ClearEndedAt() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearEndedAt()
	})
}

// SetStatus sets the "status" field.
func (u *AgentSessionMetricsUpsertOne) SetStatus(v string) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertOne) UpdateStatus() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *AgentSessionMetricsUpsertOne) ClearStatus() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearStatus()
	})
}

// SetTurnCount sets the "turn_count" field.
func (u *AgentSessionMetricsUpsertOne) SetTurnCount(v int) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetTurnCount(v)
	})
}

// AddTurnCount adds v to the "turn_count" field.
func (u *AgentSessionMetricsUpsertOne) AddTurnCount(v int) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.AddTurnCount(v)
	})
}

// UpdateTurnCount sets the "turn_count" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertOne) UpdateTurnCount() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateTurnCount()
	})
}

// ClearTurnCount clears the value of the "turn_count" field.
func (u *AgentSessionMetricsUpsertOne) ClearTurnCount() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearTurnCount()
	})
}

// SetModel sets the "model" field.
func (u *AgentSessionMetricsUpsertOne) SetModel(v string) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertOne) UpdateModel() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *AgentSessionMetricsUpsertOne) ClearModel() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearModel()
	})
}

// SetTokensInput sets the "tokens_input" field.
func (u *AgentSessionMetricsUpsertOne) SetTokensInput(v int64) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetTokensInput(v)
	})
}

// AddTokensInput adds v to the "tokens_input" field.
func (u *AgentSessionMetricsUpsertOne) AddTokensInput(v int64) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.AddTokensInput(v)
	})
}

// UpdateTokensInput sets the "tokens_input" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertOne) UpdateTokensInput() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateTokensInput()
	})
}

// ClearTokensInput clears the value of the "tokens_input" field.
func (u *AgentSessionMetricsUpsertOne) ClearTokensInput() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearTokensInput()
	})
}

// SetTokensOutput sets the "tokens_output" field.
func (u *AgentSessionMetricsUpsertOne) SetTokensOutput(v int64) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetTokensOutput(v)
	})
}

// AddTokensOutput adds v to the "tokens_output" field.
func (u *AgentSessionMetricsUpsertOne) AddTokensOutput(v int64) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.AddTokensOutput(v)
	})
}

// UpdateTokensOutput sets the "tokens_output" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertOne) UpdateTokensOutput() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateTokensOutput()
	})
}

// ClearTokensOutput clears the value of the "tokens_output" field.
func (u *AgentSessionMetricsUpsertOne) ClearTokensOutput() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearTokensOutput()
	})
}

// SetTokensCached sets the "tokens_cached" field.
func (u *AgentSessionMetricsUpsertOne) SetTokensCached(v int64) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetTokensCached(v)
	})
}

// AddTokensCached adds v to the "tokens_cached" field.
func (u *AgentSessionMetricsUpsertOne) AddTokensCached(v int64) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.AddTokensCached(v)
	})
}

// UpdateTokensCached sets the "tokens_cached" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertOne) UpdateTokensCached() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateTokensCached()
	})
}

// ClearTokensCached clears the value of the "tokens_cached" field.
func (u *AgentSessionMetricsUpsertOne) ClearTokensCached() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearTokensCached()
	})
}

// SetTokensReasoning sets the "tokens_reasoning" field.
func (u *AgentSessionMetricsUpsertOne) SetTokensReasoning(v int64) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetTokensReasoning(v)
	})
}

// AddTokensReasoning adds v to the "tokens_reasoning" field.
func (u *AgentSessionMetricsUpsertOne) AddTokensReasoning(v int64) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.AddTokensReasoning(v)
	})
}

// UpdateTokensReasoning sets the "tokens_reasoning" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertOne) UpdateTokensReasoning() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateTokensReasoning()
	})
}

// ClearTokensReasoning clears the value of the "tokens_reasoning" field.
func (u *AgentSessionMetricsUpsertOne) ClearTokensReasoning() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearTokensReasoning()
	})
}

// SetToolCalls sets the "tool_calls" field.
func (u *AgentSessionMetricsUpsertOne) SetToolCalls(v map[string]interface{}) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetToolCalls(v)
	})
}

// UpdateToolCalls sets the "tool_calls" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertOne) UpdateToolCalls() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateToolCalls()
	})
}

// ClearToolCalls clears the value of the "tool_calls" field.
func (u *AgentSessionMetricsUpsertOne) ClearToolCalls() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearToolCalls()
	})
}

// SetLanguages sets the "languages" field.
func (u *AgentSessionMetricsUpsertOne) SetLanguages(v []string) *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetLanguages(v)
	})
}

// UpdateLanguages sets the "languages" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertOne) UpdateLanguages() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateLanguages()
	})
}

// ClearLanguages clears the value of the "languages" field.
func (u *AgentSessionMetricsUpsertOne) ClearLanguages() *AgentSessionMetricsUpsertOne {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearLanguages()
	})
}

// Exec executes the query.
func (u *AgentSessionMetricsUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AgentSessionMetricsCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AgentSessionMetricsUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AgentSessionMetricsUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AgentSessionMetricsUpsertOne.ID is not supported by MySQL driver. Use AgentSessionMetricsUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AgentSessionMetricsUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AgentSessionMetricsCreateBulk is the builder for creating many AgentSessionMetrics entities in bulk.
type AgentSessionMetricsCreateBulk struct {
	config
	err      error
	builders []*AgentSessionMetricsCreate
	conflict []sql.ConflictOption
}

// Save creates the AgentSessionMetrics entities in the database.
func (_c *AgentSessionMetricsCreateBulk) Save(ctx context.Context) ([]*AgentSessionMetrics, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentSessionMetrics, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentSessionMetricsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentSessionMetricsCreateBulk) SaveX(ctx context.Context) []*AgentSessionMetrics {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentSessionMetricsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentSessionMetricsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AgentSessionMetrics.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AgentSessionMetricsUpsert) {
//			SetAgentID(v+v).
//		}).
//		Exec(ctx)
func (_c *AgentSessionMetricsCreateBulk) OnConflict(opts ...sql.ConflictOption) *AgentSessionMetricsUpsertBulk {
	_c.conflict = opts
	return &AgentSessionMetricsUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AgentSessionMetrics.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AgentSessionMetricsCreateBulk) OnConflictColumns(columns ...string) *AgentSessionMetricsUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AgentSessionMetricsUpsertBulk{
		create: _c,
	}
}

// AgentSessionMetricsUpsertBulk is the builder for "upsert"-ing
// a bulk of AgentSessionMetrics nodes.
type AgentSessionMetricsUpsertBulk struct {
	create *AgentSessionMetricsCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AgentSessionMetrics.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(agentsessionmetrics.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AgentSessionMetricsUpsertBulk) UpdateNewValues() *AgentSessionMetricsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(agentsessionmetrics.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(agentsessionmetrics.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AgentSessionMetrics.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AgentSessionMetricsUpsertBulk) Ignore() *AgentSessionMetricsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AgentSessionMetricsUpsertBulk) DoNothing() *AgentSessionMetricsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AgentSessionMetricsCreateBulk.OnConflict
// documentation for more info.
func (u *AgentSessionMetricsUpsertBulk) Update(set func(*AgentSessionMetricsUpsert)) *AgentSessionMetricsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AgentSessionMetricsUpsert{UpdateSet: update})
	}))
	return u
}

// SetAgentID sets the "agent_id" field.
func (u *AgentSessionMetricsUpsertBulk) SetAgentID(v string) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertBulk) UpdateAgentID() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateAgentID()
	})
}

// SetGroveID sets the "grove_id" field.
func (u *AgentSessionMetricsUpsertBulk) SetGroveID(v string) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetGroveID(v)
	})
}

// UpdateGroveID sets the "grove_id" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertBulk) UpdateGroveID() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateGroveID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *AgentSessionMetricsUpsertBulk) SetSessionID(v string) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertBulk) UpdateSessionID() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateSessionID()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *AgentSessionMetricsUpsertBulk) SetStartedAt(v time.Time) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertBulk) UpdateStartedAt() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateStartedAt()
	})
}

// SetEndedAt sets the "ended_at" field.
func (u *AgentSessionMetricsUpsertBulk) SetEndedAt(v time.Time) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetEndedAt(v)
	})
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertBulk) UpdateEndedAt() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateEndedAt()
	})
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *AgentSessionMetricsUpsertBulk) ClearEndedAt() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearEndedAt()
	})
}

// SetStatus sets the "status" field.
func (u *AgentSessionMetricsUpsertBulk) SetStatus(v string) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertBulk) UpdateStatus() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *AgentSessionMetricsUpsertBulk) ClearStatus() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearStatus()
	})
}

// SetTurnCount sets the "turn_count" field.
func (u *AgentSessionMetricsUpsertBulk) SetTurnCount(v int) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetTurnCount(v)
	})
}

// AddTurnCount adds v to the "turn_count" field.
func (u *AgentSessionMetricsUpsertBulk) AddTurnCount(v int) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.AddTurnCount(v)
	})
}

// UpdateTurnCount sets the "turn_count" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertBulk) UpdateTurnCount() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateTurnCount()
	})
}

// ClearTurnCount clears the value of the "turn_count" field.
func (u *AgentSessionMetricsUpsertBulk) ClearTurnCount() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearTurnCount()
	})
}

// SetModel sets the "model" field.
func (u *AgentSessionMetricsUpsertBulk) SetModel(v string) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertBulk) UpdateModel() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *AgentSessionMetricsUpsertBulk) ClearModel() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearModel()
	})
}

// SetTokensInput sets the "tokens_input" field.
func (u *AgentSessionMetricsUpsertBulk) SetTokensInput(v int64) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetTokensInput(v)
	})
}

// AddTokensInput adds v to the "tokens_input" field.
func (u *AgentSessionMetricsUpsertBulk) AddTokensInput(v int64) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.AddTokensInput(v)
	})
}

// UpdateTokensInput sets the "tokens_input" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertBulk) UpdateTokensInput() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateTokensInput()
	})
}

// ClearTokensInput clears the value of the "tokens_input" field.
func (u *AgentSessionMetricsUpsertBulk) ClearTokensInput() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearTokensInput()
	})
}

// SetTokensOutput sets the "tokens_output" field.
func (u *AgentSessionMetricsUpsertBulk) SetTokensOutput(v int64) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetTokensOutput(v)
	})
}

// AddTokensOutput adds v to the "tokens_output" field.
func (u *AgentSessionMetricsUpsertBulk) AddTokensOutput(v int64) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.AddTokensOutput(v)
	})
}

// UpdateTokensOutput sets the "tokens_output" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertBulk) UpdateTokensOutput() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateTokensOutput()
	})
}

// ClearTokensOutput clears the value of the "tokens_output" field.
func (u *AgentSessionMetricsUpsertBulk) ClearTokensOutput() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearTokensOutput()
	})
}

// SetTokensCached sets the "tokens_cached" field.
func (u *AgentSessionMetricsUpsertBulk) SetTokensCached(v int64) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetTokensCached(v)
	})
}

// AddTokensCached adds v to the "tokens_cached" field.
func (u *AgentSessionMetricsUpsertBulk) AddTokensCached(v int64) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.AddTokensCached(v)
	})
}

// UpdateTokensCached sets the "tokens_cached" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertBulk) UpdateTokensCached() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateTokensCached()
	})
}

// ClearTokensCached clears the value of the "tokens_cached" field.
func (u *AgentSessionMetricsUpsertBulk) ClearTokensCached() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearTokensCached()
	})
}

// SetTokensReasoning sets the "tokens_reasoning" field.
func (u *AgentSessionMetricsUpsertBulk) SetTokensReasoning(v int64) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetTokensReasoning(v)
	})
}

// AddTokensReasoning adds v to the "tokens_reasoning" field.
func (u *AgentSessionMetricsUpsertBulk) AddTokensReasoning(v int64) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.AddTokensReasoning(v)
	})
}

// UpdateTokensReasoning sets the "tokens_reasoning" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertBulk) UpdateTokensReasoning() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateTokensReasoning()
	})
}

// ClearTokensReasoning clears the value of the "tokens_reasoning" field.
func (u *AgentSessionMetricsUpsertBulk) ClearTokensReasoning() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearTokensReasoning()
	})
}

// SetToolCalls sets the "tool_calls" field.
func (u *AgentSessionMetricsUpsertBulk) SetToolCalls(v map[string]interface{}) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetToolCalls(v)
	})
}

// UpdateToolCalls sets the "tool_calls" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertBulk) UpdateToolCalls() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateToolCalls()
	})
}

// ClearToolCalls clears the value of the "tool_calls" field.
func (u *AgentSessionMetricsUpsertBulk) ClearToolCalls() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearToolCalls()
	})
}

// SetLanguages sets the "languages" field.
func (u *AgentSessionMetricsUpsertBulk) SetLanguages(v []string) *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.SetLanguages(v)
	})
}

// UpdateLanguages sets the "languages" field to the value that was provided on create.
func (u *AgentSessionMetricsUpsertBulk) UpdateLanguages() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.UpdateLanguages()
	})
}

// ClearLanguages clears the value of the "languages" field.
func (u *AgentSessionMetricsUpsertBulk) ClearLanguages() *AgentSessionMetricsUpsertBulk {
	return u.Update(func(s *AgentSessionMetricsUpsert) {
		s.ClearLanguages()
	})
}

// Exec executes the query.
func (u *AgentSessionMetricsUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AgentSessionMetricsCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AgentSessionMetricsCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AgentSessionMetricsUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
