// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/chatlinkcode"
	"github.com/google/uuid"
)

// ChatLinkCodeCreate is the builder for creating a ChatLinkCode entity.
type ChatLinkCodeCreate struct {
	config
	mutation *ChatLinkCodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCodeHash sets the "code_hash" field.
func (_c *ChatLinkCodeCreate) SetCodeHash(v string) *ChatLinkCodeCreate {
	_c.mutation.SetCodeHash(v)
	return _c
}

// SetUserIdentifier sets the "user_identifier" field.
func (_c *ChatLinkCodeCreate) SetUserIdentifier(v string) *ChatLinkCodeCreate {
	_c.mutation.SetUserIdentifier(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *ChatLinkCodeCreate) SetProvider(v chatlinkcode.Provider) *ChatLinkCodeCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ChatLinkCodeCreate) SetStatus(v chatlinkcode.Status) *ChatLinkCodeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ChatLinkCodeCreate) SetNillableStatus(v *chatlinkcode.Status) *ChatLinkCodeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ChatLinkCodeCreate) SetUserID(v string) *ChatLinkCodeCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *ChatLinkCodeCreate) SetNillableUserID(v *string) *ChatLinkCodeCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUserEmail sets the "user_email" field.
func (_c *ChatLinkCodeCreate) SetUserEmail(v string) *ChatLinkCodeCreate {
	_c.mutation.SetUserEmail(v)
	return _c
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_c *ChatLinkCodeCreate) SetNillableUserEmail(v *string) *ChatLinkCodeCreate {
	if v != nil {
		_c.SetUserEmail(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ChatLinkCodeCreate) SetExpiresAt(v time.Time) *ChatLinkCodeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatLinkCodeCreate) SetCreatedAt(v time.Time) *ChatLinkCodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatLinkCodeCreate) SetNillableCreatedAt(v *time.Time) *ChatLinkCodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChatLinkCodeCreate) SetID(v uuid.UUID) *ChatLinkCodeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChatLinkCodeCreate) SetNillableID(v *uuid.UUID) *ChatLinkCodeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ChatLinkCodeMutation object of the builder.
func (_c *ChatLinkCodeCreate) Mutation() *ChatLinkCodeMutation {
	return _c.mutation
}

// Save creates the ChatLinkCode in the database.
func (_c *ChatLinkCodeCreate) Save(ctx context.Context) (*ChatLinkCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatLinkCodeCreate) SaveX(ctx context.Context) *ChatLinkCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatLinkCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatLinkCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatLinkCodeCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := chatlinkcode.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chatlinkcode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := chatlinkcode.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatLinkCodeCreate) check() error {
	if _, ok := _c.mutation.CodeHash(); !ok {
		return &ValidationError{Name: "code_hash", err: errors.New(`ent: missing required field "ChatLinkCode.code_hash"`)}
	}
	if v, ok := _c.mutation.CodeHash(); ok {
		if err := chatlinkcode.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "ChatLinkCode.code_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserIdentifier(); !ok {
		return &ValidationError{Name: "user_identifier", err: errors.New(`ent: missing required field "ChatLinkCode.user_identifier"`)}
	}
	if v, ok := _c.mutation.UserIdentifier(); ok {
		if err := chatlinkcode.UserIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "user_identifier", err: fmt.Errorf(`ent: validator failed for field "ChatLinkCode.user_identifier": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "ChatLinkCode.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := chatlinkcode.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ChatLinkCode.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ChatLinkCode.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := chatlinkcode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChatLinkCode.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "ChatLinkCode.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatLinkCode.created_at"`)}
	}
	return nil
}

func (_c *ChatLinkCodeCreate) sqlSave(ctx context.Context) (*ChatLinkCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatLinkCodeCreate) createSpec() (*ChatLinkCode, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatLinkCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatlinkcode.Table, sqlgraph.NewFieldSpec(chatlinkcode.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CodeHash(); ok {
		_spec.SetField(chatlinkcode.FieldCodeHash, field.TypeString, value)
		_node.CodeHash = value
	}
	if value, ok := _c.mutation.UserIdentifier(); ok {
		_spec.SetField(chatlinkcode.FieldUserIdentifier, field.TypeString, value)
		_node.UserIdentifier = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(chatlinkcode.FieldProvider, field.TypeEnum, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(chatlinkcode.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(chatlinkcode.FieldUserID, field.TypeString, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.UserEmail(); ok {
		_spec.SetField(chatlinkcode.FieldUserEmail, field.TypeString, value)
		_node.UserEmail = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(chatlinkcode.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatlinkcode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatLinkCode.Create().
//		SetCodeHash(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatLinkCodeUpsert) {
//			SetCodeHash(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatLinkCodeCreate) OnConflict(opts ...sql.ConflictOption) *ChatLinkCodeUpsertOne {
	_c.conflict = opts
	return &ChatLinkCodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatLinkCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatLinkCodeCreate) OnConflictColumns(columns ...string) *ChatLinkCodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatLinkCodeUpsertOne{
		create: _c,
	}
}

type (
	// ChatLinkCodeUpsertOne is the builder for "upsert"-ing
	//  one ChatLinkCode node.
	ChatLinkCodeUpsertOne struct {
		create *ChatLinkCodeCreate
	}

	// ChatLinkCodeUpsert is the "OnConflict" setter.
	ChatLinkCodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetCodeHash sets the "code_hash" field.
func (u *ChatLinkCodeUpsert) SetCodeHash(v string) *ChatLinkCodeUpsert {
	u.Set(chatlinkcode.FieldCodeHash, v)
	return u
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *ChatLinkCodeUpsert) UpdateCodeHash() *ChatLinkCodeUpsert {
	u.SetExcluded(chatlinkcode.FieldCodeHash)
	return u
}

// SetUserIdentifier sets the "user_identifier" field.
func (u *ChatLinkCodeUpsert) SetUserIdentifier(v string) *ChatLinkCodeUpsert {
	u.Set(chatlinkcode.FieldUserIdentifier, v)
	return u
}

// UpdateUserIdentifier sets the "user_identifier" field to the value that was provided on create.
func (u *ChatLinkCodeUpsert) UpdateUserIdentifier() *ChatLinkCodeUpsert {
	u.SetExcluded(chatlinkcode.FieldUserIdentifier)
	return u
}

// SetProvider sets the "provider" field.
func (u *ChatLinkCodeUpsert) SetProvider(v chatlinkcode.Provider) *ChatLinkCodeUpsert {
	u.Set(chatlinkcode.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ChatLinkCodeUpsert) UpdateProvider() *ChatLinkCodeUpsert {
	u.SetExcluded(chatlinkcode.FieldProvider)
	return u
}

// SetStatus sets the "status" field.
func (u *ChatLinkCodeUpsert) SetStatus(v chatlinkcode.Status) *ChatLinkCodeUpsert {
	u.Set(chatlinkcode.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChatLinkCodeUpsert) UpdateStatus() *ChatLinkCodeUpsert {
	u.SetExcluded(chatlinkcode.FieldStatus)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ChatLinkCodeUpsert) SetUserID(v string) *ChatLinkCodeUpsert {
	u.Set(chatlinkcode.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChatLinkCodeUpsert) UpdateUserID() *ChatLinkCodeUpsert {
	u.SetExcluded(chatlinkcode.FieldUserID)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *ChatLinkCodeUpsert) ClearUserID() *ChatLinkCodeUpsert {
	u.SetNull(chatlinkcode.FieldUserID)
	return u
}

// SetUserEmail sets the "user_email" field.
func (u *ChatLinkCodeUpsert) SetUserEmail(v string) *ChatLinkCodeUpsert {
	u.Set(chatlinkcode.FieldUserEmail, v)
	return u
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *ChatLinkCodeUpsert) UpdateUserEmail() *ChatLinkCodeUpsert {
	u.SetExcluded(chatlinkcode.FieldUserEmail)
	return u
}

// ClearUserEmail clears the value of the "user_email" field.
func (u *ChatLinkCodeUpsert) ClearUserEmail() *ChatLinkCodeUpsert {
	u.SetNull(chatlinkcode.FieldUserEmail)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *ChatLinkCodeUpsert) SetExpiresAt(v time.Time) *ChatLinkCodeUpsert {
	u.Set(chatlinkcode.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ChatLinkCodeUpsert) UpdateExpiresAt() *ChatLinkCodeUpsert {
	u.SetExcluded(chatlinkcode.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ChatLinkCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(chatlinkcode.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ChatLinkCodeUpsertOne) UpdateNewValues() *ChatLinkCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(chatlinkcode.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(chatlinkcode.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatLinkCode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChatLinkCodeUpsertOne) Ignore() *ChatLinkCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatLinkCodeUpsertOne) DoNothing() *ChatLinkCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatLinkCodeCreate.OnConflict
// documentation for more info.
func (u *ChatLinkCodeUpsertOne) Update(set func(*ChatLinkCodeUpsert)) *ChatLinkCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatLinkCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetCodeHash sets the "code_hash" field.
func (u *ChatLinkCodeUpsertOne) SetCodeHash(v string) *ChatLinkCodeUpsertOne {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.SetCodeHash(v)
	})
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *ChatLinkCodeUpsertOne) UpdateCodeHash() *ChatLinkCodeUpsertOne {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.UpdateCodeHash()
	})
}

// SetUserIdentifier sets the "user_identifier" field.
func (u *ChatLinkCodeUpsertOne) SetUserIdentifier(v string) *ChatLinkCodeUpsertOne {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.SetUserIdentifier(v)
	})
}

// UpdateUserIdentifier sets the "user_identifier" field to the value that was provided on create.
func (u *ChatLinkCodeUpsertOne) UpdateUserIdentifier() *ChatLinkCodeUpsertOne {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.UpdateUserIdentifier()
	})
}

// SetProvider sets the "provider" field.
func (u *ChatLinkCodeUpsertOne) SetProvider(v chatlinkcode.Provider) *ChatLinkCodeUpsertOne {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ChatLinkCodeUpsertOne) UpdateProvider() *ChatLinkCodeUpsertOne {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.UpdateProvider()
	})
}

// SetStatus sets the "status" field.
func (u *ChatLinkCodeUpsertOne) SetStatus(v chatlinkcode.Status) *ChatLinkCodeUpsertOne {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChatLinkCodeUpsertOne) UpdateStatus() *ChatLinkCodeUpsertOne {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.UpdateStatus()
	})
}

// SetUserID sets the "user_id" field.
func (u *ChatLinkCodeUpsertOne) SetUserID(v string) *ChatLinkCodeUpsertOne {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChatLinkCodeUpsertOne) UpdateUserID() *ChatLinkCodeUpsertOne {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *ChatLinkCodeUpsertOne) ClearUserID() *ChatLinkCodeUpsertOne {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.ClearUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *ChatLinkCodeUpsertOne) SetUserEmail(v string) *ChatLinkCodeUpsertOne {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *ChatLinkCodeUpsertOne) UpdateUserEmail() *ChatLinkCodeUpsertOne {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.UpdateUserEmail()
	})
}

// ClearUserEmail clears the value of the "user_email" field.
func (u *ChatLinkCodeUpsertOne) ClearUserEmail() *ChatLinkCodeUpsertOne {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.ClearUserEmail()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ChatLinkCodeUpsertOne) SetExpiresAt(v time.Time) *ChatLinkCodeUpsertOne {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ChatLinkCodeUpsertOne) UpdateExpiresAt() *ChatLinkCodeUpsertOne {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *ChatLinkCodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatLinkCodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatLinkCodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChatLinkCodeUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ChatLinkCodeUpsertOne.ID is not supported by MySQL driver. Use ChatLinkCodeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChatLinkCodeUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChatLinkCodeCreateBulk is the builder for creating many ChatLinkCode entities in bulk.
type ChatLinkCodeCreateBulk struct {
	config
	err      error
	builders []*ChatLinkCodeCreate
	conflict []sql.ConflictOption
}

// Save creates the ChatLinkCode entities in the database.
func (_c *ChatLinkCodeCreateBulk) Save(ctx context.Context) ([]*ChatLinkCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatLinkCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatLinkCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatLinkCodeCreateBulk) SaveX(ctx context.Context) []*ChatLinkCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatLinkCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatLinkCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatLinkCode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatLinkCodeUpsert) {
//			SetCodeHash(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatLinkCodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChatLinkCodeUpsertBulk {
	_c.conflict = opts
	return &ChatLinkCodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatLinkCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatLinkCodeCreateBulk) OnConflictColumns(columns ...string) *ChatLinkCodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatLinkCodeUpsertBulk{
		create: _c,
	}
}

// ChatLinkCodeUpsertBulk is the builder for "upsert"-ing
// a bulk of ChatLinkCode nodes.
type ChatLinkCodeUpsertBulk struct {
	create *ChatLinkCodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChatLinkCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(chatlinkcode.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ChatLinkCodeUpsertBulk) UpdateNewValues() *ChatLinkCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(chatlinkcode.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(chatlinkcode.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatLinkCode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChatLinkCodeUpsertBulk) Ignore() *ChatLinkCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatLinkCodeUpsertBulk) DoNothing() *ChatLinkCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatLinkCodeCreateBulk.OnConflict
// documentation for more info.
func (u *ChatLinkCodeUpsertBulk) Update(set func(*ChatLinkCodeUpsert)) *ChatLinkCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatLinkCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetCodeHash sets the "code_hash" field.
func (u *ChatLinkCodeUpsertBulk) SetCodeHash(v string) *ChatLinkCodeUpsertBulk {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.SetCodeHash(v)
	})
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *ChatLinkCodeUpsertBulk) UpdateCodeHash() *ChatLinkCodeUpsertBulk {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.UpdateCodeHash()
	})
}

// SetUserIdentifier sets the "user_identifier" field.
func (u *ChatLinkCodeUpsertBulk) SetUserIdentifier(v string) *ChatLinkCodeUpsertBulk {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.SetUserIdentifier(v)
	})
}

// UpdateUserIdentifier sets the "user_identifier" field to the value that was provided on create.
func (u *ChatLinkCodeUpsertBulk) UpdateUserIdentifier() *ChatLinkCodeUpsertBulk {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.UpdateUserIdentifier()
	})
}

// SetProvider sets the "provider" field.
func (u *ChatLinkCodeUpsertBulk) SetProvider(v chatlinkcode.Provider) *ChatLinkCodeUpsertBulk {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ChatLinkCodeUpsertBulk) UpdateProvider() *ChatLinkCodeUpsertBulk {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.UpdateProvider()
	})
}

// SetStatus sets the "status" field.
func (u *ChatLinkCodeUpsertBulk) SetStatus(v chatlinkcode.Status) *ChatLinkCodeUpsertBulk {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChatLinkCodeUpsertBulk) UpdateStatus() *ChatLinkCodeUpsertBulk {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.UpdateStatus()
	})
}

// SetUserID sets the "user_id" field.
func (u *ChatLinkCodeUpsertBulk) SetUserID(v string) *ChatLinkCodeUpsertBulk {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChatLinkCodeUpsertBulk) UpdateUserID() *ChatLinkCodeUpsertBulk {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *ChatLinkCodeUpsertBulk) ClearUserID() *ChatLinkCodeUpsertBulk {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.ClearUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *ChatLinkCodeUpsertBulk) SetUserEmail(v string) *ChatLinkCodeUpsertBulk {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *ChatLinkCodeUpsertBulk) UpdateUserEmail() *ChatLinkCodeUpsertBulk {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.UpdateUserEmail()
	})
}

// ClearUserEmail clears the value of the "user_email" field.
func (u *ChatLinkCodeUpsertBulk) ClearUserEmail() *ChatLinkCodeUpsertBulk {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.ClearUserEmail()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ChatLinkCodeUpsertBulk) SetExpiresAt(v time.Time) *ChatLinkCodeUpsertBulk {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ChatLinkCodeUpsertBulk) UpdateExpiresAt() *ChatLinkCodeUpsertBulk {
	return u.Update(func(s *ChatLinkCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *ChatLinkCodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChatLinkCodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatLinkCodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatLinkCodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
