// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/chatlinkcode"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/google/uuid"
)

// ChatLinkCodeQuery is the builder for querying ChatLinkCode entities.
type ChatLinkCodeQuery struct {
	config
	ctx        *QueryContext
	order      []chatlinkcode.OrderOption
	inters     []Interceptor
	predicates []predicate.ChatLinkCode
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChatLinkCodeQuery builder.
func (_q *ChatLinkCodeQuery) Where(ps ...predicate.ChatLinkCode) *ChatLinkCodeQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChatLinkCodeQuery) Limit(limit int) *ChatLinkCodeQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChatLinkCodeQuery) Offset(offset int) *ChatLinkCodeQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChatLinkCodeQuery) Unique(unique bool) *ChatLinkCodeQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChatLinkCodeQuery) Order(o ...chatlinkcode.OrderOption) *ChatLinkCodeQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// First returns the first ChatLinkCode entity from the query.
// Returns a *NotFoundError when no ChatLinkCode was found.
func (_q *ChatLinkCodeQuery) First(ctx context.Context) (*ChatLinkCode, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chatlinkcode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChatLinkCodeQuery) FirstX(ctx context.Context) *ChatLinkCode {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChatLinkCode ID from the query.
// Returns a *NotFoundError when no ChatLinkCode ID was found.
func (_q *ChatLinkCodeQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{chatlinkcode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ChatLinkCodeQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChatLinkCode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChatLinkCode entity is found.
// Returns a *NotFoundError when no ChatLinkCode entities are found.
func (_q *ChatLinkCodeQuery) Only(ctx context.Context) (*ChatLinkCode, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chatlinkcode.Label}
	default:
		return nil, &NotSingularError{chatlinkcode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChatLinkCodeQuery) OnlyX(ctx context.Context) *ChatLinkCode {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChatLinkCode ID in the query.
// Returns a *NotSingularError when more than one ChatLinkCode ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ChatLinkCodeQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{chatlinkcode.Label}
	default:
		err = &NotSingularError{chatlinkcode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ChatLinkCodeQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChatLinkCodes.
func (_q *ChatLinkCodeQuery) All(ctx context.Context) ([]*ChatLinkCode, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChatLinkCode, *ChatLinkCodeQuery]()
	return withInterceptors[[]*ChatLinkCode](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChatLinkCodeQuery) AllX(ctx context.Context) []*ChatLinkCode {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChatLinkCode IDs.
func (_q *ChatLinkCodeQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(chatlinkcode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ChatLinkCodeQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ChatLinkCodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChatLinkCodeQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChatLinkCodeQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChatLinkCodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChatLinkCodeQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChatLinkCodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChatLinkCodeQuery) Clone() *ChatLinkCodeQuery {
	if _q == nil {
		return nil
	}
	return &ChatLinkCodeQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]chatlinkcode.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.ChatLinkCode{}, _q.predicates...),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CodeHash string `json:"code_hash,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChatLinkCode.Query().
//		GroupBy(chatlinkcode.FieldCodeHash).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ChatLinkCodeQuery) GroupBy(field string, fields ...string) *ChatLinkCodeGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChatLinkCodeGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = chatlinkcode.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CodeHash string `json:"code_hash,omitempty"`
//	}
//
//	client.ChatLinkCode.Query().
//		Select(chatlinkcode.FieldCodeHash).
//		Scan(ctx, &v)
func (_q *ChatLinkCodeQuery) Select(fields ...string) *ChatLinkCodeSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChatLinkCodeSelect{ChatLinkCodeQuery: _q}
	sbuild.label = chatlinkcode.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChatLinkCodeSelect configured with the given aggregations.
func (_q *ChatLinkCodeQuery) Aggregate(fns ...AggregateFunc) *ChatLinkCodeSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChatLinkCodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !chatlinkcode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ChatLinkCodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChatLinkCode, error) {
	var (
		nodes = []*ChatLinkCode{}
		_spec = _q.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChatLinkCode).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChatLinkCode{config: _q.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (_q *ChatLinkCodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChatLinkCodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(chatlinkcode.Table, chatlinkcode.Columns, sqlgraph.NewFieldSpec(chatlinkcode.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatlinkcode.FieldID)
		for i := range fields {
			if fields[i] != chatlinkcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChatLinkCodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(chatlinkcode.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = chatlinkcode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *ChatLinkCodeQuery) ForUpdate(opts ...sql.LockOption) *ChatLinkCodeQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *ChatLinkCodeQuery) ForShare(opts ...sql.LockOption) *ChatLinkCodeQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// ChatLinkCodeGroupBy is the group-by builder for ChatLinkCode entities.
type ChatLinkCodeGroupBy struct {
	selector
	build *ChatLinkCodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChatLinkCodeGroupBy) Aggregate(fns ...AggregateFunc) *ChatLinkCodeGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChatLinkCodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatLinkCodeQuery, *ChatLinkCodeGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChatLinkCodeGroupBy) sqlScan(ctx context.Context, root *ChatLinkCodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChatLinkCodeSelect is the builder for selecting fields of ChatLinkCode entities.
type ChatLinkCodeSelect struct {
	*ChatLinkCodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChatLinkCodeSelect) Aggregate(fns ...AggregateFunc) *ChatLinkCodeSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChatLinkCodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatLinkCodeQuery, *ChatLinkCodeSelect](ctx, _s.ChatLinkCodeQuery, _s, _s.inters, v)
}

func (_s *ChatLinkCodeSelect) sqlScan(ctx context.Context, root *ChatLinkCodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
