// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/entitlementbinding"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/limitdefinition"
	"github.com/google/uuid"
)

// EntitlementBinding is the model entity for the EntitlementBinding schema.
type EntitlementBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// FK to LimitDefinition
	LimitDefinitionID uuid.UUID `json:"limit_definition_id,omitempty"`
	// SubjectType holds the value of the "subject_type" field.
	SubjectType entitlementbinding.SubjectType `json:"subject_type,omitempty"`
	// SubjectID holds the value of the "subject_id" field.
	SubjectID string `json:"subject_id,omitempty"`
	// ScopeType holds the value of the "scope_type" field.
	ScopeType entitlementbinding.ScopeType `json:"scope_type,omitempty"`
	// ScopeID holds the value of the "scope_id" field.
	ScopeID string `json:"scope_id,omitempty"`
	// Value holds the value of the "value" field.
	Value int64 `json:"value,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EntitlementBindingQuery when eager-loading is set.
	Edges        EntitlementBindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EntitlementBindingEdges holds the relations/edges for other nodes in the graph.
type EntitlementBindingEdges struct {
	// LimitDefinition holds the value of the limit_definition edge.
	LimitDefinition *LimitDefinition `json:"limit_definition,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// LimitDefinitionOrErr returns the LimitDefinition value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntitlementBindingEdges) LimitDefinitionOrErr() (*LimitDefinition, error) {
	if e.LimitDefinition != nil {
		return e.LimitDefinition, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: limitdefinition.Label}
	}
	return nil, &NotLoadedError{edge: "limit_definition"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EntitlementBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case entitlementbinding.FieldValue:
			values[i] = new(sql.NullInt64)
		case entitlementbinding.FieldSubjectType, entitlementbinding.FieldSubjectID, entitlementbinding.FieldScopeType, entitlementbinding.FieldScopeID, entitlementbinding.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case entitlementbinding.FieldCreatedAt, entitlementbinding.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case entitlementbinding.FieldID, entitlementbinding.FieldLimitDefinitionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EntitlementBinding fields.
func (_m *EntitlementBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entitlementbinding.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case entitlementbinding.FieldLimitDefinitionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field limit_definition_id", values[i])
			} else if value != nil {
				_m.LimitDefinitionID = *value
			}
		case entitlementbinding.FieldSubjectType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject_type", values[i])
			} else if value.Valid {
				_m.SubjectType = entitlementbinding.SubjectType(value.String)
			}
		case entitlementbinding.FieldSubjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject_id", values[i])
			} else if value.Valid {
				_m.SubjectID = value.String
			}
		case entitlementbinding.FieldScopeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_type", values[i])
			} else if value.Valid {
				_m.ScopeType = entitlementbinding.ScopeType(value.String)
			}
		case entitlementbinding.FieldScopeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_id", values[i])
			} else if value.Valid {
				_m.ScopeID = value.String
			}
		case entitlementbinding.FieldValue:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.Int64
			}
		case entitlementbinding.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case entitlementbinding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case entitlementbinding.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the EntitlementBinding.
// This includes values selected through modifiers, order, etc.
func (_m *EntitlementBinding) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLimitDefinition queries the "limit_definition" edge of the EntitlementBinding entity.
func (_m *EntitlementBinding) QueryLimitDefinition() *LimitDefinitionQuery {
	return NewEntitlementBindingClient(_m.config).QueryLimitDefinition(_m)
}

// Update returns a builder for updating this EntitlementBinding.
// Note that you need to call EntitlementBinding.Unwrap() before calling this method if this EntitlementBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EntitlementBinding) Update() *EntitlementBindingUpdateOne {
	return NewEntitlementBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EntitlementBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EntitlementBinding) Unwrap() *EntitlementBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EntitlementBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EntitlementBinding) String() string {
	var builder strings.Builder
	builder.WriteString("EntitlementBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("limit_definition_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LimitDefinitionID))
	builder.WriteString(", ")
	builder.WriteString("subject_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubjectType))
	builder.WriteString(", ")
	builder.WriteString("subject_id=")
	builder.WriteString(_m.SubjectID)
	builder.WriteString(", ")
	builder.WriteString("scope_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScopeType))
	builder.WriteString(", ")
	builder.WriteString("scope_id=")
	builder.WriteString(_m.ScopeID)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(fmt.Sprintf("%v", _m.Value))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EntitlementBindings is a parsable slice of EntitlementBinding.
type EntitlementBindings []*EntitlementBinding
