// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/entitlementbinding"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/limitdefinition"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/google/uuid"
)

// EntitlementBindingUpdate is the builder for updating EntitlementBinding entities.
type EntitlementBindingUpdate struct {
	config
	hooks    []Hook
	mutation *EntitlementBindingMutation
}

// Where appends a list predicates to the EntitlementBindingUpdate builder.
func (_u *EntitlementBindingUpdate) Where(ps ...predicate.EntitlementBinding) *EntitlementBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLimitDefinitionID sets the "limit_definition_id" field.
func (_u *EntitlementBindingUpdate) SetLimitDefinitionID(v uuid.UUID) *EntitlementBindingUpdate {
	_u.mutation.SetLimitDefinitionID(v)
	return _u
}

// SetNillableLimitDefinitionID sets the "limit_definition_id" field if the given value is not nil.
func (_u *EntitlementBindingUpdate) SetNillableLimitDefinitionID(v *uuid.UUID) *EntitlementBindingUpdate {
	if v != nil {
		_u.SetLimitDefinitionID(*v)
	}
	return _u
}

// SetSubjectType sets the "subject_type" field.
func (_u *EntitlementBindingUpdate) SetSubjectType(v entitlementbinding.SubjectType) *EntitlementBindingUpdate {
	_u.mutation.SetSubjectType(v)
	return _u
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (_u *EntitlementBindingUpdate) SetNillableSubjectType(v *entitlementbinding.SubjectType) *EntitlementBindingUpdate {
	if v != nil {
		_u.SetSubjectType(*v)
	}
	return _u
}

// SetSubjectID sets the "subject_id" field.
func (_u *EntitlementBindingUpdate) SetSubjectID(v string) *EntitlementBindingUpdate {
	_u.mutation.SetSubjectID(v)
	return _u
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (_u *EntitlementBindingUpdate) SetNillableSubjectID(v *string) *EntitlementBindingUpdate {
	if v != nil {
		_u.SetSubjectID(*v)
	}
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *EntitlementBindingUpdate) SetScopeType(v entitlementbinding.ScopeType) *EntitlementBindingUpdate {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *EntitlementBindingUpdate) SetNillableScopeType(v *entitlementbinding.ScopeType) *EntitlementBindingUpdate {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *EntitlementBindingUpdate) SetScopeID(v string) *EntitlementBindingUpdate {
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *EntitlementBindingUpdate) SetNillableScopeID(v *string) *EntitlementBindingUpdate {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *EntitlementBindingUpdate) SetValue(v int64) *EntitlementBindingUpdate {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *EntitlementBindingUpdate) SetNillableValue(v *int64) *EntitlementBindingUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *EntitlementBindingUpdate) AddValue(v int64) *EntitlementBindingUpdate {
	_u.mutation.AddValue(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntitlementBindingUpdate) SetUpdatedAt(v time.Time) *EntitlementBindingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLimitDefinition sets the "limit_definition" edge to the LimitDefinition entity.
func (_u *EntitlementBindingUpdate) SetLimitDefinition(v *LimitDefinition) *EntitlementBindingUpdate {
	return _u.SetLimitDefinitionID(v.ID)
}

// Mutation returns the EntitlementBindingMutation object of the builder.
func (_u *EntitlementBindingUpdate) Mutation() *EntitlementBindingMutation {
	return _u.mutation
}

// ClearLimitDefinition clears the "limit_definition" edge to the LimitDefinition entity.
func (_u *EntitlementBindingUpdate) ClearLimitDefinition() *EntitlementBindingUpdate {
	_u.mutation.ClearLimitDefinition()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EntitlementBindingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntitlementBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EntitlementBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntitlementBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntitlementBindingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entitlementbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntitlementBindingUpdate) check() error {
	if v, ok := _u.mutation.SubjectType(); ok {
		if err := entitlementbinding.SubjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "subject_type", err: fmt.Errorf(`ent: validator failed for field "EntitlementBinding.subject_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := entitlementbinding.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "EntitlementBinding.scope_type": %w`, err)}
		}
	}
	if _u.mutation.LimitDefinitionCleared() && len(_u.mutation.LimitDefinitionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntitlementBinding.limit_definition"`)
	}
	return nil
}

func (_u *EntitlementBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entitlementbinding.Table, entitlementbinding.Columns, sqlgraph.NewFieldSpec(entitlementbinding.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubjectType(); ok {
		_spec.SetField(entitlementbinding.FieldSubjectType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SubjectID(); ok {
		_spec.SetField(entitlementbinding.FieldSubjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(entitlementbinding.FieldScopeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(entitlementbinding.FieldScopeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(entitlementbinding.FieldValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(entitlementbinding.FieldValue, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(entitlementbinding.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entitlementbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LimitDefinitionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementbinding.LimitDefinitionTable,
			Columns: []string{entitlementbinding.LimitDefinitionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(limitdefinition.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LimitDefinitionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementbinding.LimitDefinitionTable,
			Columns: []string{entitlementbinding.LimitDefinitionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(limitdefinition.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitlementbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EntitlementBindingUpdateOne is the builder for updating a single EntitlementBinding entity.
type EntitlementBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntitlementBindingMutation
}

// SetLimitDefinitionID sets the "limit_definition_id" field.
func (_u *EntitlementBindingUpdateOne) SetLimitDefinitionID(v uuid.UUID) *EntitlementBindingUpdateOne {
	_u.mutation.SetLimitDefinitionID(v)
	return _u
}

// SetNillableLimitDefinitionID sets the "limit_definition_id" field if the given value is not nil.
func (_u *EntitlementBindingUpdateOne) SetNillableLimitDefinitionID(v *uuid.UUID) *EntitlementBindingUpdateOne {
	if v != nil {
		_u.SetLimitDefinitionID(*v)
	}
	return _u
}

// SetSubjectType sets the "subject_type" field.
func (_u *EntitlementBindingUpdateOne) SetSubjectType(v entitlementbinding.SubjectType) *EntitlementBindingUpdateOne {
	_u.mutation.SetSubjectType(v)
	return _u
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (_u *EntitlementBindingUpdateOne) SetNillableSubjectType(v *entitlementbinding.SubjectType) *EntitlementBindingUpdateOne {
	if v != nil {
		_u.SetSubjectType(*v)
	}
	return _u
}

// SetSubjectID sets the "subject_id" field.
func (_u *EntitlementBindingUpdateOne) SetSubjectID(v string) *EntitlementBindingUpdateOne {
	_u.mutation.SetSubjectID(v)
	return _u
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (_u *EntitlementBindingUpdateOne) SetNillableSubjectID(v *string) *EntitlementBindingUpdateOne {
	if v != nil {
		_u.SetSubjectID(*v)
	}
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *EntitlementBindingUpdateOne) SetScopeType(v entitlementbinding.ScopeType) *EntitlementBindingUpdateOne {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *EntitlementBindingUpdateOne) SetNillableScopeType(v *entitlementbinding.ScopeType) *EntitlementBindingUpdateOne {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *EntitlementBindingUpdateOne) SetScopeID(v string) *EntitlementBindingUpdateOne {
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *EntitlementBindingUpdateOne) SetNillableScopeID(v *string) *EntitlementBindingUpdateOne {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *EntitlementBindingUpdateOne) SetValue(v int64) *EntitlementBindingUpdateOne {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *EntitlementBindingUpdateOne) SetNillableValue(v *int64) *EntitlementBindingUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *EntitlementBindingUpdateOne) AddValue(v int64) *EntitlementBindingUpdateOne {
	_u.mutation.AddValue(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntitlementBindingUpdateOne) SetUpdatedAt(v time.Time) *EntitlementBindingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLimitDefinition sets the "limit_definition" edge to the LimitDefinition entity.
func (_u *EntitlementBindingUpdateOne) SetLimitDefinition(v *LimitDefinition) *EntitlementBindingUpdateOne {
	return _u.SetLimitDefinitionID(v.ID)
}

// Mutation returns the EntitlementBindingMutation object of the builder.
func (_u *EntitlementBindingUpdateOne) Mutation() *EntitlementBindingMutation {
	return _u.mutation
}

// ClearLimitDefinition clears the "limit_definition" edge to the LimitDefinition entity.
func (_u *EntitlementBindingUpdateOne) ClearLimitDefinition() *EntitlementBindingUpdateOne {
	_u.mutation.ClearLimitDefinition()
	return _u
}

// Where appends a list predicates to the EntitlementBindingUpdate builder.
func (_u *EntitlementBindingUpdateOne) Where(ps ...predicate.EntitlementBinding) *EntitlementBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EntitlementBindingUpdateOne) Select(field string, fields ...string) *EntitlementBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EntitlementBinding entity.
func (_u *EntitlementBindingUpdateOne) Save(ctx context.Context) (*EntitlementBinding, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntitlementBindingUpdateOne) SaveX(ctx context.Context) *EntitlementBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EntitlementBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntitlementBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntitlementBindingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entitlementbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntitlementBindingUpdateOne) check() error {
	if v, ok := _u.mutation.SubjectType(); ok {
		if err := entitlementbinding.SubjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "subject_type", err: fmt.Errorf(`ent: validator failed for field "EntitlementBinding.subject_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := entitlementbinding.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "EntitlementBinding.scope_type": %w`, err)}
		}
	}
	if _u.mutation.LimitDefinitionCleared() && len(_u.mutation.LimitDefinitionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntitlementBinding.limit_definition"`)
	}
	return nil
}

func (_u *EntitlementBindingUpdateOne) sqlSave(ctx context.Context) (_node *EntitlementBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entitlementbinding.Table, entitlementbinding.Columns, sqlgraph.NewFieldSpec(entitlementbinding.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EntitlementBinding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entitlementbinding.FieldID)
		for _, f := range fields {
			if !entitlementbinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entitlementbinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubjectType(); ok {
		_spec.SetField(entitlementbinding.FieldSubjectType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SubjectID(); ok {
		_spec.SetField(entitlementbinding.FieldSubjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(entitlementbinding.FieldScopeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(entitlementbinding.FieldScopeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(entitlementbinding.FieldValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(entitlementbinding.FieldValue, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(entitlementbinding.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entitlementbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LimitDefinitionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementbinding.LimitDefinitionTable,
			Columns: []string{entitlementbinding.LimitDefinitionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(limitdefinition.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LimitDefinitionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementbinding.LimitDefinitionTable,
			Columns: []string{entitlementbinding.LimitDefinitionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(limitdefinition.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EntitlementBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitlementbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
