// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/entitlementbinding"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/limitdefinition"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/google/uuid"
)

// EntitlementBindingQuery is the builder for querying EntitlementBinding entities.
type EntitlementBindingQuery struct {
	config
	ctx                 *QueryContext
	order               []entitlementbinding.OrderOption
	inters              []Interceptor
	predicates          []predicate.EntitlementBinding
	withLimitDefinition *LimitDefinitionQuery
	modifiers           []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EntitlementBindingQuery builder.
func (_q *EntitlementBindingQuery) Where(ps ...predicate.EntitlementBinding) *EntitlementBindingQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *EntitlementBindingQuery) Limit(limit int) *EntitlementBindingQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *EntitlementBindingQuery) Offset(offset int) *EntitlementBindingQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *EntitlementBindingQuery) Unique(unique bool) *EntitlementBindingQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *EntitlementBindingQuery) Order(o ...entitlementbinding.OrderOption) *EntitlementBindingQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryLimitDefinition chains the current query on the "limit_definition" edge.
func (_q *EntitlementBindingQuery) QueryLimitDefinition() *LimitDefinitionQuery {
	query := (&LimitDefinitionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(entitlementbinding.Table, entitlementbinding.FieldID, selector),
			sqlgraph.To(limitdefinition.Table, limitdefinition.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, entitlementbinding.LimitDefinitionTable, entitlementbinding.LimitDefinitionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EntitlementBinding entity from the query.
// Returns a *NotFoundError when no EntitlementBinding was found.
func (_q *EntitlementBindingQuery) First(ctx context.Context) (*EntitlementBinding, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{entitlementbinding.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *EntitlementBindingQuery) FirstX(ctx context.Context) *EntitlementBinding {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EntitlementBinding ID from the query.
// Returns a *NotFoundError when no EntitlementBinding ID was found.
func (_q *EntitlementBindingQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{entitlementbinding.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *EntitlementBindingQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EntitlementBinding entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EntitlementBinding entity is found.
// Returns a *NotFoundError when no EntitlementBinding entities are found.
func (_q *EntitlementBindingQuery) Only(ctx context.Context) (*EntitlementBinding, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{entitlementbinding.Label}
	default:
		return nil, &NotSingularError{entitlementbinding.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *EntitlementBindingQuery) OnlyX(ctx context.Context) *EntitlementBinding {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EntitlementBinding ID in the query.
// Returns a *NotSingularError when more than one EntitlementBinding ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *EntitlementBindingQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{entitlementbinding.Label}
	default:
		err = &NotSingularError{entitlementbinding.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *EntitlementBindingQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EntitlementBindings.
func (_q *EntitlementBindingQuery) All(ctx context.Context) ([]*EntitlementBinding, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EntitlementBinding, *EntitlementBindingQuery]()
	return withInterceptors[[]*EntitlementBinding](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *EntitlementBindingQuery) AllX(ctx context.Context) []*EntitlementBinding {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EntitlementBinding IDs.
func (_q *EntitlementBindingQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(entitlementbinding.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *EntitlementBindingQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *EntitlementBindingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*EntitlementBindingQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *EntitlementBindingQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *EntitlementBindingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *EntitlementBindingQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EntitlementBindingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *EntitlementBindingQuery) Clone() *EntitlementBindingQuery {
	if _q == nil {
		return nil
	}
	return &EntitlementBindingQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]entitlementbinding.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.EntitlementBinding{}, _q.predicates...),
		withLimitDefinition: _q.withLimitDefinition.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithLimitDefinition tells the query-builder to eager-load the nodes that are connected to
// the "limit_definition" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EntitlementBindingQuery) WithLimitDefinition(opts ...func(*LimitDefinitionQuery)) *EntitlementBindingQuery {
	query := (&LimitDefinitionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLimitDefinition = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		LimitDefinitionID uuid.UUID `json:"limit_definition_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EntitlementBinding.Query().
//		GroupBy(entitlementbinding.FieldLimitDefinitionID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *EntitlementBindingQuery) GroupBy(field string, fields ...string) *EntitlementBindingGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EntitlementBindingGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = entitlementbinding.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		LimitDefinitionID uuid.UUID `json:"limit_definition_id,omitempty"`
//	}
//
//	client.EntitlementBinding.Query().
//		Select(entitlementbinding.FieldLimitDefinitionID).
//		Scan(ctx, &v)
func (_q *EntitlementBindingQuery) Select(fields ...string) *EntitlementBindingSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &EntitlementBindingSelect{EntitlementBindingQuery: _q}
	sbuild.label = entitlementbinding.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EntitlementBindingSelect configured with the given aggregations.
func (_q *EntitlementBindingQuery) Aggregate(fns ...AggregateFunc) *EntitlementBindingSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *EntitlementBindingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !entitlementbinding.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *EntitlementBindingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EntitlementBinding, error) {
	var (
		nodes       = []*EntitlementBinding{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withLimitDefinition != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EntitlementBinding).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EntitlementBinding{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withLimitDefinition; query != nil {
		if err := _q.loadLimitDefinition(ctx, query, nodes, nil,
			func(n *EntitlementBinding, e *LimitDefinition) { n.Edges.LimitDefinition = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *EntitlementBindingQuery) loadLimitDefinition(ctx context.Context, query *LimitDefinitionQuery, nodes []*EntitlementBinding, init func(*EntitlementBinding), assign func(*EntitlementBinding, *LimitDefinition)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*EntitlementBinding)
	for i := range nodes {
		fk := nodes[i].LimitDefinitionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(limitdefinition.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "limit_definition_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *EntitlementBindingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *EntitlementBindingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(entitlementbinding.Table, entitlementbinding.Columns, sqlgraph.NewFieldSpec(entitlementbinding.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entitlementbinding.FieldID)
		for i := range fields {
			if fields[i] != entitlementbinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withLimitDefinition != nil {
			_spec.Node.AddColumnOnce(entitlementbinding.FieldLimitDefinitionID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *EntitlementBindingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(entitlementbinding.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = entitlementbinding.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *EntitlementBindingQuery) ForUpdate(opts ...sql.LockOption) *EntitlementBindingQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *EntitlementBindingQuery) ForShare(opts ...sql.LockOption) *EntitlementBindingQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// EntitlementBindingGroupBy is the group-by builder for EntitlementBinding entities.
type EntitlementBindingGroupBy struct {
	selector
	build *EntitlementBindingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *EntitlementBindingGroupBy) Aggregate(fns ...AggregateFunc) *EntitlementBindingGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *EntitlementBindingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntitlementBindingQuery, *EntitlementBindingGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *EntitlementBindingGroupBy) sqlScan(ctx context.Context, root *EntitlementBindingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EntitlementBindingSelect is the builder for selecting fields of EntitlementBinding entities.
type EntitlementBindingSelect struct {
	*EntitlementBindingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *EntitlementBindingSelect) Aggregate(fns ...AggregateFunc) *EntitlementBindingSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *EntitlementBindingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntitlementBindingQuery, *EntitlementBindingSelect](ctx, _s.EntitlementBindingQuery, _s, _s.inters, v)
}

func (_s *EntitlementBindingSelect) sqlScan(ctx context.Context, root *EntitlementBindingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
