// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/noncecache"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// NonceCacheUpdate is the builder for updating NonceCache entities.
type NonceCacheUpdate struct {
	config
	hooks    []Hook
	mutation *NonceCacheMutation
}

// Where appends a list predicates to the NonceCacheUpdate builder.
func (_u *NonceCacheUpdate) Where(ps ...predicate.NonceCache) *NonceCacheUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNonce sets the "nonce" field.
func (_u *NonceCacheUpdate) SetNonce(v string) *NonceCacheUpdate {
	_u.mutation.SetNonce(v)
	return _u
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_u *NonceCacheUpdate) SetNillableNonce(v *string) *NonceCacheUpdate {
	if v != nil {
		_u.SetNonce(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *NonceCacheUpdate) SetExpiresAt(v time.Time) *NonceCacheUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *NonceCacheUpdate) SetNillableExpiresAt(v *time.Time) *NonceCacheUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the NonceCacheMutation object of the builder.
func (_u *NonceCacheUpdate) Mutation() *NonceCacheMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NonceCacheUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NonceCacheUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NonceCacheUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NonceCacheUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NonceCacheUpdate) check() error {
	if v, ok := _u.mutation.Nonce(); ok {
		if err := noncecache.NonceValidator(v); err != nil {
			return &ValidationError{Name: "nonce", err: fmt.Errorf(`ent: validator failed for field "NonceCache.nonce": %w`, err)}
		}
	}
	return nil
}

func (_u *NonceCacheUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(noncecache.Table, noncecache.Columns, sqlgraph.NewFieldSpec(noncecache.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Nonce(); ok {
		_spec.SetField(noncecache.FieldNonce, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(noncecache.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{noncecache.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NonceCacheUpdateOne is the builder for updating a single NonceCache entity.
type NonceCacheUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NonceCacheMutation
}

// SetNonce sets the "nonce" field.
func (_u *NonceCacheUpdateOne) SetNonce(v string) *NonceCacheUpdateOne {
	_u.mutation.SetNonce(v)
	return _u
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_u *NonceCacheUpdateOne) SetNillableNonce(v *string) *NonceCacheUpdateOne {
	if v != nil {
		_u.SetNonce(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *NonceCacheUpdateOne) SetExpiresAt(v time.Time) *NonceCacheUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *NonceCacheUpdateOne) SetNillableExpiresAt(v *time.Time) *NonceCacheUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the NonceCacheMutation object of the builder.
func (_u *NonceCacheUpdateOne) Mutation() *NonceCacheMutation {
	return _u.mutation
}

// Where appends a list predicates to the NonceCacheUpdate builder.
func (_u *NonceCacheUpdateOne) Where(ps ...predicate.NonceCache) *NonceCacheUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NonceCacheUpdateOne) Select(field string, fields ...string) *NonceCacheUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NonceCache entity.
func (_u *NonceCacheUpdateOne) Save(ctx context.Context) (*NonceCache, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NonceCacheUpdateOne) SaveX(ctx context.Context) *NonceCache {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NonceCacheUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NonceCacheUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NonceCacheUpdateOne) check() error {
	if v, ok := _u.mutation.Nonce(); ok {
		if err := noncecache.NonceValidator(v); err != nil {
			return &ValidationError{Name: "nonce", err: fmt.Errorf(`ent: validator failed for field "NonceCache.nonce": %w`, err)}
		}
	}
	return nil
}

func (_u *NonceCacheUpdateOne) sqlSave(ctx context.Context) (_node *NonceCache, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(noncecache.Table, noncecache.Columns, sqlgraph.NewFieldSpec(noncecache.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NonceCache.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, noncecache.FieldID)
		for _, f := range fields {
			if !noncecache.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != noncecache.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Nonce(); ok {
		_spec.SetField(noncecache.FieldNonce, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(noncecache.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &NonceCache{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{noncecache.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
