// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/noncecache"
	"github.com/google/uuid"
)

// NonceCacheCreate is the builder for creating a NonceCache entity.
type NonceCacheCreate struct {
	config
	mutation *NonceCacheMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetNonce sets the "nonce" field.
func (_c *NonceCacheCreate) SetNonce(v string) *NonceCacheCreate {
	_c.mutation.SetNonce(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *NonceCacheCreate) SetExpiresAt(v time.Time) *NonceCacheCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NonceCacheCreate) SetCreatedAt(v time.Time) *NonceCacheCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NonceCacheCreate) SetNillableCreatedAt(v *time.Time) *NonceCacheCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NonceCacheCreate) SetID(v uuid.UUID) *NonceCacheCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *NonceCacheCreate) SetNillableID(v *uuid.UUID) *NonceCacheCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the NonceCacheMutation object of the builder.
func (_c *NonceCacheCreate) Mutation() *NonceCacheMutation {
	return _c.mutation
}

// Save creates the NonceCache in the database.
func (_c *NonceCacheCreate) Save(ctx context.Context) (*NonceCache, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NonceCacheCreate) SaveX(ctx context.Context) *NonceCache {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NonceCacheCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NonceCacheCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NonceCacheCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := noncecache.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := noncecache.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NonceCacheCreate) check() error {
	if _, ok := _c.mutation.Nonce(); !ok {
		return &ValidationError{Name: "nonce", err: errors.New(`ent: missing required field "NonceCache.nonce"`)}
	}
	if v, ok := _c.mutation.Nonce(); ok {
		if err := noncecache.NonceValidator(v); err != nil {
			return &ValidationError{Name: "nonce", err: fmt.Errorf(`ent: validator failed for field "NonceCache.nonce": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "NonceCache.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NonceCache.created_at"`)}
	}
	return nil
}

func (_c *NonceCacheCreate) sqlSave(ctx context.Context) (*NonceCache, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NonceCacheCreate) createSpec() (*NonceCache, *sqlgraph.CreateSpec) {
	var (
		_node = &NonceCache{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(noncecache.Table, sqlgraph.NewFieldSpec(noncecache.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Nonce(); ok {
		_spec.SetField(noncecache.FieldNonce, field.TypeString, value)
		_node.Nonce = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(noncecache.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(noncecache.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NonceCache.Create().
//		SetNonce(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NonceCacheUpsert) {
//			SetNonce(v+v).
//		}).
//		Exec(ctx)
func (_c *NonceCacheCreate) OnConflict(opts ...sql.ConflictOption) *NonceCacheUpsertOne {
	_c.conflict = opts
	return &NonceCacheUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NonceCache.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NonceCacheCreate) OnConflictColumns(columns ...string) *NonceCacheUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NonceCacheUpsertOne{
		create: _c,
	}
}

type (
	// NonceCacheUpsertOne is the builder for "upsert"-ing
	//  one NonceCache node.
	NonceCacheUpsertOne struct {
		create *NonceCacheCreate
	}

	// NonceCacheUpsert is the "OnConflict" setter.
	NonceCacheUpsert struct {
		*sql.UpdateSet
	}
)

// SetNonce sets the "nonce" field.
func (u *NonceCacheUpsert) SetNonce(v string) *NonceCacheUpsert {
	u.Set(noncecache.FieldNonce, v)
	return u
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *NonceCacheUpsert) UpdateNonce() *NonceCacheUpsert {
	u.SetExcluded(noncecache.FieldNonce)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *NonceCacheUpsert) SetExpiresAt(v time.Time) *NonceCacheUpsert {
	u.Set(noncecache.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *NonceCacheUpsert) UpdateExpiresAt() *NonceCacheUpsert {
	u.SetExcluded(noncecache.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.NonceCache.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(noncecache.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NonceCacheUpsertOne) UpdateNewValues() *NonceCacheUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(noncecache.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(noncecache.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NonceCache.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NonceCacheUpsertOne) Ignore() *NonceCacheUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NonceCacheUpsertOne) DoNothing() *NonceCacheUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NonceCacheCreate.OnConflict
// documentation for more info.
func (u *NonceCacheUpsertOne) Update(set func(*NonceCacheUpsert)) *NonceCacheUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NonceCacheUpsert{UpdateSet: update})
	}))
	return u
}

// SetNonce sets the "nonce" field.
func (u *NonceCacheUpsertOne) SetNonce(v string) *NonceCacheUpsertOne {
	return u.Update(func(s *NonceCacheUpsert) {
		s.SetNonce(v)
	})
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *NonceCacheUpsertOne) UpdateNonce() *NonceCacheUpsertOne {
	return u.Update(func(s *NonceCacheUpsert) {
		s.UpdateNonce()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *NonceCacheUpsertOne) SetExpiresAt(v time.Time) *NonceCacheUpsertOne {
	return u.Update(func(s *NonceCacheUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *NonceCacheUpsertOne) UpdateExpiresAt() *NonceCacheUpsertOne {
	return u.Update(func(s *NonceCacheUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *NonceCacheUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NonceCacheCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NonceCacheUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NonceCacheUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: NonceCacheUpsertOne.ID is not supported by MySQL driver. Use NonceCacheUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NonceCacheUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NonceCacheCreateBulk is the builder for creating many NonceCache entities in bulk.
type NonceCacheCreateBulk struct {
	config
	err      error
	builders []*NonceCacheCreate
	conflict []sql.ConflictOption
}

// Save creates the NonceCache entities in the database.
func (_c *NonceCacheCreateBulk) Save(ctx context.Context) ([]*NonceCache, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NonceCache, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NonceCacheMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NonceCacheCreateBulk) SaveX(ctx context.Context) []*NonceCache {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NonceCacheCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NonceCacheCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NonceCache.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NonceCacheUpsert) {
//			SetNonce(v+v).
//		}).
//		Exec(ctx)
func (_c *NonceCacheCreateBulk) OnConflict(opts ...sql.ConflictOption) *NonceCacheUpsertBulk {
	_c.conflict = opts
	return &NonceCacheUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NonceCache.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NonceCacheCreateBulk) OnConflictColumns(columns ...string) *NonceCacheUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NonceCacheUpsertBulk{
		create: _c,
	}
}

// NonceCacheUpsertBulk is the builder for "upsert"-ing
// a bulk of NonceCache nodes.
type NonceCacheUpsertBulk struct {
	create *NonceCacheCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NonceCache.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(noncecache.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NonceCacheUpsertBulk) UpdateNewValues() *NonceCacheUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(noncecache.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(noncecache.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NonceCache.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NonceCacheUpsertBulk) Ignore() *NonceCacheUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NonceCacheUpsertBulk) DoNothing() *NonceCacheUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NonceCacheCreateBulk.OnConflict
// documentation for more info.
func (u *NonceCacheUpsertBulk) Update(set func(*NonceCacheUpsert)) *NonceCacheUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NonceCacheUpsert{UpdateSet: update})
	}))
	return u
}

// SetNonce sets the "nonce" field.
func (u *NonceCacheUpsertBulk) SetNonce(v string) *NonceCacheUpsertBulk {
	return u.Update(func(s *NonceCacheUpsert) {
		s.SetNonce(v)
	})
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *NonceCacheUpsertBulk) UpdateNonce() *NonceCacheUpsertBulk {
	return u.Update(func(s *NonceCacheUpsert) {
		s.UpdateNonce()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *NonceCacheUpsertBulk) SetExpiresAt(v time.Time) *NonceCacheUpsertBulk {
	return u.Update(func(s *NonceCacheUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *NonceCacheUpsertBulk) UpdateExpiresAt() *NonceCacheUpsertBulk {
	return u.Update(func(s *NonceCacheUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *NonceCacheUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NonceCacheCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NonceCacheCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NonceCacheUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
