// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/skillinjection"
	"github.com/google/uuid"
)

// SkillInjectionCreate is the builder for creating a SkillInjection entity.
type SkillInjectionCreate struct {
	config
	mutation *SkillInjectionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetScope sets the "scope" field.
func (_c *SkillInjectionCreate) SetScope(v skillinjection.Scope) *SkillInjectionCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetScopeID sets the "scope_id" field.
func (_c *SkillInjectionCreate) SetScopeID(v string) *SkillInjectionCreate {
	_c.mutation.SetScopeID(v)
	return _c
}

// SetSkillURI sets the "skill_uri" field.
func (_c *SkillInjectionCreate) SetSkillURI(v string) *SkillInjectionCreate {
	_c.mutation.SetSkillURI(v)
	return _c
}

// SetSkillAs sets the "skill_as" field.
func (_c *SkillInjectionCreate) SetSkillAs(v string) *SkillInjectionCreate {
	_c.mutation.SetSkillAs(v)
	return _c
}

// SetNillableSkillAs sets the "skill_as" field if the given value is not nil.
func (_c *SkillInjectionCreate) SetNillableSkillAs(v *string) *SkillInjectionCreate {
	if v != nil {
		_c.SetSkillAs(*v)
	}
	return _c
}

// SetOptional sets the "optional" field.
func (_c *SkillInjectionCreate) SetOptional(v bool) *SkillInjectionCreate {
	_c.mutation.SetOptional(v)
	return _c
}

// SetNillableOptional sets the "optional" field if the given value is not nil.
func (_c *SkillInjectionCreate) SetNillableOptional(v *bool) *SkillInjectionCreate {
	if v != nil {
		_c.SetOptional(*v)
	}
	return _c
}

// SetAllowProgeny sets the "allow_progeny" field.
func (_c *SkillInjectionCreate) SetAllowProgeny(v bool) *SkillInjectionCreate {
	_c.mutation.SetAllowProgeny(v)
	return _c
}

// SetNillableAllowProgeny sets the "allow_progeny" field if the given value is not nil.
func (_c *SkillInjectionCreate) SetNillableAllowProgeny(v *bool) *SkillInjectionCreate {
	if v != nil {
		_c.SetAllowProgeny(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *SkillInjectionCreate) SetSortOrder(v int) *SkillInjectionCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *SkillInjectionCreate) SetNillableSortOrder(v *int) *SkillInjectionCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SkillInjectionCreate) SetCreatedAt(v time.Time) *SkillInjectionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SkillInjectionCreate) SetNillableCreatedAt(v *time.Time) *SkillInjectionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SkillInjectionCreate) SetCreatedBy(v string) *SkillInjectionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *SkillInjectionCreate) SetNillableCreatedBy(v *string) *SkillInjectionCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SkillInjectionCreate) SetID(v uuid.UUID) *SkillInjectionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SkillInjectionCreate) SetNillableID(v *uuid.UUID) *SkillInjectionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SkillInjectionMutation object of the builder.
func (_c *SkillInjectionCreate) Mutation() *SkillInjectionMutation {
	return _c.mutation
}

// Save creates the SkillInjection in the database.
func (_c *SkillInjectionCreate) Save(ctx context.Context) (*SkillInjection, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SkillInjectionCreate) SaveX(ctx context.Context) *SkillInjection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SkillInjectionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SkillInjectionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SkillInjectionCreate) defaults() {
	if _, ok := _c.mutation.Optional(); !ok {
		v := skillinjection.DefaultOptional
		_c.mutation.SetOptional(v)
	}
	if _, ok := _c.mutation.AllowProgeny(); !ok {
		v := skillinjection.DefaultAllowProgeny
		_c.mutation.SetAllowProgeny(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := skillinjection.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := skillinjection.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := skillinjection.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SkillInjectionCreate) check() error {
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "SkillInjection.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := skillinjection.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "SkillInjection.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScopeID(); !ok {
		return &ValidationError{Name: "scope_id", err: errors.New(`ent: missing required field "SkillInjection.scope_id"`)}
	}
	if _, ok := _c.mutation.SkillURI(); !ok {
		return &ValidationError{Name: "skill_uri", err: errors.New(`ent: missing required field "SkillInjection.skill_uri"`)}
	}
	if _, ok := _c.mutation.Optional(); !ok {
		return &ValidationError{Name: "optional", err: errors.New(`ent: missing required field "SkillInjection.optional"`)}
	}
	if _, ok := _c.mutation.AllowProgeny(); !ok {
		return &ValidationError{Name: "allow_progeny", err: errors.New(`ent: missing required field "SkillInjection.allow_progeny"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "SkillInjection.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SkillInjection.created_at"`)}
	}
	return nil
}

func (_c *SkillInjectionCreate) sqlSave(ctx context.Context) (*SkillInjection, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SkillInjectionCreate) createSpec() (*SkillInjection, *sqlgraph.CreateSpec) {
	var (
		_node = &SkillInjection{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(skillinjection.Table, sqlgraph.NewFieldSpec(skillinjection.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(skillinjection.FieldScope, field.TypeEnum, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.ScopeID(); ok {
		_spec.SetField(skillinjection.FieldScopeID, field.TypeString, value)
		_node.ScopeID = value
	}
	if value, ok := _c.mutation.SkillURI(); ok {
		_spec.SetField(skillinjection.FieldSkillURI, field.TypeString, value)
		_node.SkillURI = value
	}
	if value, ok := _c.mutation.SkillAs(); ok {
		_spec.SetField(skillinjection.FieldSkillAs, field.TypeString, value)
		_node.SkillAs = value
	}
	if value, ok := _c.mutation.Optional(); ok {
		_spec.SetField(skillinjection.FieldOptional, field.TypeBool, value)
		_node.Optional = value
	}
	if value, ok := _c.mutation.AllowProgeny(); ok {
		_spec.SetField(skillinjection.FieldAllowProgeny, field.TypeBool, value)
		_node.AllowProgeny = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(skillinjection.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(skillinjection.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(skillinjection.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SkillInjection.Create().
//		SetScope(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SkillInjectionUpsert) {
//			SetScope(v+v).
//		}).
//		Exec(ctx)
func (_c *SkillInjectionCreate) OnConflict(opts ...sql.ConflictOption) *SkillInjectionUpsertOne {
	_c.conflict = opts
	return &SkillInjectionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SkillInjection.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SkillInjectionCreate) OnConflictColumns(columns ...string) *SkillInjectionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SkillInjectionUpsertOne{
		create: _c,
	}
}

type (
	// SkillInjectionUpsertOne is the builder for "upsert"-ing
	//  one SkillInjection node.
	SkillInjectionUpsertOne struct {
		create *SkillInjectionCreate
	}

	// SkillInjectionUpsert is the "OnConflict" setter.
	SkillInjectionUpsert struct {
		*sql.UpdateSet
	}
)

// SetScope sets the "scope" field.
func (u *SkillInjectionUpsert) SetScope(v skillinjection.Scope) *SkillInjectionUpsert {
	u.Set(skillinjection.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SkillInjectionUpsert) UpdateScope() *SkillInjectionUpsert {
	u.SetExcluded(skillinjection.FieldScope)
	return u
}

// SetScopeID sets the "scope_id" field.
func (u *SkillInjectionUpsert) SetScopeID(v string) *SkillInjectionUpsert {
	u.Set(skillinjection.FieldScopeID, v)
	return u
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *SkillInjectionUpsert) UpdateScopeID() *SkillInjectionUpsert {
	u.SetExcluded(skillinjection.FieldScopeID)
	return u
}

// SetSkillURI sets the "skill_uri" field.
func (u *SkillInjectionUpsert) SetSkillURI(v string) *SkillInjectionUpsert {
	u.Set(skillinjection.FieldSkillURI, v)
	return u
}

// UpdateSkillURI sets the "skill_uri" field to the value that was provided on create.
func (u *SkillInjectionUpsert) UpdateSkillURI() *SkillInjectionUpsert {
	u.SetExcluded(skillinjection.FieldSkillURI)
	return u
}

// SetSkillAs sets the "skill_as" field.
func (u *SkillInjectionUpsert) SetSkillAs(v string) *SkillInjectionUpsert {
	u.Set(skillinjection.FieldSkillAs, v)
	return u
}

// UpdateSkillAs sets the "skill_as" field to the value that was provided on create.
func (u *SkillInjectionUpsert) UpdateSkillAs() *SkillInjectionUpsert {
	u.SetExcluded(skillinjection.FieldSkillAs)
	return u
}

// ClearSkillAs clears the value of the "skill_as" field.
func (u *SkillInjectionUpsert) ClearSkillAs() *SkillInjectionUpsert {
	u.SetNull(skillinjection.FieldSkillAs)
	return u
}

// SetOptional sets the "optional" field.
func (u *SkillInjectionUpsert) SetOptional(v bool) *SkillInjectionUpsert {
	u.Set(skillinjection.FieldOptional, v)
	return u
}

// UpdateOptional sets the "optional" field to the value that was provided on create.
func (u *SkillInjectionUpsert) UpdateOptional() *SkillInjectionUpsert {
	u.SetExcluded(skillinjection.FieldOptional)
	return u
}

// SetAllowProgeny sets the "allow_progeny" field.
func (u *SkillInjectionUpsert) SetAllowProgeny(v bool) *SkillInjectionUpsert {
	u.Set(skillinjection.FieldAllowProgeny, v)
	return u
}

// UpdateAllowProgeny sets the "allow_progeny" field to the value that was provided on create.
func (u *SkillInjectionUpsert) UpdateAllowProgeny() *SkillInjectionUpsert {
	u.SetExcluded(skillinjection.FieldAllowProgeny)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *SkillInjectionUpsert) SetSortOrder(v int) *SkillInjectionUpsert {
	u.Set(skillinjection.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SkillInjectionUpsert) UpdateSortOrder() *SkillInjectionUpsert {
	u.SetExcluded(skillinjection.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SkillInjectionUpsert) AddSortOrder(v int) *SkillInjectionUpsert {
	u.Add(skillinjection.FieldSortOrder, v)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *SkillInjectionUpsert) SetCreatedBy(v string) *SkillInjectionUpsert {
	u.Set(skillinjection.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SkillInjectionUpsert) UpdateCreatedBy() *SkillInjectionUpsert {
	u.SetExcluded(skillinjection.FieldCreatedBy)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SkillInjectionUpsert) ClearCreatedBy() *SkillInjectionUpsert {
	u.SetNull(skillinjection.FieldCreatedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SkillInjection.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(skillinjection.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SkillInjectionUpsertOne) UpdateNewValues() *SkillInjectionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(skillinjection.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(skillinjection.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SkillInjection.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SkillInjectionUpsertOne) Ignore() *SkillInjectionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SkillInjectionUpsertOne) DoNothing() *SkillInjectionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SkillInjectionCreate.OnConflict
// documentation for more info.
func (u *SkillInjectionUpsertOne) Update(set func(*SkillInjectionUpsert)) *SkillInjectionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SkillInjectionUpsert{UpdateSet: update})
	}))
	return u
}

// SetScope sets the "scope" field.
func (u *SkillInjectionUpsertOne) SetScope(v skillinjection.Scope) *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SkillInjectionUpsertOne) UpdateScope() *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.UpdateScope()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *SkillInjectionUpsertOne) SetScopeID(v string) *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.SetScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *SkillInjectionUpsertOne) UpdateScopeID() *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.UpdateScopeID()
	})
}

// SetSkillURI sets the "skill_uri" field.
func (u *SkillInjectionUpsertOne) SetSkillURI(v string) *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.SetSkillURI(v)
	})
}

// UpdateSkillURI sets the "skill_uri" field to the value that was provided on create.
func (u *SkillInjectionUpsertOne) UpdateSkillURI() *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.UpdateSkillURI()
	})
}

// SetSkillAs sets the "skill_as" field.
func (u *SkillInjectionUpsertOne) SetSkillAs(v string) *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.SetSkillAs(v)
	})
}

// UpdateSkillAs sets the "skill_as" field to the value that was provided on create.
func (u *SkillInjectionUpsertOne) UpdateSkillAs() *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.UpdateSkillAs()
	})
}

// ClearSkillAs clears the value of the "skill_as" field.
func (u *SkillInjectionUpsertOne) ClearSkillAs() *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.ClearSkillAs()
	})
}

// SetOptional sets the "optional" field.
func (u *SkillInjectionUpsertOne) SetOptional(v bool) *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.SetOptional(v)
	})
}

// UpdateOptional sets the "optional" field to the value that was provided on create.
func (u *SkillInjectionUpsertOne) UpdateOptional() *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.UpdateOptional()
	})
}

// SetAllowProgeny sets the "allow_progeny" field.
func (u *SkillInjectionUpsertOne) SetAllowProgeny(v bool) *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.SetAllowProgeny(v)
	})
}

// UpdateAllowProgeny sets the "allow_progeny" field to the value that was provided on create.
func (u *SkillInjectionUpsertOne) UpdateAllowProgeny() *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.UpdateAllowProgeny()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *SkillInjectionUpsertOne) SetSortOrder(v int) *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SkillInjectionUpsertOne) AddSortOrder(v int) *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SkillInjectionUpsertOne) UpdateSortOrder() *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.UpdateSortOrder()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *SkillInjectionUpsertOne) SetCreatedBy(v string) *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SkillInjectionUpsertOne) UpdateCreatedBy() *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SkillInjectionUpsertOne) ClearCreatedBy() *SkillInjectionUpsertOne {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.ClearCreatedBy()
	})
}

// Exec executes the query.
func (u *SkillInjectionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SkillInjectionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SkillInjectionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SkillInjectionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SkillInjectionUpsertOne.ID is not supported by MySQL driver. Use SkillInjectionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SkillInjectionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SkillInjectionCreateBulk is the builder for creating many SkillInjection entities in bulk.
type SkillInjectionCreateBulk struct {
	config
	err      error
	builders []*SkillInjectionCreate
	conflict []sql.ConflictOption
}

// Save creates the SkillInjection entities in the database.
func (_c *SkillInjectionCreateBulk) Save(ctx context.Context) ([]*SkillInjection, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SkillInjection, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SkillInjectionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SkillInjectionCreateBulk) SaveX(ctx context.Context) []*SkillInjection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SkillInjectionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SkillInjectionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SkillInjection.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SkillInjectionUpsert) {
//			SetScope(v+v).
//		}).
//		Exec(ctx)
func (_c *SkillInjectionCreateBulk) OnConflict(opts ...sql.ConflictOption) *SkillInjectionUpsertBulk {
	_c.conflict = opts
	return &SkillInjectionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SkillInjection.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SkillInjectionCreateBulk) OnConflictColumns(columns ...string) *SkillInjectionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SkillInjectionUpsertBulk{
		create: _c,
	}
}

// SkillInjectionUpsertBulk is the builder for "upsert"-ing
// a bulk of SkillInjection nodes.
type SkillInjectionUpsertBulk struct {
	create *SkillInjectionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SkillInjection.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(skillinjection.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SkillInjectionUpsertBulk) UpdateNewValues() *SkillInjectionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(skillinjection.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(skillinjection.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SkillInjection.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SkillInjectionUpsertBulk) Ignore() *SkillInjectionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SkillInjectionUpsertBulk) DoNothing() *SkillInjectionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SkillInjectionCreateBulk.OnConflict
// documentation for more info.
func (u *SkillInjectionUpsertBulk) Update(set func(*SkillInjectionUpsert)) *SkillInjectionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SkillInjectionUpsert{UpdateSet: update})
	}))
	return u
}

// SetScope sets the "scope" field.
func (u *SkillInjectionUpsertBulk) SetScope(v skillinjection.Scope) *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SkillInjectionUpsertBulk) UpdateScope() *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.UpdateScope()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *SkillInjectionUpsertBulk) SetScopeID(v string) *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.SetScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *SkillInjectionUpsertBulk) UpdateScopeID() *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.UpdateScopeID()
	})
}

// SetSkillURI sets the "skill_uri" field.
func (u *SkillInjectionUpsertBulk) SetSkillURI(v string) *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.SetSkillURI(v)
	})
}

// UpdateSkillURI sets the "skill_uri" field to the value that was provided on create.
func (u *SkillInjectionUpsertBulk) UpdateSkillURI() *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.UpdateSkillURI()
	})
}

// SetSkillAs sets the "skill_as" field.
func (u *SkillInjectionUpsertBulk) SetSkillAs(v string) *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.SetSkillAs(v)
	})
}

// UpdateSkillAs sets the "skill_as" field to the value that was provided on create.
func (u *SkillInjectionUpsertBulk) UpdateSkillAs() *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.UpdateSkillAs()
	})
}

// ClearSkillAs clears the value of the "skill_as" field.
func (u *SkillInjectionUpsertBulk) ClearSkillAs() *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.ClearSkillAs()
	})
}

// SetOptional sets the "optional" field.
func (u *SkillInjectionUpsertBulk) SetOptional(v bool) *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.SetOptional(v)
	})
}

// UpdateOptional sets the "optional" field to the value that was provided on create.
func (u *SkillInjectionUpsertBulk) UpdateOptional() *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.UpdateOptional()
	})
}

// SetAllowProgeny sets the "allow_progeny" field.
func (u *SkillInjectionUpsertBulk) SetAllowProgeny(v bool) *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.SetAllowProgeny(v)
	})
}

// UpdateAllowProgeny sets the "allow_progeny" field to the value that was provided on create.
func (u *SkillInjectionUpsertBulk) UpdateAllowProgeny() *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.UpdateAllowProgeny()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *SkillInjectionUpsertBulk) SetSortOrder(v int) *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SkillInjectionUpsertBulk) AddSortOrder(v int) *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SkillInjectionUpsertBulk) UpdateSortOrder() *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.UpdateSortOrder()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *SkillInjectionUpsertBulk) SetCreatedBy(v string) *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SkillInjectionUpsertBulk) UpdateCreatedBy() *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SkillInjectionUpsertBulk) ClearCreatedBy() *SkillInjectionUpsertBulk {
	return u.Update(func(s *SkillInjectionUpsert) {
		s.ClearCreatedBy()
	})
}

// Exec executes the query.
func (u *SkillInjectionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SkillInjectionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SkillInjectionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SkillInjectionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
