// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/skillinjection"
	"github.com/google/uuid"
)

// SkillInjection is the model entity for the SkillInjection schema.
type SkillInjection struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope skillinjection.Scope `json:"scope,omitempty"`
	// ScopeID holds the value of the "scope_id" field.
	ScopeID string `json:"scope_id,omitempty"`
	// SkillURI holds the value of the "skill_uri" field.
	SkillURI string `json:"skill_uri,omitempty"`
	// SkillAs holds the value of the "skill_as" field.
	SkillAs string `json:"skill_as,omitempty"`
	// Optional holds the value of the "optional" field.
	Optional bool `json:"optional,omitempty"`
	// AllowProgeny holds the value of the "allow_progeny" field.
	AllowProgeny bool `json:"allow_progeny,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy    string `json:"created_by,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SkillInjection) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case skillinjection.FieldOptional, skillinjection.FieldAllowProgeny:
			values[i] = new(sql.NullBool)
		case skillinjection.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case skillinjection.FieldScope, skillinjection.FieldScopeID, skillinjection.FieldSkillURI, skillinjection.FieldSkillAs, skillinjection.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case skillinjection.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case skillinjection.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SkillInjection fields.
func (_m *SkillInjection) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case skillinjection.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case skillinjection.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = skillinjection.Scope(value.String)
			}
		case skillinjection.FieldScopeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_id", values[i])
			} else if value.Valid {
				_m.ScopeID = value.String
			}
		case skillinjection.FieldSkillURI:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field skill_uri", values[i])
			} else if value.Valid {
				_m.SkillURI = value.String
			}
		case skillinjection.FieldSkillAs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field skill_as", values[i])
			} else if value.Valid {
				_m.SkillAs = value.String
			}
		case skillinjection.FieldOptional:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field optional", values[i])
			} else if value.Valid {
				_m.Optional = value.Bool
			}
		case skillinjection.FieldAllowProgeny:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_progeny", values[i])
			} else if value.Valid {
				_m.AllowProgeny = value.Bool
			}
		case skillinjection.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case skillinjection.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case skillinjection.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SkillInjection.
// This includes values selected through modifiers, order, etc.
func (_m *SkillInjection) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SkillInjection.
// Note that you need to call SkillInjection.Unwrap() before calling this method if this SkillInjection
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SkillInjection) Update() *SkillInjectionUpdateOne {
	return NewSkillInjectionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SkillInjection entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SkillInjection) Unwrap() *SkillInjection {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SkillInjection is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SkillInjection) String() string {
	var builder strings.Builder
	builder.WriteString("SkillInjection(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("scope=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scope))
	builder.WriteString(", ")
	builder.WriteString("scope_id=")
	builder.WriteString(_m.ScopeID)
	builder.WriteString(", ")
	builder.WriteString("skill_uri=")
	builder.WriteString(_m.SkillURI)
	builder.WriteString(", ")
	builder.WriteString("skill_as=")
	builder.WriteString(_m.SkillAs)
	builder.WriteString(", ")
	builder.WriteString("optional=")
	builder.WriteString(fmt.Sprintf("%v", _m.Optional))
	builder.WriteString(", ")
	builder.WriteString("allow_progeny=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowProgeny))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteByte(')')
	return builder.String()
}

// SkillInjections is a parsable slice of SkillInjection.
type SkillInjections []*SkillInjection
