// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/skillinjection"
)

// SkillInjectionUpdate is the builder for updating SkillInjection entities.
type SkillInjectionUpdate struct {
	config
	hooks    []Hook
	mutation *SkillInjectionMutation
}

// Where appends a list predicates to the SkillInjectionUpdate builder.
func (_u *SkillInjectionUpdate) Where(ps ...predicate.SkillInjection) *SkillInjectionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScope sets the "scope" field.
func (_u *SkillInjectionUpdate) SetScope(v skillinjection.Scope) *SkillInjectionUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *SkillInjectionUpdate) SetNillableScope(v *skillinjection.Scope) *SkillInjectionUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *SkillInjectionUpdate) SetScopeID(v string) *SkillInjectionUpdate {
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *SkillInjectionUpdate) SetNillableScopeID(v *string) *SkillInjectionUpdate {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// SetSkillURI sets the "skill_uri" field.
func (_u *SkillInjectionUpdate) SetSkillURI(v string) *SkillInjectionUpdate {
	_u.mutation.SetSkillURI(v)
	return _u
}

// SetNillableSkillURI sets the "skill_uri" field if the given value is not nil.
func (_u *SkillInjectionUpdate) SetNillableSkillURI(v *string) *SkillInjectionUpdate {
	if v != nil {
		_u.SetSkillURI(*v)
	}
	return _u
}

// SetSkillAs sets the "skill_as" field.
func (_u *SkillInjectionUpdate) SetSkillAs(v string) *SkillInjectionUpdate {
	_u.mutation.SetSkillAs(v)
	return _u
}

// SetNillableSkillAs sets the "skill_as" field if the given value is not nil.
func (_u *SkillInjectionUpdate) SetNillableSkillAs(v *string) *SkillInjectionUpdate {
	if v != nil {
		_u.SetSkillAs(*v)
	}
	return _u
}

// ClearSkillAs clears the value of the "skill_as" field.
func (_u *SkillInjectionUpdate) ClearSkillAs() *SkillInjectionUpdate {
	_u.mutation.ClearSkillAs()
	return _u
}

// SetOptional sets the "optional" field.
func (_u *SkillInjectionUpdate) SetOptional(v bool) *SkillInjectionUpdate {
	_u.mutation.SetOptional(v)
	return _u
}

// SetNillableOptional sets the "optional" field if the given value is not nil.
func (_u *SkillInjectionUpdate) SetNillableOptional(v *bool) *SkillInjectionUpdate {
	if v != nil {
		_u.SetOptional(*v)
	}
	return _u
}

// SetAllowProgeny sets the "allow_progeny" field.
func (_u *SkillInjectionUpdate) SetAllowProgeny(v bool) *SkillInjectionUpdate {
	_u.mutation.SetAllowProgeny(v)
	return _u
}

// SetNillableAllowProgeny sets the "allow_progeny" field if the given value is not nil.
func (_u *SkillInjectionUpdate) SetNillableAllowProgeny(v *bool) *SkillInjectionUpdate {
	if v != nil {
		_u.SetAllowProgeny(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SkillInjectionUpdate) SetSortOrder(v int) *SkillInjectionUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SkillInjectionUpdate) SetNillableSortOrder(v *int) *SkillInjectionUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SkillInjectionUpdate) AddSortOrder(v int) *SkillInjectionUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SkillInjectionUpdate) SetCreatedBy(v string) *SkillInjectionUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SkillInjectionUpdate) SetNillableCreatedBy(v *string) *SkillInjectionUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SkillInjectionUpdate) ClearCreatedBy() *SkillInjectionUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// Mutation returns the SkillInjectionMutation object of the builder.
func (_u *SkillInjectionUpdate) Mutation() *SkillInjectionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SkillInjectionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkillInjectionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SkillInjectionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkillInjectionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkillInjectionUpdate) check() error {
	if v, ok := _u.mutation.Scope(); ok {
		if err := skillinjection.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "SkillInjection.scope": %w`, err)}
		}
	}
	return nil
}

func (_u *SkillInjectionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skillinjection.Table, skillinjection.Columns, sqlgraph.NewFieldSpec(skillinjection.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(skillinjection.FieldScope, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(skillinjection.FieldScopeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SkillURI(); ok {
		_spec.SetField(skillinjection.FieldSkillURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.SkillAs(); ok {
		_spec.SetField(skillinjection.FieldSkillAs, field.TypeString, value)
	}
	if _u.mutation.SkillAsCleared() {
		_spec.ClearField(skillinjection.FieldSkillAs, field.TypeString)
	}
	if value, ok := _u.mutation.Optional(); ok {
		_spec.SetField(skillinjection.FieldOptional, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowProgeny(); ok {
		_spec.SetField(skillinjection.FieldAllowProgeny, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(skillinjection.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(skillinjection.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(skillinjection.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(skillinjection.FieldCreatedBy, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skillinjection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SkillInjectionUpdateOne is the builder for updating a single SkillInjection entity.
type SkillInjectionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SkillInjectionMutation
}

// SetScope sets the "scope" field.
func (_u *SkillInjectionUpdateOne) SetScope(v skillinjection.Scope) *SkillInjectionUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *SkillInjectionUpdateOne) SetNillableScope(v *skillinjection.Scope) *SkillInjectionUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *SkillInjectionUpdateOne) SetScopeID(v string) *SkillInjectionUpdateOne {
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *SkillInjectionUpdateOne) SetNillableScopeID(v *string) *SkillInjectionUpdateOne {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// SetSkillURI sets the "skill_uri" field.
func (_u *SkillInjectionUpdateOne) SetSkillURI(v string) *SkillInjectionUpdateOne {
	_u.mutation.SetSkillURI(v)
	return _u
}

// SetNillableSkillURI sets the "skill_uri" field if the given value is not nil.
func (_u *SkillInjectionUpdateOne) SetNillableSkillURI(v *string) *SkillInjectionUpdateOne {
	if v != nil {
		_u.SetSkillURI(*v)
	}
	return _u
}

// SetSkillAs sets the "skill_as" field.
func (_u *SkillInjectionUpdateOne) SetSkillAs(v string) *SkillInjectionUpdateOne {
	_u.mutation.SetSkillAs(v)
	return _u
}

// SetNillableSkillAs sets the "skill_as" field if the given value is not nil.
func (_u *SkillInjectionUpdateOne) SetNillableSkillAs(v *string) *SkillInjectionUpdateOne {
	if v != nil {
		_u.SetSkillAs(*v)
	}
	return _u
}

// ClearSkillAs clears the value of the "skill_as" field.
func (_u *SkillInjectionUpdateOne) ClearSkillAs() *SkillInjectionUpdateOne {
	_u.mutation.ClearSkillAs()
	return _u
}

// SetOptional sets the "optional" field.
func (_u *SkillInjectionUpdateOne) SetOptional(v bool) *SkillInjectionUpdateOne {
	_u.mutation.SetOptional(v)
	return _u
}

// SetNillableOptional sets the "optional" field if the given value is not nil.
func (_u *SkillInjectionUpdateOne) SetNillableOptional(v *bool) *SkillInjectionUpdateOne {
	if v != nil {
		_u.SetOptional(*v)
	}
	return _u
}

// SetAllowProgeny sets the "allow_progeny" field.
func (_u *SkillInjectionUpdateOne) SetAllowProgeny(v bool) *SkillInjectionUpdateOne {
	_u.mutation.SetAllowProgeny(v)
	return _u
}

// SetNillableAllowProgeny sets the "allow_progeny" field if the given value is not nil.
func (_u *SkillInjectionUpdateOne) SetNillableAllowProgeny(v *bool) *SkillInjectionUpdateOne {
	if v != nil {
		_u.SetAllowProgeny(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SkillInjectionUpdateOne) SetSortOrder(v int) *SkillInjectionUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SkillInjectionUpdateOne) SetNillableSortOrder(v *int) *SkillInjectionUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SkillInjectionUpdateOne) AddSortOrder(v int) *SkillInjectionUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SkillInjectionUpdateOne) SetCreatedBy(v string) *SkillInjectionUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SkillInjectionUpdateOne) SetNillableCreatedBy(v *string) *SkillInjectionUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SkillInjectionUpdateOne) ClearCreatedBy() *SkillInjectionUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// Mutation returns the SkillInjectionMutation object of the builder.
func (_u *SkillInjectionUpdateOne) Mutation() *SkillInjectionMutation {
	return _u.mutation
}

// Where appends a list predicates to the SkillInjectionUpdate builder.
func (_u *SkillInjectionUpdateOne) Where(ps ...predicate.SkillInjection) *SkillInjectionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SkillInjectionUpdateOne) Select(field string, fields ...string) *SkillInjectionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SkillInjection entity.
func (_u *SkillInjectionUpdateOne) Save(ctx context.Context) (*SkillInjection, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkillInjectionUpdateOne) SaveX(ctx context.Context) *SkillInjection {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SkillInjectionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkillInjectionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkillInjectionUpdateOne) check() error {
	if v, ok := _u.mutation.Scope(); ok {
		if err := skillinjection.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "SkillInjection.scope": %w`, err)}
		}
	}
	return nil
}

func (_u *SkillInjectionUpdateOne) sqlSave(ctx context.Context) (_node *SkillInjection, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skillinjection.Table, skillinjection.Columns, sqlgraph.NewFieldSpec(skillinjection.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SkillInjection.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, skillinjection.FieldID)
		for _, f := range fields {
			if !skillinjection.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != skillinjection.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(skillinjection.FieldScope, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(skillinjection.FieldScopeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SkillURI(); ok {
		_spec.SetField(skillinjection.FieldSkillURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.SkillAs(); ok {
		_spec.SetField(skillinjection.FieldSkillAs, field.TypeString, value)
	}
	if _u.mutation.SkillAsCleared() {
		_spec.ClearField(skillinjection.FieldSkillAs, field.TypeString)
	}
	if value, ok := _u.mutation.Optional(); ok {
		_spec.SetField(skillinjection.FieldOptional, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowProgeny(); ok {
		_spec.SetField(skillinjection.FieldAllowProgeny, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(skillinjection.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(skillinjection.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(skillinjection.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(skillinjection.FieldCreatedBy, field.TypeString)
	}
	_node = &SkillInjection{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skillinjection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
