// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/limitdefinition"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/usagereservation"
	"github.com/google/uuid"
)

// UsageReservationCreate is the builder for creating a UsageReservation entity.
type UsageReservationCreate struct {
	config
	mutation *UsageReservationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetLimitDefinitionID sets the "limit_definition_id" field.
func (_c *UsageReservationCreate) SetLimitDefinitionID(v uuid.UUID) *UsageReservationCreate {
	_c.mutation.SetLimitDefinitionID(v)
	return _c
}

// SetSubjectID sets the "subject_id" field.
func (_c *UsageReservationCreate) SetSubjectID(v string) *UsageReservationCreate {
	_c.mutation.SetSubjectID(v)
	return _c
}

// SetScopeType sets the "scope_type" field.
func (_c *UsageReservationCreate) SetScopeType(v usagereservation.ScopeType) *UsageReservationCreate {
	_c.mutation.SetScopeType(v)
	return _c
}

// SetScopeID sets the "scope_id" field.
func (_c *UsageReservationCreate) SetScopeID(v string) *UsageReservationCreate {
	_c.mutation.SetScopeID(v)
	return _c
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_c *UsageReservationCreate) SetNillableScopeID(v *string) *UsageReservationCreate {
	if v != nil {
		_c.SetScopeID(*v)
	}
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *UsageReservationCreate) SetResourceID(v string) *UsageReservationCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetReserved sets the "reserved" field.
func (_c *UsageReservationCreate) SetReserved(v int64) *UsageReservationCreate {
	_c.mutation.SetReserved(v)
	return _c
}

// SetNillableReserved sets the "reserved" field if the given value is not nil.
func (_c *UsageReservationCreate) SetNillableReserved(v *int64) *UsageReservationCreate {
	if v != nil {
		_c.SetReserved(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UsageReservationCreate) SetCreatedAt(v time.Time) *UsageReservationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UsageReservationCreate) SetNillableCreatedAt(v *time.Time) *UsageReservationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetReleasedAt sets the "released_at" field.
func (_c *UsageReservationCreate) SetReleasedAt(v time.Time) *UsageReservationCreate {
	_c.mutation.SetReleasedAt(v)
	return _c
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_c *UsageReservationCreate) SetNillableReleasedAt(v *time.Time) *UsageReservationCreate {
	if v != nil {
		_c.SetReleasedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UsageReservationCreate) SetID(v uuid.UUID) *UsageReservationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UsageReservationCreate) SetNillableID(v *uuid.UUID) *UsageReservationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetLimitDefinition sets the "limit_definition" edge to the LimitDefinition entity.
func (_c *UsageReservationCreate) SetLimitDefinition(v *LimitDefinition) *UsageReservationCreate {
	return _c.SetLimitDefinitionID(v.ID)
}

// Mutation returns the UsageReservationMutation object of the builder.
func (_c *UsageReservationCreate) Mutation() *UsageReservationMutation {
	return _c.mutation
}

// Save creates the UsageReservation in the database.
func (_c *UsageReservationCreate) Save(ctx context.Context) (*UsageReservation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsageReservationCreate) SaveX(ctx context.Context) *UsageReservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageReservationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageReservationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UsageReservationCreate) defaults() {
	if _, ok := _c.mutation.ScopeID(); !ok {
		v := usagereservation.DefaultScopeID
		_c.mutation.SetScopeID(v)
	}
	if _, ok := _c.mutation.Reserved(); !ok {
		v := usagereservation.DefaultReserved
		_c.mutation.SetReserved(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usagereservation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := usagereservation.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsageReservationCreate) check() error {
	if _, ok := _c.mutation.LimitDefinitionID(); !ok {
		return &ValidationError{Name: "limit_definition_id", err: errors.New(`ent: missing required field "UsageReservation.limit_definition_id"`)}
	}
	if _, ok := _c.mutation.SubjectID(); !ok {
		return &ValidationError{Name: "subject_id", err: errors.New(`ent: missing required field "UsageReservation.subject_id"`)}
	}
	if v, ok := _c.mutation.SubjectID(); ok {
		if err := usagereservation.SubjectIDValidator(v); err != nil {
			return &ValidationError{Name: "subject_id", err: fmt.Errorf(`ent: validator failed for field "UsageReservation.subject_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScopeType(); !ok {
		return &ValidationError{Name: "scope_type", err: errors.New(`ent: missing required field "UsageReservation.scope_type"`)}
	}
	if v, ok := _c.mutation.ScopeType(); ok {
		if err := usagereservation.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "UsageReservation.scope_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScopeID(); !ok {
		return &ValidationError{Name: "scope_id", err: errors.New(`ent: missing required field "UsageReservation.scope_id"`)}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "UsageReservation.resource_id"`)}
	}
	if v, ok := _c.mutation.ResourceID(); ok {
		if err := usagereservation.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "UsageReservation.resource_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Reserved(); !ok {
		return &ValidationError{Name: "reserved", err: errors.New(`ent: missing required field "UsageReservation.reserved"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageReservation.created_at"`)}
	}
	if len(_c.mutation.LimitDefinitionIDs()) == 0 {
		return &ValidationError{Name: "limit_definition", err: errors.New(`ent: missing required edge "UsageReservation.limit_definition"`)}
	}
	return nil
}

func (_c *UsageReservationCreate) sqlSave(ctx context.Context) (*UsageReservation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsageReservationCreate) createSpec() (*UsageReservation, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageReservation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usagereservation.Table, sqlgraph.NewFieldSpec(usagereservation.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.SubjectID(); ok {
		_spec.SetField(usagereservation.FieldSubjectID, field.TypeString, value)
		_node.SubjectID = value
	}
	if value, ok := _c.mutation.ScopeType(); ok {
		_spec.SetField(usagereservation.FieldScopeType, field.TypeEnum, value)
		_node.ScopeType = value
	}
	if value, ok := _c.mutation.ScopeID(); ok {
		_spec.SetField(usagereservation.FieldScopeID, field.TypeString, value)
		_node.ScopeID = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(usagereservation.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Reserved(); ok {
		_spec.SetField(usagereservation.FieldReserved, field.TypeInt64, value)
		_node.Reserved = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usagereservation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ReleasedAt(); ok {
		_spec.SetField(usagereservation.FieldReleasedAt, field.TypeTime, value)
		_node.ReleasedAt = &value
	}
	if nodes := _c.mutation.LimitDefinitionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagereservation.LimitDefinitionTable,
			Columns: []string{usagereservation.LimitDefinitionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(limitdefinition.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LimitDefinitionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageReservation.Create().
//		SetLimitDefinitionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageReservationUpsert) {
//			SetLimitDefinitionID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageReservationCreate) OnConflict(opts ...sql.ConflictOption) *UsageReservationUpsertOne {
	_c.conflict = opts
	return &UsageReservationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageReservation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageReservationCreate) OnConflictColumns(columns ...string) *UsageReservationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageReservationUpsertOne{
		create: _c,
	}
}

type (
	// UsageReservationUpsertOne is the builder for "upsert"-ing
	//  one UsageReservation node.
	UsageReservationUpsertOne struct {
		create *UsageReservationCreate
	}

	// UsageReservationUpsert is the "OnConflict" setter.
	UsageReservationUpsert struct {
		*sql.UpdateSet
	}
)

// SetLimitDefinitionID sets the "limit_definition_id" field.
func (u *UsageReservationUpsert) SetLimitDefinitionID(v uuid.UUID) *UsageReservationUpsert {
	u.Set(usagereservation.FieldLimitDefinitionID, v)
	return u
}

// UpdateLimitDefinitionID sets the "limit_definition_id" field to the value that was provided on create.
func (u *UsageReservationUpsert) UpdateLimitDefinitionID() *UsageReservationUpsert {
	u.SetExcluded(usagereservation.FieldLimitDefinitionID)
	return u
}

// SetSubjectID sets the "subject_id" field.
func (u *UsageReservationUpsert) SetSubjectID(v string) *UsageReservationUpsert {
	u.Set(usagereservation.FieldSubjectID, v)
	return u
}

// UpdateSubjectID sets the "subject_id" field to the value that was provided on create.
func (u *UsageReservationUpsert) UpdateSubjectID() *UsageReservationUpsert {
	u.SetExcluded(usagereservation.FieldSubjectID)
	return u
}

// SetScopeType sets the "scope_type" field.
func (u *UsageReservationUpsert) SetScopeType(v usagereservation.ScopeType) *UsageReservationUpsert {
	u.Set(usagereservation.FieldScopeType, v)
	return u
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *UsageReservationUpsert) UpdateScopeType() *UsageReservationUpsert {
	u.SetExcluded(usagereservation.FieldScopeType)
	return u
}

// SetScopeID sets the "scope_id" field.
func (u *UsageReservationUpsert) SetScopeID(v string) *UsageReservationUpsert {
	u.Set(usagereservation.FieldScopeID, v)
	return u
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *UsageReservationUpsert) UpdateScopeID() *UsageReservationUpsert {
	u.SetExcluded(usagereservation.FieldScopeID)
	return u
}

// SetResourceID sets the "resource_id" field.
func (u *UsageReservationUpsert) SetResourceID(v string) *UsageReservationUpsert {
	u.Set(usagereservation.FieldResourceID, v)
	return u
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *UsageReservationUpsert) UpdateResourceID() *UsageReservationUpsert {
	u.SetExcluded(usagereservation.FieldResourceID)
	return u
}

// SetReserved sets the "reserved" field.
func (u *UsageReservationUpsert) SetReserved(v int64) *UsageReservationUpsert {
	u.Set(usagereservation.FieldReserved, v)
	return u
}

// UpdateReserved sets the "reserved" field to the value that was provided on create.
func (u *UsageReservationUpsert) UpdateReserved() *UsageReservationUpsert {
	u.SetExcluded(usagereservation.FieldReserved)
	return u
}

// AddReserved adds v to the "reserved" field.
func (u *UsageReservationUpsert) AddReserved(v int64) *UsageReservationUpsert {
	u.Add(usagereservation.FieldReserved, v)
	return u
}

// SetReleasedAt sets the "released_at" field.
func (u *UsageReservationUpsert) SetReleasedAt(v time.Time) *UsageReservationUpsert {
	u.Set(usagereservation.FieldReleasedAt, v)
	return u
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *UsageReservationUpsert) UpdateReleasedAt() *UsageReservationUpsert {
	u.SetExcluded(usagereservation.FieldReleasedAt)
	return u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *UsageReservationUpsert) ClearReleasedAt() *UsageReservationUpsert {
	u.SetNull(usagereservation.FieldReleasedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UsageReservation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(usagereservation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UsageReservationUpsertOne) UpdateNewValues() *UsageReservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(usagereservation.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usagereservation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageReservation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UsageReservationUpsertOne) Ignore() *UsageReservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageReservationUpsertOne) DoNothing() *UsageReservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageReservationCreate.OnConflict
// documentation for more info.
func (u *UsageReservationUpsertOne) Update(set func(*UsageReservationUpsert)) *UsageReservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageReservationUpsert{UpdateSet: update})
	}))
	return u
}

// SetLimitDefinitionID sets the "limit_definition_id" field.
func (u *UsageReservationUpsertOne) SetLimitDefinitionID(v uuid.UUID) *UsageReservationUpsertOne {
	return u.Update(func(s *UsageReservationUpsert) {
		s.SetLimitDefinitionID(v)
	})
}

// UpdateLimitDefinitionID sets the "limit_definition_id" field to the value that was provided on create.
func (u *UsageReservationUpsertOne) UpdateLimitDefinitionID() *UsageReservationUpsertOne {
	return u.Update(func(s *UsageReservationUpsert) {
		s.UpdateLimitDefinitionID()
	})
}

// SetSubjectID sets the "subject_id" field.
func (u *UsageReservationUpsertOne) SetSubjectID(v string) *UsageReservationUpsertOne {
	return u.Update(func(s *UsageReservationUpsert) {
		s.SetSubjectID(v)
	})
}

// UpdateSubjectID sets the "subject_id" field to the value that was provided on create.
func (u *UsageReservationUpsertOne) UpdateSubjectID() *UsageReservationUpsertOne {
	return u.Update(func(s *UsageReservationUpsert) {
		s.UpdateSubjectID()
	})
}

// SetScopeType sets the "scope_type" field.
func (u *UsageReservationUpsertOne) SetScopeType(v usagereservation.ScopeType) *UsageReservationUpsertOne {
	return u.Update(func(s *UsageReservationUpsert) {
		s.SetScopeType(v)
	})
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *UsageReservationUpsertOne) UpdateScopeType() *UsageReservationUpsertOne {
	return u.Update(func(s *UsageReservationUpsert) {
		s.UpdateScopeType()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *UsageReservationUpsertOne) SetScopeID(v string) *UsageReservationUpsertOne {
	return u.Update(func(s *UsageReservationUpsert) {
		s.SetScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *UsageReservationUpsertOne) UpdateScopeID() *UsageReservationUpsertOne {
	return u.Update(func(s *UsageReservationUpsert) {
		s.UpdateScopeID()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *UsageReservationUpsertOne) SetResourceID(v string) *UsageReservationUpsertOne {
	return u.Update(func(s *UsageReservationUpsert) {
		s.SetResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *UsageReservationUpsertOne) UpdateResourceID() *UsageReservationUpsertOne {
	return u.Update(func(s *UsageReservationUpsert) {
		s.UpdateResourceID()
	})
}

// SetReserved sets the "reserved" field.
func (u *UsageReservationUpsertOne) SetReserved(v int64) *UsageReservationUpsertOne {
	return u.Update(func(s *UsageReservationUpsert) {
		s.SetReserved(v)
	})
}

// AddReserved adds v to the "reserved" field.
func (u *UsageReservationUpsertOne) AddReserved(v int64) *UsageReservationUpsertOne {
	return u.Update(func(s *UsageReservationUpsert) {
		s.AddReserved(v)
	})
}

// UpdateReserved sets the "reserved" field to the value that was provided on create.
func (u *UsageReservationUpsertOne) UpdateReserved() *UsageReservationUpsertOne {
	return u.Update(func(s *UsageReservationUpsert) {
		s.UpdateReserved()
	})
}

// SetReleasedAt sets the "released_at" field.
func (u *UsageReservationUpsertOne) SetReleasedAt(v time.Time) *UsageReservationUpsertOne {
	return u.Update(func(s *UsageReservationUpsert) {
		s.SetReleasedAt(v)
	})
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *UsageReservationUpsertOne) UpdateReleasedAt() *UsageReservationUpsertOne {
	return u.Update(func(s *UsageReservationUpsert) {
		s.UpdateReleasedAt()
	})
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *UsageReservationUpsertOne) ClearReleasedAt() *UsageReservationUpsertOne {
	return u.Update(func(s *UsageReservationUpsert) {
		s.ClearReleasedAt()
	})
}

// Exec executes the query.
func (u *UsageReservationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageReservationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageReservationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UsageReservationUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: UsageReservationUpsertOne.ID is not supported by MySQL driver. Use UsageReservationUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UsageReservationUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UsageReservationCreateBulk is the builder for creating many UsageReservation entities in bulk.
type UsageReservationCreateBulk struct {
	config
	err      error
	builders []*UsageReservationCreate
	conflict []sql.ConflictOption
}

// Save creates the UsageReservation entities in the database.
func (_c *UsageReservationCreateBulk) Save(ctx context.Context) ([]*UsageReservation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UsageReservation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageReservationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsageReservationCreateBulk) SaveX(ctx context.Context) []*UsageReservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageReservationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageReservationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageReservation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageReservationUpsert) {
//			SetLimitDefinitionID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageReservationCreateBulk) OnConflict(opts ...sql.ConflictOption) *UsageReservationUpsertBulk {
	_c.conflict = opts
	return &UsageReservationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageReservation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageReservationCreateBulk) OnConflictColumns(columns ...string) *UsageReservationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageReservationUpsertBulk{
		create: _c,
	}
}

// UsageReservationUpsertBulk is the builder for "upsert"-ing
// a bulk of UsageReservation nodes.
type UsageReservationUpsertBulk struct {
	create *UsageReservationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UsageReservation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(usagereservation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UsageReservationUpsertBulk) UpdateNewValues() *UsageReservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(usagereservation.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usagereservation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageReservation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UsageReservationUpsertBulk) Ignore() *UsageReservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageReservationUpsertBulk) DoNothing() *UsageReservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageReservationCreateBulk.OnConflict
// documentation for more info.
func (u *UsageReservationUpsertBulk) Update(set func(*UsageReservationUpsert)) *UsageReservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageReservationUpsert{UpdateSet: update})
	}))
	return u
}

// SetLimitDefinitionID sets the "limit_definition_id" field.
func (u *UsageReservationUpsertBulk) SetLimitDefinitionID(v uuid.UUID) *UsageReservationUpsertBulk {
	return u.Update(func(s *UsageReservationUpsert) {
		s.SetLimitDefinitionID(v)
	})
}

// UpdateLimitDefinitionID sets the "limit_definition_id" field to the value that was provided on create.
func (u *UsageReservationUpsertBulk) UpdateLimitDefinitionID() *UsageReservationUpsertBulk {
	return u.Update(func(s *UsageReservationUpsert) {
		s.UpdateLimitDefinitionID()
	})
}

// SetSubjectID sets the "subject_id" field.
func (u *UsageReservationUpsertBulk) SetSubjectID(v string) *UsageReservationUpsertBulk {
	return u.Update(func(s *UsageReservationUpsert) {
		s.SetSubjectID(v)
	})
}

// UpdateSubjectID sets the "subject_id" field to the value that was provided on create.
func (u *UsageReservationUpsertBulk) UpdateSubjectID() *UsageReservationUpsertBulk {
	return u.Update(func(s *UsageReservationUpsert) {
		s.UpdateSubjectID()
	})
}

// SetScopeType sets the "scope_type" field.
func (u *UsageReservationUpsertBulk) SetScopeType(v usagereservation.ScopeType) *UsageReservationUpsertBulk {
	return u.Update(func(s *UsageReservationUpsert) {
		s.SetScopeType(v)
	})
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *UsageReservationUpsertBulk) UpdateScopeType() *UsageReservationUpsertBulk {
	return u.Update(func(s *UsageReservationUpsert) {
		s.UpdateScopeType()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *UsageReservationUpsertBulk) SetScopeID(v string) *UsageReservationUpsertBulk {
	return u.Update(func(s *UsageReservationUpsert) {
		s.SetScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *UsageReservationUpsertBulk) UpdateScopeID() *UsageReservationUpsertBulk {
	return u.Update(func(s *UsageReservationUpsert) {
		s.UpdateScopeID()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *UsageReservationUpsertBulk) SetResourceID(v string) *UsageReservationUpsertBulk {
	return u.Update(func(s *UsageReservationUpsert) {
		s.SetResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *UsageReservationUpsertBulk) UpdateResourceID() *UsageReservationUpsertBulk {
	return u.Update(func(s *UsageReservationUpsert) {
		s.UpdateResourceID()
	})
}

// SetReserved sets the "reserved" field.
func (u *UsageReservationUpsertBulk) SetReserved(v int64) *UsageReservationUpsertBulk {
	return u.Update(func(s *UsageReservationUpsert) {
		s.SetReserved(v)
	})
}

// AddReserved adds v to the "reserved" field.
func (u *UsageReservationUpsertBulk) AddReserved(v int64) *UsageReservationUpsertBulk {
	return u.Update(func(s *UsageReservationUpsert) {
		s.AddReserved(v)
	})
}

// UpdateReserved sets the "reserved" field to the value that was provided on create.
func (u *UsageReservationUpsertBulk) UpdateReserved() *UsageReservationUpsertBulk {
	return u.Update(func(s *UsageReservationUpsert) {
		s.UpdateReserved()
	})
}

// SetReleasedAt sets the "released_at" field.
func (u *UsageReservationUpsertBulk) SetReleasedAt(v time.Time) *UsageReservationUpsertBulk {
	return u.Update(func(s *UsageReservationUpsert) {
		s.SetReleasedAt(v)
	})
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *UsageReservationUpsertBulk) UpdateReleasedAt() *UsageReservationUpsertBulk {
	return u.Update(func(s *UsageReservationUpsert) {
		s.UpdateReleasedAt()
	})
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *UsageReservationUpsertBulk) ClearReleasedAt() *UsageReservationUpsertBulk {
	return u.Update(func(s *UsageReservationUpsert) {
		s.ClearReleasedAt()
	})
}

// Exec executes the query.
func (u *UsageReservationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UsageReservationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageReservationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageReservationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
