// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/limitdefinition"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/usagereservation"
	"github.com/google/uuid"
)

// UsageReservationUpdate is the builder for updating UsageReservation entities.
type UsageReservationUpdate struct {
	config
	hooks    []Hook
	mutation *UsageReservationMutation
}

// Where appends a list predicates to the UsageReservationUpdate builder.
func (_u *UsageReservationUpdate) Where(ps ...predicate.UsageReservation) *UsageReservationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLimitDefinitionID sets the "limit_definition_id" field.
func (_u *UsageReservationUpdate) SetLimitDefinitionID(v uuid.UUID) *UsageReservationUpdate {
	_u.mutation.SetLimitDefinitionID(v)
	return _u
}

// SetNillableLimitDefinitionID sets the "limit_definition_id" field if the given value is not nil.
func (_u *UsageReservationUpdate) SetNillableLimitDefinitionID(v *uuid.UUID) *UsageReservationUpdate {
	if v != nil {
		_u.SetLimitDefinitionID(*v)
	}
	return _u
}

// SetSubjectID sets the "subject_id" field.
func (_u *UsageReservationUpdate) SetSubjectID(v string) *UsageReservationUpdate {
	_u.mutation.SetSubjectID(v)
	return _u
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (_u *UsageReservationUpdate) SetNillableSubjectID(v *string) *UsageReservationUpdate {
	if v != nil {
		_u.SetSubjectID(*v)
	}
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *UsageReservationUpdate) SetScopeType(v usagereservation.ScopeType) *UsageReservationUpdate {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *UsageReservationUpdate) SetNillableScopeType(v *usagereservation.ScopeType) *UsageReservationUpdate {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *UsageReservationUpdate) SetScopeID(v string) *UsageReservationUpdate {
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *UsageReservationUpdate) SetNillableScopeID(v *string) *UsageReservationUpdate {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *UsageReservationUpdate) SetResourceID(v string) *UsageReservationUpdate {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *UsageReservationUpdate) SetNillableResourceID(v *string) *UsageReservationUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetReserved sets the "reserved" field.
func (_u *UsageReservationUpdate) SetReserved(v int64) *UsageReservationUpdate {
	_u.mutation.ResetReserved()
	_u.mutation.SetReserved(v)
	return _u
}

// SetNillableReserved sets the "reserved" field if the given value is not nil.
func (_u *UsageReservationUpdate) SetNillableReserved(v *int64) *UsageReservationUpdate {
	if v != nil {
		_u.SetReserved(*v)
	}
	return _u
}

// AddReserved adds value to the "reserved" field.
func (_u *UsageReservationUpdate) AddReserved(v int64) *UsageReservationUpdate {
	_u.mutation.AddReserved(v)
	return _u
}

// SetReleasedAt sets the "released_at" field.
func (_u *UsageReservationUpdate) SetReleasedAt(v time.Time) *UsageReservationUpdate {
	_u.mutation.SetReleasedAt(v)
	return _u
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_u *UsageReservationUpdate) SetNillableReleasedAt(v *time.Time) *UsageReservationUpdate {
	if v != nil {
		_u.SetReleasedAt(*v)
	}
	return _u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (_u *UsageReservationUpdate) ClearReleasedAt() *UsageReservationUpdate {
	_u.mutation.ClearReleasedAt()
	return _u
}

// SetLimitDefinition sets the "limit_definition" edge to the LimitDefinition entity.
func (_u *UsageReservationUpdate) SetLimitDefinition(v *LimitDefinition) *UsageReservationUpdate {
	return _u.SetLimitDefinitionID(v.ID)
}

// Mutation returns the UsageReservationMutation object of the builder.
func (_u *UsageReservationUpdate) Mutation() *UsageReservationMutation {
	return _u.mutation
}

// ClearLimitDefinition clears the "limit_definition" edge to the LimitDefinition entity.
func (_u *UsageReservationUpdate) ClearLimitDefinition() *UsageReservationUpdate {
	_u.mutation.ClearLimitDefinition()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageReservationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageReservationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageReservationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageReservationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageReservationUpdate) check() error {
	if v, ok := _u.mutation.SubjectID(); ok {
		if err := usagereservation.SubjectIDValidator(v); err != nil {
			return &ValidationError{Name: "subject_id", err: fmt.Errorf(`ent: validator failed for field "UsageReservation.subject_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := usagereservation.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "UsageReservation.scope_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceID(); ok {
		if err := usagereservation.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "UsageReservation.resource_id": %w`, err)}
		}
	}
	if _u.mutation.LimitDefinitionCleared() && len(_u.mutation.LimitDefinitionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UsageReservation.limit_definition"`)
	}
	return nil
}

func (_u *UsageReservationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagereservation.Table, usagereservation.Columns, sqlgraph.NewFieldSpec(usagereservation.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubjectID(); ok {
		_spec.SetField(usagereservation.FieldSubjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(usagereservation.FieldScopeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(usagereservation.FieldScopeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(usagereservation.FieldResourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reserved(); ok {
		_spec.SetField(usagereservation.FieldReserved, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReserved(); ok {
		_spec.AddField(usagereservation.FieldReserved, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReleasedAt(); ok {
		_spec.SetField(usagereservation.FieldReleasedAt, field.TypeTime, value)
	}
	if _u.mutation.ReleasedAtCleared() {
		_spec.ClearField(usagereservation.FieldReleasedAt, field.TypeTime)
	}
	if _u.mutation.LimitDefinitionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagereservation.LimitDefinitionTable,
			Columns: []string{usagereservation.LimitDefinitionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(limitdefinition.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LimitDefinitionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagereservation.LimitDefinitionTable,
			Columns: []string{usagereservation.LimitDefinitionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(limitdefinition.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagereservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageReservationUpdateOne is the builder for updating a single UsageReservation entity.
type UsageReservationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageReservationMutation
}

// SetLimitDefinitionID sets the "limit_definition_id" field.
func (_u *UsageReservationUpdateOne) SetLimitDefinitionID(v uuid.UUID) *UsageReservationUpdateOne {
	_u.mutation.SetLimitDefinitionID(v)
	return _u
}

// SetNillableLimitDefinitionID sets the "limit_definition_id" field if the given value is not nil.
func (_u *UsageReservationUpdateOne) SetNillableLimitDefinitionID(v *uuid.UUID) *UsageReservationUpdateOne {
	if v != nil {
		_u.SetLimitDefinitionID(*v)
	}
	return _u
}

// SetSubjectID sets the "subject_id" field.
func (_u *UsageReservationUpdateOne) SetSubjectID(v string) *UsageReservationUpdateOne {
	_u.mutation.SetSubjectID(v)
	return _u
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (_u *UsageReservationUpdateOne) SetNillableSubjectID(v *string) *UsageReservationUpdateOne {
	if v != nil {
		_u.SetSubjectID(*v)
	}
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *UsageReservationUpdateOne) SetScopeType(v usagereservation.ScopeType) *UsageReservationUpdateOne {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *UsageReservationUpdateOne) SetNillableScopeType(v *usagereservation.ScopeType) *UsageReservationUpdateOne {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *UsageReservationUpdateOne) SetScopeID(v string) *UsageReservationUpdateOne {
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *UsageReservationUpdateOne) SetNillableScopeID(v *string) *UsageReservationUpdateOne {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *UsageReservationUpdateOne) SetResourceID(v string) *UsageReservationUpdateOne {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *UsageReservationUpdateOne) SetNillableResourceID(v *string) *UsageReservationUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetReserved sets the "reserved" field.
func (_u *UsageReservationUpdateOne) SetReserved(v int64) *UsageReservationUpdateOne {
	_u.mutation.ResetReserved()
	_u.mutation.SetReserved(v)
	return _u
}

// SetNillableReserved sets the "reserved" field if the given value is not nil.
func (_u *UsageReservationUpdateOne) SetNillableReserved(v *int64) *UsageReservationUpdateOne {
	if v != nil {
		_u.SetReserved(*v)
	}
	return _u
}

// AddReserved adds value to the "reserved" field.
func (_u *UsageReservationUpdateOne) AddReserved(v int64) *UsageReservationUpdateOne {
	_u.mutation.AddReserved(v)
	return _u
}

// SetReleasedAt sets the "released_at" field.
func (_u *UsageReservationUpdateOne) SetReleasedAt(v time.Time) *UsageReservationUpdateOne {
	_u.mutation.SetReleasedAt(v)
	return _u
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_u *UsageReservationUpdateOne) SetNillableReleasedAt(v *time.Time) *UsageReservationUpdateOne {
	if v != nil {
		_u.SetReleasedAt(*v)
	}
	return _u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (_u *UsageReservationUpdateOne) ClearReleasedAt() *UsageReservationUpdateOne {
	_u.mutation.ClearReleasedAt()
	return _u
}

// SetLimitDefinition sets the "limit_definition" edge to the LimitDefinition entity.
func (_u *UsageReservationUpdateOne) SetLimitDefinition(v *LimitDefinition) *UsageReservationUpdateOne {
	return _u.SetLimitDefinitionID(v.ID)
}

// Mutation returns the UsageReservationMutation object of the builder.
func (_u *UsageReservationUpdateOne) Mutation() *UsageReservationMutation {
	return _u.mutation
}

// ClearLimitDefinition clears the "limit_definition" edge to the LimitDefinition entity.
func (_u *UsageReservationUpdateOne) ClearLimitDefinition() *UsageReservationUpdateOne {
	_u.mutation.ClearLimitDefinition()
	return _u
}

// Where appends a list predicates to the UsageReservationUpdate builder.
func (_u *UsageReservationUpdateOne) Where(ps ...predicate.UsageReservation) *UsageReservationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageReservationUpdateOne) Select(field string, fields ...string) *UsageReservationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageReservation entity.
func (_u *UsageReservationUpdateOne) Save(ctx context.Context) (*UsageReservation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageReservationUpdateOne) SaveX(ctx context.Context) *UsageReservation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageReservationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageReservationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageReservationUpdateOne) check() error {
	if v, ok := _u.mutation.SubjectID(); ok {
		if err := usagereservation.SubjectIDValidator(v); err != nil {
			return &ValidationError{Name: "subject_id", err: fmt.Errorf(`ent: validator failed for field "UsageReservation.subject_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := usagereservation.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "UsageReservation.scope_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceID(); ok {
		if err := usagereservation.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "UsageReservation.resource_id": %w`, err)}
		}
	}
	if _u.mutation.LimitDefinitionCleared() && len(_u.mutation.LimitDefinitionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UsageReservation.limit_definition"`)
	}
	return nil
}

func (_u *UsageReservationUpdateOne) sqlSave(ctx context.Context) (_node *UsageReservation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagereservation.Table, usagereservation.Columns, sqlgraph.NewFieldSpec(usagereservation.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageReservation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagereservation.FieldID)
		for _, f := range fields {
			if !usagereservation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagereservation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubjectID(); ok {
		_spec.SetField(usagereservation.FieldSubjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(usagereservation.FieldScopeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(usagereservation.FieldScopeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(usagereservation.FieldResourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reserved(); ok {
		_spec.SetField(usagereservation.FieldReserved, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReserved(); ok {
		_spec.AddField(usagereservation.FieldReserved, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReleasedAt(); ok {
		_spec.SetField(usagereservation.FieldReleasedAt, field.TypeTime, value)
	}
	if _u.mutation.ReleasedAtCleared() {
		_spec.ClearField(usagereservation.FieldReleasedAt, field.TypeTime)
	}
	if _u.mutation.LimitDefinitionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagereservation.LimitDefinitionTable,
			Columns: []string{usagereservation.LimitDefinitionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(limitdefinition.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LimitDefinitionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagereservation.LimitDefinitionTable,
			Columns: []string{usagereservation.LimitDefinitionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(limitdefinition.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UsageReservation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagereservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
